MODULE BOUNDARY

	USE INTEGRATION
	USE LUDECOMPOSITION

  implicit integer (i-n)
	implicit real(8) (a-h,o-z)

CONTAINS

SUBROUTINE IMPOSEBD(K,F)

	REAL*8, INTENT(INOUT) :: K(2*DOF,2*DOF), F(2*DOF)
	REAL*8 :: SUB_K(DIRICHLET_BDNDX(1,1)%LC_NUM,DIRICHLET_BDNDX(1,1)%LC_NUM), DMY_SUB_K(DIRICHLET_BDNDX(1,1)%LC_NUM, DIRICHLET_BDNDX(1,1)%LC_NUM), DD
	TYPE(DISPLACEMENT) :: SUB_F(DIRICHLET_BDNDX(1,1)%LC_NUM), PINCH_DISP(2)
	INTEGER :: I, J, II, JJ, KK, INDX(DIRICHLET_BDNDX(1,1)%LC_NUM), PINCH_BS_INDX(UBOUND(PINCH_DISP,1))
	TYPE(POINT2D) :: LN_INT

! IMPOSE NEUMANN BOUNDARY CONDITION
!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
	DO J=1, NEUMANN_NUMBD
		DO I=1, NEUMANN_BDNDX(J,1)%LC_NUM
! 			PRINT*, NEUMANN_BDNDX(J,1)%LC_NUM
			LN_INT = INT_F_LN(NEUMANN_BDNDX(J,I)%LC_NDX,J)
			F(NEUMANN_BDNDX(J,I)%GL_NDX) = F(NEUMANN_BDNDX(J,I)%GL_NDX) + LN_INT%X
			F(DOF + NEUMANN_BDNDX(J,I)%GL_NDX) = F(DOF + NEUMANN_BDNDX(J,I)%GL_NDX) + LN_INT%Y
		ENDDO
	ENDDO
	
	PRINT*, 
	PRINT*, '<<< IMPOSING NEUMANN BOUNDARY CONDITIONS : DONE >>>'
	PRINT*, 

! IMPOSE DIRICHLET BOUNDARY CONDITION BY USING LEAST SQUARE METHOD
!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
	SUB_K(:,:) = 0.D0
	SUB_F(:) = DISPLACEMENT(0.D0, 0.D0, 0.D0)

! 	OPEN(121, FILE = 'least_square')
	
	CALL GEN_BD_LN(SUB_K, SUB_F, INT(1))

! 	PRINT*, 'HERE 1'
! 	OPEN(124, FILE = 'sub_k')
! 	OPEN(125, FILE = 'sub_f')
! 	DO I=1, DIRICHLET_BDNDX(1,1)%LC_NUM
! 		WRITE(124, 102) (SUB_K(I,J), J=1,DIRICHLET_BDNDX(1,1)%LC_NUM)
! 		WRITE(125, 102) SUB_F(I)
! 	ENDDO
! 	CLOSE(124)
! 	CLOSE(125)
	
	102 FORMAT(1000(f20.8,1x))
	
	DMY_SUB_K(:,:) = SUB_K(:,:)
	CALL LUDCMP(DMY_SUB_K, DIRICHLET_BDNDX(1,1)%LC_NUM, DIRICHLET_BDNDX(1,1)%LC_NUM, INDX, DD)
	CALL LUBKSB(DMY_SUB_K, DIRICHLET_BDNDX(1,1)%LC_NUM, DIRICHLET_BDNDX(1,1)%LC_NUM, INDX, SUB_F(:)%PIX)
! 	PRINT*, 'HERE 2'
	DMY_SUB_K(:,:) = SUB_K(:,:)
	CALL LUDCMP(DMY_SUB_K, DIRICHLET_BDNDX(1,1)%LC_NUM, DIRICHLET_BDNDX(1,1)%LC_NUM, INDX, DD)
	CALL LUBKSB(DMY_SUB_K, DIRICHLET_BDNDX(1,1)%LC_NUM, DIRICHLET_BDNDX(1,1)%LC_NUM, INDX, SUB_F(:)%PIY)
! 	PRINT*, 'HERE 3'
! 	SUBTRACT EXACT SOLUTIONS FROM THE LOAD VECTOR
	DO I=1, DIRICHLET_BDNDX(1,1)%LC_NUM
		DO J=1, 2*DOF
			F(J) = F(J) - SUB_F(I)%PIX*K(J, DIRICHLET_BDNDX(1,I)%GL_NDX) - SUB_F(I)%PIY*K(J, DOF + DIRICHLET_BDNDX(1,I)%GL_NDX)
		ENDDO
	ENDDO
! PRINT*, 'HERE 4'
	DO I=1, DIRICHLET_BDNDX(1,1)%LC_NUM
		F(DIRICHLET_BDNDX(1,I)%GL_NDX) = SUB_F(I)%PIX
		F(DOF + DIRICHLET_BDNDX(1,I)%GL_NDX) = SUB_F(I)%PIY
		DO J=1, 2*DOF
			K(DIRICHLET_BDNDX(1,I)%GL_NDX,J) = 0.0D0
			K(DOF + DIRICHLET_BDNDX(1,I)%GL_NDX,J) = 0.0D0
			
			K(J,DIRICHLET_BDNDX(1,I)%GL_NDX) = 0.0D0
			K(J,DOF + DIRICHLET_BDNDX(1,I)%GL_NDX) = 0.0D0
		ENDDO
		K(DIRICHLET_BDNDX(1,I)%GL_NDX, DIRICHLET_BDNDX(1,I)%GL_NDX) = 1.0D0
		K(DOF + DIRICHLET_BDNDX(1,I)%GL_NDX, DOF + DIRICHLET_BDNDX(1,I)%GL_NDX) = 1.0D0
	ENDDO

	PRINT*, 
	PRINT*, '<<< IMPOSING ESSENTIAL BOUNDARY CONDITIONS BY USING LEAST SQUARE METHOD : DONE >>>'
	PRINT*, 
!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!


END SUBROUTINE IMPOSEBD

END MODULE BOUNDARY
