MODULE ERRORESTIMATE

	USE NURBS_BASIS
	USE LOADFUNCTION
	USE PATCH_MAPPING
	USE GSQUAD

    IMPLICIT NONE
    
CONTAINS

!----MAX. NORM ESTIMATE----
SUBROUTINE MAXNORM(MAX_NORM, COEFF_SOL)

	REAL*8, INTENT(OUT) :: MAX_NORM(5)
	REAL*8, INTENT(IN) :: COEFF_SOL(2*DOF)
	TYPE(POINT2D) :: MESH, NURBS_PT, TSPT, PHY_PT, REF_PT
	TYPE(INT2D) :: MAXGRID
	INTEGER :: II, I, J
	TYPE(DISPLACEMENT) :: EXDISP, APDISP, ERR_DISP, ERR_LINE_DISP, ERR_POLAR_DISP, TMP_ERR_DISP, MAXDISP
	TYPE(STRESS) :: EXSTR, APSTR, ERR_STR, TMP_ERR_STR, ERR_LINE_STR, ERR_POLAR_STR, MAXSTR
	REAL*8 :: R, THETA

	MAXGRID = INT2D(100,100)
	MESH=POINT2D(1.D0/MAXGRID%A, 1.D0/MAXGRID%B)
	
	ERR_STR = STRESS(0.D0,0.D0,0.D0,0.D0,0.D0)
	ERR_DISP = DISPLACEMENT(0.D0,0.D0,0.D0)
	MAXDISP = DISPLACEMENT(0.D0,0.D0,0.D0)
	MAXSTR = STRESS(0.D0,0.D0,0.D0,0.D0,0.D0)
	
	OPEN(11, FILE = 'ext_disp'); OPEN(12, FILE = 'ext_str')
	OPEN(21, FILE = 'app_disp'); OPEN(22, FILE = 'app_str')
	OPEN(31, FILE = 'err_disp'); OPEN(32, FILE = 'err_str')
	DO J=1, MAXGRID%B+1
		DO I=1, MAXGRID%A+1

			TSPT = POINT2D(MESH%X*(I-1), MESH%Y*(J-1))

			NURBS_PT = GET_PHY_PT(TSPT)

			CALL APPROXSOL(APDISP, APSTR, TSPT, COEFF_SOL)
			EXDISP = EX_DISP(TSPT); EXSTR = EX_STRESS(TSPT)
			
			TMP_ERR_DISP%PIX = DABS(APDISP%PIX - EXDISP%PIX)
			TMP_ERR_DISP%PIY = DABS(APDISP%PIY - EXDISP%PIY)
			
			TMP_ERR_STR%SXX = DABS(APSTR%SXX - EXSTR%SXX)
			TMP_ERR_STR%SYY = DABS(APSTR%SYY - EXSTR%SYY)
			TMP_ERR_STR%SXY = DABS(APSTR%SXY - EXSTR%SXY)

			WRITE(11,*) NURBS_PT, EXDISP%PIX, EXDISP%PIY
			WRITE(12,*) NURBS_PT, EXSTR%SXX, EXSTR%SYY, EXSTR%SXY
			WRITE(21,*) NURBS_PT, APDISP%PIX, APDISP%PIY
			WRITE(22,*) NURBS_PT, APSTR%SXX, APSTR%SYY, APSTR%SXY
			WRITE(31,*) NURBS_PT, TMP_ERR_DISP%PIX, TMP_ERR_DISP%PIY
			WRITE(32,*) NURBS_PT, TMP_ERR_STR%SXX, TMP_ERR_STR%SYY, TMP_ERR_STR%SXY
			
			IF (TMP_ERR_DISP%PIX.GE.ERR_DISP%PIX) THEN
				ERR_DISP%PIX = TMP_ERR_DISP%PIX
			ENDIF
			IF (TMP_ERR_DISP%PIY.GE.ERR_DISP%PIY) THEN
				ERR_DISP%PIY = TMP_ERR_DISP%PIY
			ENDIF
			
			IF (TMP_ERR_STR%SXX.GE.ERR_STR%SXX) THEN
				ERR_STR%SXX = TMP_ERR_STR%SXX
			ENDIF
			IF (TMP_ERR_STR%SYY.GE.ERR_STR%SYY) THEN
				ERR_STR%SYY = TMP_ERR_STR%SYY
			ENDIF
			IF (TMP_ERR_STR%SXY.GE.ERR_STR%SXY) THEN
				ERR_STR%SXY = TMP_ERR_STR%SXY
			ENDIF
			IF (DABS(EXDISP%PIX).GE.MAXDISP%PIX) THEN
				MAXDISP%PIX = DABS(EXDISP%PIX)
			ENDIF
			IF (DABS(EXDISP%PIY).GE.MAXDISP%PIY) THEN
				MAXDISP%PIY = DABS(EXDISP%PIY)
			ENDIF
			IF (DABS(EXSTR%SXX).GE.MAXSTR%SXX) THEN
				MAXSTR%SXX = DABS(EXSTR%SXX)
			ENDIF
			IF (DABS(EXSTR%SYY).GE.MAXSTR%SYY) THEN
				MAXSTR%SYY = DABS(EXSTR%SYY)
			ENDIF
			IF (DABS(EXSTR%SXY).GE.MAXSTR%SXY) THEN
				MAXSTR%SXY = DABS(EXSTR%SXY)
			ENDIF
		ENDDO
		WRITE(11,*) ""; WRITE(12,*) ""
		WRITE(21,*) ""; WRITE(22,*) ""
		WRITE(31,*) ""; WRITE(32,*) ""
	ENDDO
	CLOSE(11); CLOSE(12)
	CLOSE(21); CLOSE(22)
	CLOSE(31); CLOSE(32)

! 	write(char_problem,fmt='(i1)') PROBLEM
! 	write(char_order(1),fmt='(i2.2)') BS_ORDER(1)
! 	write(char_order(2),fmt='(i2.2)') BS_ORDER(2)
! 	write(char_basis(1),fmt='(i2.2)') NUMBS(1)
! 	write(char_basis(2),fmt='(i2.2)') NUMBS(2)
! 	write(char_spe_const,fmt='(i2.2)') INT(special_refinement_const(1))
! 	write(char_geo_const,fmt='(i2.2)') int(geometric_refinement_const(2)) 
! 
! 	write(char_knot_interval(1),fmt='(f4.3)') knot_interval(1)
! 	write(char_knot_interval(2),fmt='(f4.3)') knot_interval(2)
! ! 	write(char_thickness,fmt='(f4.3)') thickness
! 
! 	if (uniform=='NON' .and. refinement=='SHI') THEN
! 		filename = trim('pro') // char_problem // trim('_') // trim('result_p') // char_order(1) // trim('X') // char_order(2) // trim('_b') // char_basis(1) // trim('X') // char_basis(2) // trim('_') // bctype // trim('_') // trim('(') // char_knot_interval(1) // trim(',') // char_knot_interval(2) // trim(')') // trim('_') // refinement
! 	elseif (uniform=='NON' .and. refinement=='SPE') THEN
! 		filename = trim('pro') // char_problem // trim('_') // trim('result_p') // char_order(1) // trim('X') // char_order(2) // trim('_b') // char_basis(1) // trim('X') // char_basis(2) // trim('_') // bctype // trim('_') // refinement // trim('(') // char_spe_const // trim(')')
! 	elseif (uniform=='NON' .and. refinement=='GEO') THEN
! 		filename = trim('pro') // char_problem // trim('_') // trim('result_p') // char_order(1) // trim('X') // char_order(2) // trim('_b') // char_basis(1) // trim('X') // char_basis(2) // trim('_') // bctype // trim('_') // refinement // trim('(') // char_geo_const // trim(')')
! 	elseif (uniform=='NON' .and. refinement=='NON') THEN
! 		filename = trim('pro') // char_problem // trim('_') // trim('result_p') // char_order(1) // trim('X') // char_order(2) // trim('_b') // char_basis(1) // trim('X') // char_basis(2) // trim('_') // bctype
! 	else
! 		filename = trim('pro') // char_problem // trim('_') // trim('result_p') // char_order(1) // trim('X') // char_order(2) // trim('_b') // char_basis(1) // trim('X') // char_basis(2) // trim('_') // bctype // trim('_') // UNIFORM
! 	endif

! 	open(13,file=filename,status='unknown')
! 	WRITE(13,*) "ORDER OF B-SPLINE : ", BS_ORDER
! 	IF (EXTRA_KNOTS(1).EQ.0 .AND. EXTRA_KNOTS(2).EQ.0) THEN
! 		WRITE(13,*) "KNOT INSERTION : NONE"
! 	ELSE
! 		WRITE(13,*) "KNOT INSERTION : ", EXTRA_KNOTS
! 		IF (UNIFORM=='NON') THEN
! 			WRITE(13,*) "UNIFORM : NON-UNIFORM", KNOT_INTERVAL(:)
! 		ELSE
! 			WRITE(13,*) "UNIFORM : UNIFORM"
! 		ENDIF
! 	ENDIF
! 	WRITE(13,*) "BOUNDARY CONDITION : ", BCTYPE
! 	WRITE(13,*) "REFINEMENT TYPE : ", REFINEMENT
! 	WRITE(13,*) "NUMBER OF BASIS FTS : ", NUMBS
! 	WRITE(13,*) 'DEGREE OF FREEDOM : ', 2*DOF - BD_DOF
! 	WRITE(13,*) 'DEGREE OF FREEDOM ON BOUNDARY : ', BD_DOF
! 	WRITE(13,*) ""
! 	WRITE(13,*) "MAXIMUM ERROR FOR DISPLACEMENT ALONG X DIRECTION (%) : ", ERR_DISP%PIX*100.D0
! ! 	WRITE(13,*) "RELATIVE MAXIMUM ERROR FOR PI_X : ", ERROR_DISP(INDICE(2))%PIX/DABS(EXDISP(MAX_INDICE(2))%PIX)
! 	WRITE(13,*) ""
! 	WRITE(13,*) "MAXIMUM ERROR FOR DISPLACEMENT ALONG Y DIRECTION (%) : ", ERR_DISP%PIY*100.D0
! ! 	WRITE(13,*) "RELATIVE MAXIMUM ERROR FOR PI_Y : ", ERROR_DISP(INDICE(3))%PIY/DABS(EXDISP(MAX_INDICE(3))%PIY)
! 	WRITE(13,*) ""
! 	WRITE(13,*) "MAXIMUM ERROR FOR STRESS ALONG X DIRECTION (%) : ", ERR_STR%SXX*100.D0
! 	WRITE(13,*) ""
! 	WRITE(13,*) "MAXIMUM ERROR FOR STRESS ALONG Y DIRECTION (%) : ", ERR_STR%SYY*100.D0
! 	WRITE(13,*) ""
! 	WRITE(13,*) "MAXIMUM ERROR FOR STRESS ALONG XY DIRECTION (%) : ", ERR_STR%SXY*100.D0
! 	CLOSE(13)
	
! 	PRINT*, ERR_DISP
! 	PRINT*, MAXDISP
! 	PRINT*, ERR_STR
! 	PRINT*, MAXSTR

	MAX_NORM(1) = ERR_DISP%PIX*100.D0/MAXDISP%PIX
	MAX_NORM(2) = ERR_DISP%PIY*100.D0/MAXDISP%PIY
	MAX_NORM(3) = ERR_STR%SXX*100.D0/MAXSTR%SXX
	MAX_NORM(4) = ERR_STR%SYY*100.D0/MAXSTR%SYY
	MAX_NORM(5) = ERR_STR%SXY*100.D0/MAXSTR%SXY
	
END SUBROUTINE MAXNORM

SUBROUTINE ENRGY(ENRG, DMY_K, SOL)

	REAL*8, INTENT(IN) :: DMY_K(2*DOF,2*DOF), SOL(2*DOF)
	REAL*8, INTENT(OUT) :: ENRG(4)
	REAL*8 :: AP, TR
	INTEGER :: I, J

	AP = 0.50D0*DOT_PRODUCT(SOL, MATMUL(DMY_K, SOL))

	IF (PROBLEM.EQ.0) THEN
		TR = 0.5d0*(STRESS_E(1,1) + STRESS_E(1,2) + STRESS_E(2,1) + STRESS_E(2,2))
	ELSEIF (PROBLEM.EQ.1) THEN
		TR = 5860.810d0
	ELSEIF (PROBLEM.EQ.2) THEN
		TR = 1253.66300366300360d0
	ELSEIF (PROBLEM.EQ.3) THEN
		TR = 4.474666666666666792195883317620D0
	ENDIF

! 	CALL EXT_ENERGY(TR)

	ENRG(1) = TR
	ENRG(2) = AP

	ENRG(3) = DSQRT(DABS(ENRG(2) - ENRG(1)))*100.D0
	ENRG(4) = DSQRT(DABS(ENRG(2) - ENRG(1)) / ENRG(1))*100.D0

!   OPEN(13, FILE=filename, STATUS='unknown', POSITION='append')
! 	WRITE(13,*) ''
! 	WRITE(13,*) 'EXACT ENERGY : ', TR
! 	WRITE(13,*) 'APPR. ENERGY : ', AP
! 	WRITE(13,*) 'ABS.  ENERGY NORM ERROR (%) : ', ENRG(3)*100.D0
! 	WRITE(13,*) 'REL.  ENERGY NORM ERROR (%) : ', ENRG(4)*100.D0
! 	CLOSE(13)
! 
! 	WRITE(*,*) ""
! 	WRITE(*,*) 'REL.  ENERGY NORM ERROR (%) : ', ENRG(4)*100.D0
! 	WRITE(*,*) ""

END SUBROUTINE ENRGY

SUBROUTINE L2_NORM_ERROR(L2_NORM, COEFF_SOL)
	
	REAL*8, INTENT(OUT) :: L2_NORM(2)
	REAL*8, INTENT(IN) :: COEFF_SOL(DOF)
	INTEGER :: I, J, II, JJ, SUB_NUMLN(2), N, KK, K
	REAL*8 :: SUB_LN_LENGTH(2), WEIGHT, DIFF_NN, DET_M
	TYPE(VEC2D) :: SUB_LN
	TYPE(POINT2D) :: GSPT, DMY_GSPT, PHY_PT
	TYPE(MATRIX_22) :: JACOB
	TYPE(DISPLACEMENT) :: EXDISP, APDISP, INTF(2)
	TYPE(STRESS) :: APSTRESS
	
	N = NUMGSPT
	SUB_NUMLN = (/1,1/)
	INTF(:) = DISPLACEMENT(0.D0,0.D0,0.D0)
	
	DO JJ = 1, NUMIR(1)-1
		SUB_LN_LENGTH(1) = DABS(IR_GRID(1,JJ+1) - IR_GRID(1,JJ))/(1.D0*SUB_NUMLN(1))
		DO J=1, SUB_NUMLN(1)
			CALL GAULEG(IR_GRID(1,JJ)+(J-1)*SUB_LN_LENGTH(1), IR_GRID(1,JJ)+J*SUB_LN_LENGTH(1), GSX, GSXW, N)
			DO II = 1, NUMIR(2)-1
				SUB_LN_LENGTH(2) = DABS(IR_GRID(2,II+1) - IR_GRID(2,II))/(1.D0*SUB_NUMLN(2))
				DO I = 1, SUB_NUMLN(2)
					CALL GAULEG(IR_GRID(2,II)+(I-1)*SUB_LN_LENGTH(2), IR_GRID(2,II)+I*SUB_LN_LENGTH(2), GSY, GSYW, N)
					DO KK = 1, N
						DO K = 1, N
							GSPT = POINT2D(GSX(KK),GSY(K))
							DMY_GSPT = GSPT
							JACOB= GET_JACOBIAN_MATRIX(DMY_GSPT)
							DET_M = .DETERMINANT.JACOB
							PHY_PT = GET_PHY_PT(DMY_GSPT)
							EXDISP = EX_DISP(DMY_GSPT)
							CALL APPROXSOL(APDISP, APSTRESS, DMY_GSPT, COEFF_SOL)
							INTF(1)%PIX = INTF(1)%PIX + (EXDISP%PIX - APDISP%PIX)**2*DET_M*GSXW(KK)*GSYW(K)
							INTF(1)%PIY = INTF(1)%PIY + (EXDISP%PIY - APDISP%PIY)**2*DET_M*GSXW(KK)*GSYW(K)
							INTF(2)%PIX = INTF(2)%PIX + EXDISP%PIX**2*DET_M*GSXW(KK)*GSYW(K)
							INTF(2)%PIY = INTF(2)%PIY + EXDISP%PIY**2*DET_M*GSXW(KK)*GSYW(K)
						ENDDO
					ENDDO
				ENDDO
			ENDDO
		ENDDO
	ENDDO
	
	L2_NORM(1) = DSQRT(INTF(1)%PIX/INTF(2)%PIX)*100.D0
	L2_NORM(2) = DSQRT(INTF(1)%PIY/INTF(2)%PIY)*100.D0
	
! 	OPEN(13, FILE=filename, STATUS='unknown', POSITION='append')
! 	WRITE(13,*) ''
! 	WRITE(13,*) 'RELATIVE ERROR IN L2 NORM (%) OF DISPLACEMENT ALONG X-DIRECTION : ', L2_NORM(1)
! 	WRITE(13,*) 'RELATIVE ERROR IN L2 NORM (%) OF DISPLACEMENT ALONG Y-DIRECTION : ', L2_NORM(2)
! 	CLOSE(1)
	
END SUBROUTINE L2_NORM_ERROR
	
SUBROUTINE APPROXSOL(APDISP, APSTRESS, PT2D, COEFF_SOL)

	TYPE(POINT2D), INTENT(IN) :: PT2D
	REAL*8, INTENT(IN) :: COEFF_SOL(2*DOF)
	TYPE(DISPLACEMENT), INTENT(OUT) :: APDISP
	TYPE(STRESS), INTENT(OUT) :: APSTRESS
	
	TYPE(FVALUE) :: SF(DOF), LOCAL_SF((BASIS_KVEC(1)%POLY_ORDER+1)*(BASIS_KVEC(2)%POLY_ORDER+1))
	INTEGER :: I, J, II, JJ, KK, GLOBAL_INDX
	TYPE(INT2D) :: INDX((BASIS_KVEC(1)%POLY_ORDER+1)*(BASIS_KVEC(2)%POLY_ORDER+1))
	TYPE(POINT2D) :: NURBS_PT, POLAR_PT
	
	REAL*8 :: DMY_STRAIN(3), APP_STRAIN(3), DMY_STRESS(3)
	
	APDISP = DISPLACEMENT(0.0D0, 0.0D0, 0.0D0)
	APSTRESS = STRESS(0.0D0, 0.0D0, 0.0D0, 0.D0, 0.D0)
	SF(:) = FVALUE(0.D0,0.D0,0.D0,0.D0,0.D0,0.D0)
	
	CALL GET_ALL_PHY_BASIS(LOCAL_SF(:), INDX, PT2D)
	DO JJ=1, UBOUND(LOCAL_SF,1)
		DO II=1, DOF
			IF (NDX(1,II).EQ.INDX(JJ)%A .AND. NDX(2,II).EQ.INDX(JJ)%B) THEN
				GLOBAL_INDX = II
				GOTO 111
			ENDIF
		ENDDO
		111 CONTINUE
		SF(GLOBAL_INDX) = LOCAL_SF(JJ)
	ENDDO
	APDISP%PIX = DOT_PRODUCT(COEFF_SOL(1:DOF), SF(:)%D00)
	APDISP%PIY = DOT_PRODUCT(COEFF_SOL(DOF+1:2*DOF), SF(:)%D00)
	APP_STRAIN = (/0.D0,0.D0,0.D0/)
	DO II=1, DOF
		DMY_STRAIN = (/COEFF_SOL(II)*SF(II)%D10, COEFF_SOL(DOF+II)*SF(II)%D01, COEFF_SOL(II)*SF(II)%D01+ COEFF_SOL(DOF+II)*SF(II)%D10/)
		APP_STRAIN = (/APP_STRAIN(1) + DMY_STRAIN(1),APP_STRAIN(2) + DMY_STRAIN(2),APP_STRAIN(3) + DMY_STRAIN(3)/)
	ENDDO
	DMY_STRESS = MATMUL(STRESS_E, APP_STRAIN)
	APSTRESS = STRESS(DMY_STRESS(1), DMY_STRESS(2), DMY_STRESS(3), 0.D0, 0.D0)
			
! 			APMOMENT(KK)%MXX = STRESS_D(1,1)*DOT_PRODUCT(COEFF_SOL(DOF+1:2*DOF), SF(:)%D10) + &
! 												 STRESS_D(1,2)*DOT_PRODUCT(COEFF_SOL(2*DOF+1:3*DOF), SF(:)%D01)
! 			APMOMENT(KK)%MYY = STRESS_D(1,2)*DOT_PRODUCT(COEFF_SOL(DOF+1:2*DOF), SF(:)%D10) + &
! 												 STRESS_D(2,2)*DOT_PRODUCT(COEFF_SOL(2*DOF+1:3*DOF), SF(:)%D01)
! 			APMOMENT(KK)%MXY = STRESS_D(3,3)*(DOT_PRODUCT(COEFF_SOL(DOF+1:2*DOF), SF(:)%D01) + &
! 																				DOT_PRODUCT(COEFF_SOL(2*DOF+1:3*DOF), SF(:)%D10))
	
END SUBROUTINE APPROXSOL

END MODULE ERRORESTIMATE
