! NAME : HYUNJU KIM
! DATE : 11 / 8 / 2010

MODULE GLBVAR

	USE NEWTYPE

  IMPLICIT NONE

!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
!
!   GLOBAL PARAMETER

	REAL(8), PARAMETER :: PI=DACOS(-1.0D0)
	REAL(8), PARAMETER :: DEGREE = PI/180.D0
	REAL(8), PARAMETER:: EPS=5.0D-15
	INTEGER :: PROBLEM

	! B-SPLINE GLOBAL VARIABLES
	INTEGER, DIMENSION(1:2), PARAMETER :: EXTRA_KNOTS = (/0,0/), BD_KNOTS = (/0,0/)
	INTEGER :: BS_ORDER(2)

	CHARACTER(LEN=3), PARAMETER :: UNIFORM = 'NON'
	CHARACTER(LEN=3), PARAMETER :: REFINEMENT = 'NON'	! SPE = SPECIAL REFINEMENT	GEO = GEOMETRIC REFINEMENT	KPD = P-VERSION ON D-DEPENDENT MESH	 SHI = SHISHINKIN MESH

	INTEGER, DIMENSION(1:2) :: GEO_NUMBS
	REAL(8), DIMENSION(1:2) :: KNOT_INTERVAL = (/0.05d0,0.001d0/)
	INTEGER :: NUMBS(2), DOF, BD_DOF
	INTEGER, PARAMETER :: NEUMANN_NUMBD = 3, DIRICHLET_NUMBD = 1
	TYPE(BD_INFO) :: NEUMANN_BDNDX(NEUMANN_NUMBD,MAX_LENGTH), DIRICHLET_BDNDX(DIRICHLET_NUMBD,MAX_LENGTH)
	LOGICAL, ALLOCATABLE :: BD_MASK(:)
	
	TYPE(POINT2D) :: BDPT

	!!  VARIABLES FOR GEOMETRIC MAP
	TYPE(KNOT_VECTOR), SAVE :: GEO_KVEC(2), BASIS_KVEC(2)
	TYPE(CONTROL_POINTS_2D), SAVE :: GEO_CTL

		!!  CONNECTIVITY ARRAY
	INTEGER, ALLOCATABLE :: CARRAY(:,:)
	
	!!  BINOMIAL COEFFICIENTS
	REAL(8) :: BINOM(MAX_DIFF_ORDER,0:MAX_DIFF_ORDER)

	! INTEGRAL GLOBAL VARIABLES
	INTEGER, PARAMETER :: NUMGSPT = 18
	REAL*8 :: IR_GRID(2, MAX_LENGTH)
	INTEGER :: NUMIR(2)

	REAL*8 :: GSX(NUMGSPT), GSXW(NUMGSPT), GSY(NUMGSPT), GSYW(NUMGSPT)
	INTEGER, ALLOCATABLE :: NDX(:,:)

	CHARACTER(LEN=2) :: CHAR_ORDER(2)
	CHARACTER(LEN=2) :: CHAR_BASIS(2)
	CHARACTER(LEN=5) :: CHAR_KNOT_INTERVAL(2)
	CHARACTER(LEN=2) :: CHAR_SPE_CONST
	CHARACTER(LEN=2) :: CHAR_GEO_CONST
	CHARACTER(LEN=3) :: CHAR_PROBLEM
	CHARACTER(LEN=100) :: FILENAME

	REAL*8, DIMENSION(1:2) :: SPECIAL_REFINEMENT_CONST = (/6.D0, 1.D0 /)
	REAL*8, DIMENSION(1:2) :: GEOMETRIC_REFINEMENT_CONST = (/1.D0, 5.D0/)
	
!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
!	MATERIAL COEFFICIENTS

	INTEGER, DIMENSION(1:2), PARAMETER :: ORDER1=(/ 1, 2 /)
	INTEGER, DIMENSION(1:2), PARAMETER :: ORDER2=(/ 2, 1 /)

	CHARACTER(LEN=6), PARAMETER :: PLANE_TYPE = 'STRESS'
	CHARACTER(LEN=5), PARAMETER :: BCTYPE = 'DIRIC'

	REAL*8, PARAMETER :: LENGTH = 48.D0
	REAL*8, PARAMETER :: THICKNESS = 12.D0
	REAL*8, PARAMETER :: SCALE_FACTOR = THICKNESS**3/12.D0
	
	REAL*8, PARAMETER :: E = 3.D0*10.D0**7 					! YOUNG'S MODULUS
	REAL*8, PARAMETER :: V = 0.30D0		  				! POISSON RATION
	REAL*8, PARAMETER :: RESULTANT = 1000.D0

	REAL*8 :: E_ZERO, V_ZERO
	REAL*8 :: STRESS_E33
	REAL*8 :: STRESS_E11
	REAL*8 :: STRESS_E22
	REAL*8 :: STRESS_E12
	REAL*8 :: STRESS_E21

	REAL*8, DIMENSION(3,3) :: STRESS_E
	
! 	REAL*8, PARAMETER :: SIGMA = 100.D0
! 	REAL*8, PARAMETER :: MU = E/(2.D0*(1.D0+V))
! 	REAL*8, PARAMETER :: KAPPA = (3.D0-V)/(1.D0+V)
! 	REAL*8, PARAMETER :: LENGTH_CRACK = 2.D0
! 	REAL*8, PARAMETER :: LENGTH_DOMAIN = 4.D0

!		Center - Cracked Stress Intensity Factor
! 	REAL*8, PARAMETER :: KI = SIGMA*DSQRT(PI*HALF_LENGTH_CRACK)*(1.D0 + 0.128D0*(HALF_LENGTH_CRACK/HALF_LENGTH_DOMAIN) + 0.288D0*(HALF_LENGTH_CRACK/HALF_LENGTH_DOMAIN)**2 + 1.523D0*(HALF_LENGTH_CRACK/HALF_LENGTH_DOMAIN)**3)

!		Single - Edged - Cracked Stress Intensity Factor
! 	REAL*8, PARAMETER :: KI = SIGMA*DSQRT(PI*LENGTH_CRACK)*(1.12D0 - 0.23D0*(LENGTH_CRACK/LENGTH_DOMAIN) + 10.55D0*(LENGTH_CRACK/LENGTH_DOMAIN)**2 - 21.72D0*(LENGTH_CRACK/LENGTH_DOMAIN)**3 + 30.39D0*(LENGTH_CRACK/LENGTH_DOMAIN)**4)
!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!

	TYPE(POINT2D), PARAMETER :: PT0 = POINT2D(0.D0,0.D0)

END MODULE GLBVAR
