PROGRAM MAIN

  USE GEOMETRY
  USE KNOT_HANDLING
  USE PLOT
  USE BOUNDARY
  USE ERRORESTIMATE
	USE LOADFUNCTION
	
  implicit integer (i-n)
	implicit real(8) (a-h,o-z)

	REAL*8, ALLOCATABLE :: STIF_K(:,:), DMY_K(:,:), F(:)
  REAL*8 :: TMPERR, LUD, ENRG(4), L2_NORM(2), MAX_NORM(5)
  REAL :: CPTS, CPTE
 	INTEGER :: I, J, II, JJ, MAIN_I, MAIN_J
 	INTEGER, ALLOCATABLE :: INDX(:)
	TYPE(INT2D) :: MAIN_INDX

	PROBLEM = 3
	OPEN(133, FILE = 'robin_pv')
	DO I=2, 3
		BS_ORDER = (/I,I/)
 	
	CALL CPU_TIME(CPTS)

	CALL GET_GEO()

	ALLOCATE(STIF_K(2*DOF,2*DOF), DMY_K(2*DOF, 2*DOF), F(2*DOF), INDX(2*DOF), CARRAY(DOF,2))

	CALL PLOTGM()

	CALL GEN_KF(STIF_K, F)

	DMY_K = STIF_K

! 	OPEN(1, FILE = 'f1')
! 	DO I=1, 2*DOF
! 		WRITE(1,*) F(I)
! 	ENDDO
! 	CLOSE(1)
! 	
! 	OPEN(1, FILE = 'k1')
! 	DO I=1, 2*DOF
! 		WRITE(1,*) (STIF_K(I,J), J=1,2*DOF)
! 	ENDDO
! 	CLOSE(1)
	
	CALL IMPOSEBD(STIF_K,F)

! 	OPEN(1, FILE = 'f2')
! 	DO I=1, 2*DOF
! 		WRITE(1,*) F(I)
! 	ENDDO
! 	CLOSE(1)
! 	
! 	OPEN(1, FILE = 'k2')
! 	DO I=1, 2*DOF
! 		WRITE(1,*) (STIF_K(I,J), J=1,2*DOF)
! 	ENDDO
! 	CLOSE(1)

! 	RES_K = STIF_K
! 	DMY_F = F
! 	
! 	OPEN(1, FILE = 'f2')
! 	DO I=1, DOF
! 		WRITE(1,*) F(I)
! 	ENDDO
! 	CLOSE(1)
	
	CALL LUDCMP(STIF_K, 2*DOF, 2*DOF, INDX, LUD)
	CALL LUBKSB(STIF_K, 2*DOF, 2*DOF, INDX, F)

! 	OPEN(1, FILE = 'sol')
! 	DO I=1, 3*DOF
! 		WRITE(1,*) F(I)
! 	ENDDO
! 	CLOSE(1)
	
  CALL MAXNORM(MAX_NORM, F)
	CALL L2_NORM_ERROR(L2_NORM, F)
  CALL ENRGY(ENRG, DMY_K, F)
	
	PRINT*, DOF, BS_ORDER(1), MAX_NORM, L2_NORM, ENRG(4)
	WRITE(133,*) DOF, BS_ORDER(1), MAX_NORM, L2_NORM, ENRG(4)

	CALL CPU_TIME(CPTE)

	PRINT*, ""
 	PRINT*, "ELAPSED CPU TIME : ", CPTE - CPTS
 	PRINT*, ""

	DEALLOCATE(STIF_K, DMY_K, F, INDX, BD_MASK, NDX, CARRAY)

	ENDDO
	close(133)
	
END PROGRAM MAIN
