MODULE BOUNDARY

	USE INTEGRATION
	USE LUDECOMPOSITION

  implicit integer (i-n)
	implicit real(8) (a-h,o-z)

CONTAINS

SUBROUTINE IMPOSEBD(K, F)

	REAL*8, INTENT(INOUT) :: K(DOF,DOF), F(DOF)
	REAL*8 :: SUB_K(SUM(BDNDX(:,1)%LC_NUM),SUM(BDNDX(:,1)%LC_NUM))
	TYPE(POINT2D) :: DMY_SUB_F(SUM(BDNDX(:,1)%LC_NUM))
	
	TYPE(POINT2D) :: PINCH_DISP(2), SUB_F(SUM(BDNDX(:,1)%LC_NUM))
	REAL*8 :: DMY_SUB_K(SUM(BDNDX(:,1)%LC_NUM), SUM(BDNDX(:,1)%LC_NUM)), DD
	INTEGER :: I, J, II, JJ, KK, INDX(SUM(BDNDX(:,1)%LC_NUM)), PINCH_BS_INDX(2), LC_NUM_SUM
	TYPE(POINT2D) :: LN_INT

	DO I=1, DOF
		DO J=1, DOF
			IF (DABS(K(I,J)).LE.EPS) THEN
				K(I,J) = 0.D0
			ENDIF
		ENDDO
	ENDDO
	
! IMPOSE NEUMANN BOUNDARY CONDITION
!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
! 	DO J=1, NEUMANN_NUMBD
! 		DO I=1, NEUMANN_BDNDX(J,1)%LC_NUM
! ! 			PRINT*, NEUMANN_BDNDX(J,1)%LC_NUM
! 			LN_INT = INT_F_LN(NEUMANN_BDNDX(J,I),J)
! 			F(NEUMANN_BDNDX(J,I)%GL_NDX) = F(NEUMANN_BDNDX(J,I)%GL_NDX) + LN_INT%X
! 			F(DOF + NEUMANN_BDNDX(J,I)%GL_NDX) = F(DOF + NEUMANN_BDNDX(J,I)%GL_NDX) + LN_INT%Y
! 		ENDDO
! 	ENDDO
! 
! ! PINCH TWO POINTS IN THE CASE OF IMPOSING NEUMANN B.C. ON ALL BOUNDARY
! 	PINCH_DISP(1) = EX_DISP(POINT2D(0.D0,1.D0),1) !<----- CAUTION!!!!! PUT A REFERENCE POINT CORRESPONDING TO A PINCH POINT ON PHYSICAL DOMAIN
! 	PINCH_DISP(2) = EX_DISP(POINT2D(1.D0,1.D0),2) !<----- CAUTION!!!!! PUT A REFERENCE POINT CORRESPONDING TO A PINCH POINT ON PHYSICAL DOMAIN
! 
! 	DO J=1, 2*DOF
! 		F(J) = F(J) - PINCH_DISP(1)%X*K(J,LOCAL_DOF(1)-NUMBS(1)+1) - PINCH_DISP(1)%Y*K(J, DOF + LOCAL_DOF(1)-NUMBS(1)+1)
! 		F(J) = F(J) - PINCH_DISP(2)%X*K(J,DOF) - PINCH_DISP(2)%Y*K(J, 2*DOF)
! 	ENDDO
! 
! 	F(LOCAL_DOF(1)-NUMBS(1)+1) = PINCH_DISP(1)%X; F(DOF) = PINCH_DISP(2)%X
! 	F(DOF + LOCAL_DOF(1)-NUMBS(1)+1) = PINCH_DISP(1)%Y; F(2*DOF) = PINCH_DISP(2)%Y
! 	DO J=1, 2*DOF
! 		K(LOCAL_DOF(1)-NUMBS(1)+1,J) = 0.0D0; K(DOF,J) = 0.D0
! 		K(DOF + LOCAL_DOF(1)-NUMBS(1)+1,J) = 0.0D0; K(2*DOF, J) = 0.D0
! 
! 		K(J,LOCAL_DOF(1)-NUMBS(1)+1) = 0.0D0; K(J,DOF) = 0.D0
! 		K(J,DOF + LOCAL_DOF(1)-NUMBS(1)+1) = 0.0D0; K(J,2*DOF) = 0.D0
! 	ENDDO
! 	K(LOCAL_DOF(1)-NUMBS(1)+1, LOCAL_DOF(1)-NUMBS(1)+1) = 1.0D0; K(DOF,DOF) = 1.D0
! 	K(DOF + LOCAL_DOF(1)-NUMBS(1)+1, DOF + LOCAL_DOF(1)-NUMBS(1)+1) = 1.0D0; K(2*DOF,2*DOF) = 1.D0
! 
! 	PRINT*, 
! 	PRINT*, '<<< IMPOSING NEUMANN BOUNDARY CONDITIONS : DONE >>>'
! 	PRINT*, 

! IMPOSE DIRICHLET BOUNDARY CONDITION BY USING LEAST SQUARE METHOD
!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
	SUB_K(:,:) = 0.D0
	SUB_F(:) = POINT2D(0.D0,0.D0)

! 	OPEN(121, FILE = 'least_square')
	
	CALL GEN_BD_LN(SUB_K, SUB_F)
	
	DMY_SUB_F = SUB_F
	
! 	PRINT*, 'HERE 1'
! 	OPEN(124, FILE = './data/sub_k')
! 	OPEN(125, FILE = './data/sub_f')
! 	DO I=1, SUM(BDNDX(:,1)%LC_NUM)
! 		WRITE(124, 102) (SUB_K(I,J), J=1, SUM(BDNDX(:,1)%LC_NUM))
! 		WRITE(125, 102) SUB_F(I)
! 	ENDDO
! 	CLOSE(124)
! 	CLOSE(125)
	
	102 FORMAT(1000(f20.8,1x))
	
	DMY_SUB_K(:,:) = SUB_K(:,:)
	CALL LUDCMP(DMY_SUB_K, SUM(BDNDX(:,1)%LC_NUM), SUM(BDNDX(:,1)%LC_NUM), INDX, DD)
	CALL LUBKSB(DMY_SUB_K, SUM(BDNDX(:,1)%LC_NUM), SUM(BDNDX(:,1)%LC_NUM), INDX, SUB_F(:)%X)
! 	PRINT*, 'HERE 2'
! 	DMY_SUB_K(:,:) = SUB_K(:,:)
! 	CALL LUDCMP(DMY_SUB_K, SUM(BDNDX(:,1)%LC_NUM), SUM(BDNDX(:,1)%LC_NUM), INDX, DD)
! 	CALL LUBKSB(DMY_SUB_K, SUM(BDNDX(:,1)%LC_NUM), SUM(BDNDX(:,1)%LC_NUM), INDX, SUB_F(:)%Y)
! 	PRINT*, 'HERE 3'
! 	SUBTRACT EXACT SOLUTIONS FROM THE LOAD VECTOR
	DO II=1, NUM_PATCH
		IF (II.EQ.1) THEN
			LC_NUM_SUM = 0
		ELSE
			LC_NUM_SUM = SUM(BDNDX(1:II-1,1)%LC_NUM)
		ENDIF
! 					PRINT*, LC_NUM_SUM
		DO I=1, BDNDX(II,1)%LC_NUM
			DO J=1, DOF
				F(J) = F(J) - SUB_F(LC_NUM_SUM + I)%X*K(J, BDNDX(II,I)%GL_NDX)
			ENDDO
		ENDDO
	ENDDO
! PRINT*, 'HERE 4'
	DO II=1, NUM_PATCH
		IF (II.EQ.1) THEN
			LC_NUM_SUM = 0
		ELSE
			LC_NUM_SUM = SUM(BDNDX(1:II-1,1)%LC_NUM)
		ENDIF
		DO I=1, BDNDX(II,1)%LC_NUM
			F(BDNDX(II,I)%GL_NDX) = SUB_F(LC_NUM_SUM + I)%X
! 			PRINT*, F(BDNDX(II,I)%GL_NDX), F(DOF+BDNDX(II,I)%GL_NDX)
			DO J=1, DOF
				K(BDNDX(II,I)%GL_NDX,J) = 0.0D0
				K(J,BDNDX(II,I)%GL_NDX) = 0.0D0
			ENDDO
			K(BDNDX(II,I)%GL_NDX, BDNDX(II,I)%GL_NDX) = 1.0D0
		ENDDO
	ENDDO
	
	PRINT*, 
	PRINT*, '<<< IMPOSING ESSENTIAL BOUNDARY CONDITIONS BY USING LEAST SQUARE METHOD : DONE >>>'
	PRINT*, 
!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!


END SUBROUTINE IMPOSEBD

END MODULE BOUNDARY
