	MODULE INTEGRATION

	USE GSQUAD
	USE NURBS_BASIS
	USE LOADFUNCTION

	implicit integer (i-n)
	implicit real(8) (a-h,o-z)

CONTAINS


!------------------INTEGRAL CODE FOR THE STIFFNESS MATRIX ELEMENT--------------
SUBROUTINE GEN_KF(STIF_K, LOAD_F)

	REAL*8, INTENT(OUT) :: STIF_K(DOF, DOF), LOAD_F(DOF)
	TYPE(RECPATCH) :: IRBOX
	TYPE(POINT2D) :: GSPT, DMY_GSPT, LOAD_Q_VEC(NUMGSPT**2)
	TYPE(INT2D), ALLOCATABLE :: INDX1(:), INDX2(:)
	TYPE(MATRIX_22) :: JACOB
	TYPE(FVALUE), ALLOCATABLE :: SF1(:,:), SF2(:,:)
	INTEGER :: I,J, K, II, JJ, KK, N, GLOBAL_INDX(2), PATCH
	REAL*8 :: DIFF_XX, DIFF_YY, DIFF_XY, DIFF_YX, DIFF_NN, WEIGHT(NUMGSPT**2)
	
	STIF_K(:,:) = 0.D0; LOAD_F(:) = 0.D0

	!--------------------Compute sub stiffness matrices---------------------------
	DO PATCH = 1, NUM_PATCH
		ALLOCATE(INDX1((BASIS_KVEC(PATCH,1)%POLY_ORDER+1)*(BASIS_KVEC(PATCH,2)%POLY_ORDER+1)))
		ALLOCATE(SF1(NUMGSPT**2, (BASIS_KVEC(PATCH,1)%POLY_ORDER+1)*(BASIS_KVEC(PATCH,2)%POLY_ORDER+1)))
		DO JJ=1, NUMIR(PATCH,2)-1
			DO II=1, NUMIR(PATCH,1)-1
				CALL STIF_LC_INT_II(SF1, WEIGHT, LOAD_Q_VEC(:), INDX1, PATCH, (/II,JJ/))
				DO I = 1, UBOUND(INDX1,1)
					DO J = 1, UBOUND(INDX1,1)
						CALL STIF_FIND_GLOBAL_INDX_FII(GLOBAL_INDX(1:2), PATCH, (/I,J/), INDX1)
						IF (GLOBAL_INDX(1).NE.0 .AND. GLOBAL_INDX(2).NE.0) THEN
							DIFF_XX = DOT_PRODUCT(PRODUCT(RESHAPE((/SF1(:,I)%D10, WEIGHT(:)/), (/NUMGSPT**2, 2/), ORDER=ORDER1), 2), SF1(:,J)%D10)
							DIFF_YY = DOT_PRODUCT(PRODUCT(RESHAPE((/SF1(:,I)%D01, WEIGHT(:)/), (/NUMGSPT**2, 2/), ORDER=ORDER1), 2), SF1(:,J)%D01)
							
							STIF_K(GLOBAL_INDX(1),GLOBAL_INDX(2)) = STIF_K(GLOBAL_INDX(1),GLOBAL_INDX(2)) + DIFF_XX + DIFF_YY
						ENDIF
					ENDDO
					IF (GLOBAL_INDX(1).NE.0) THEN
						DIFF_NN = DOT_PRODUCT(PRODUCT(RESHAPE((/SF1(:,I)%D00, WEIGHT(:)/), (/NUMGSPT**2, 2/), ORDER=ORDER1), 2), LOAD_Q_VEC(:)%X)
						LOAD_F(GLOBAL_INDX(1)) = LOAD_F(GLOBAL_INDX(1)) + DIFF_NN
					ENDIF
				ENDDO
			ENDDO
		ENDDO
		DEALLOCATE(SF1, INDX1)
	ENDDO
	
! 	PRINT*, 'HERE-1'
	
! 	PRINT*, 'HERE1', STIF_K(40,66)

! 	PRINT*, BASIS_KVEC(1,:)%POLY_ORDER
	
	ALLOCATE(INDX1((BASIS_KVEC(1,1)%POLY_ORDER+1)*(BASIS_KVEC(1,2)%POLY_ORDER+1)))
	ALLOCATE(SF1(NUMGSPT**2, (BASIS_KVEC(1,1)%POLY_ORDER+1)*(BASIS_KVEC(1,2)%POLY_ORDER+1)))
	
	ALLOCATE(INDX2((BASIS_KVEC(2,1)%POLY_ORDER+1)*(BASIS_KVEC(2,2)%POLY_ORDER+1)))
	ALLOCATE(SF2(NUMGSPT**2, (BASIS_KVEC(2,1)%POLY_ORDER+1)*(BASIS_KVEC(2,2)%POLY_ORDER+1)))
	
! 	PRINT*, 'HERE-2'
	
	!-----------------Compute elements on interface (i.e. F11, F22, F33)---------------------
	DO JJ=1, NUMIR(2,2)-1
		DO II=1, NUMIR(2,1)-1
			CALL STIF_LC_INT_IJ(SF1, SF2, INDX1, INDX2, WEIGHT, (/1,2/), (/II,JJ/))
			DO I = 1, UBOUND(INDX1,1)
				DO J = 1, UBOUND(INDX2,1)
! 					PRINT*, I, J
					CALL STIF_FIND_GLOBAL_INDX_FIJ(GLOBAL_INDX(1:2), (/1,2/), (/I,J/), INDX1, INDX2)
! 					PRINT*, GLOBAL_INDX 
					IF (GLOBAL_INDX(1).NE.0 .AND. GLOBAL_INDX(2).NE.0) THEN
						DIFF_XX = DOT_PRODUCT(PRODUCT(RESHAPE((/SF1(:,I)%D10, WEIGHT(:)/), (/NUMGSPT**2, 2/), ORDER=ORDER1), 2), SF2(:,J)%D10)
						DIFF_YY = DOT_PRODUCT(PRODUCT(RESHAPE((/SF1(:,I)%D01, WEIGHT(:)/), (/NUMGSPT**2, 2/), ORDER=ORDER1), 2), SF2(:,J)%D01)
						
						STIF_K(GLOBAL_INDX(1),GLOBAL_INDX(2)) = STIF_K(GLOBAL_INDX(1),GLOBAL_INDX(2)) + DIFF_XX + DIFF_YY
						STIF_K(GLOBAL_INDX(2),GLOBAL_INDX(1)) = STIF_K(GLOBAL_INDX(2),GLOBAL_INDX(1)) + DIFF_XX + DIFF_YY
					ENDIF
				ENDDO
			ENDDO
		ENDDO
	ENDDO
	DEALLOCATE(SF1, SF2, INDX1, INDX2)
	
! 	PRINT*, 'HERE-3'

	WRITE(*,*)
	WRITE(*,*) '<<< ASSEMBLE STIFFNESS MATRIX AND LOAD VECTOR : DONE >>>'
	WRITE(*,*)
	
END SUBROUTINE GEN_KF

SUBROUTINE GEN_BD_LN(SUB_K, SUB_F)

	REAL*8, INTENT(OUT) :: SUB_K(SUM(BDNDX(:,1)%LC_NUM), SUM(BDNDX(:,1)%LC_NUM))
	TYPE(POINT2D), INTENT(OUT) :: SUB_F(SUM(BDNDX(:,1)%LC_NUM))
	TYPE(POINT2D) :: EXACT_ON_BD(NUMGSPT)
	TYPE(FVALUE), ALLOCATABLE :: SF1(:,:), SF2(:,:)
	TYPE(INT2D), ALLOCATABLE :: INDX1(:), INDX2(:)
	TYPE(POINT2D) :: BDPT(2)
	REAL*8 :: WEIGHT(NUMGSPT)
	REAL*8 :: DIFF_NN, DET_M, SUB_LN_LENGTH
	INTEGER :: I, J, II, JJ, KK, N, GLOBAL_INDX(2), PATCH, IGA_PATCH, EGM_PATCH, SUB_NUMLN
	TYPE(VEC2D) :: SUB_LN
	TYPE(MATRIX_22) :: JACOB
	
	N = NUMGSPT; SUB_K(:,:)=0.D0; SUB_F(:) = POINT2D(0.D0,0.D0); SUB_NUMLN = 1
	
!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
	DO PATCH = 1, NUM_PATCH
		ALLOCATE(SF1(NUMGSPT, (BASIS_KVEC(PATCH,1)%POLY_ORDER+1)*(BASIS_KVEC(PATCH,2)%POLY_ORDER+1)))
		ALLOCATE(INDX1((BASIS_KVEC(PATCH,1)%POLY_ORDER+1)*(BASIS_KVEC(PATCH,2)%POLY_ORDER+1)))
		DO JJ = 1, NUMIR(PATCH,2)-1
			SUB_LN_LENGTH = DABS(IR_GRID(PATCH,2,JJ+1) - IR_GRID(PATCH,2,JJ))/(1.D0*SUB_NUMLN)
			!----------------------- LEFT SIDE ON THE PARAMETER SPACE ------------------------!
			DO II=1, SUB_NUMLN
				SUB_LN = VEC2D(POINT2D(0.D0,IR_GRID(PATCH,2,JJ)+(II-1)*SUB_LN_LENGTH), POINT2D(0.D0,IR_GRID(PATCH,2,JJ)+II*SUB_LN_LENGTH))
				CALL LEAST_SQUARE_LC_INT_II(SF1, INDX1, WEIGHT, EXACT_ON_BD, PATCH, SUB_LN, 'L')
				DO I=1, UBOUND(INDX1,1)
					DO J=1, UBOUND(INDX1,1)
						DIFF_NN = 0.D0
						CALL DR_GL_INDX_FII(GLOBAL_INDX, PATCH, (/I,J/), INDX1)
						IF (GLOBAL_INDX(1).EQ.0 .OR. GLOBAL_INDX(2).EQ.0) THEN
						ELSE
							DIFF_NN = DOT_PRODUCT(PRODUCT(RESHAPE((/SF1(:,I)%D00, WEIGHT(:)/), (/NUMGSPT, 2/), ORDER=ORDER1), 2), SF1(:,J)%D00)
							SUB_K(GLOBAL_INDX(1), GLOBAL_INDX(2)) = SUB_K(GLOBAL_INDX(1), GLOBAL_INDX(2)) + DIFF_NN
						ENDIF
					ENDDO
					IF (GLOBAL_INDX(1).EQ.0) THEN
					ELSE
						DIFF_NN = DOT_PRODUCT(PRODUCT(RESHAPE((/SF1(:,I)%D00, WEIGHT(:)/), (/NUMGSPT, 2/), ORDER=ORDER1), 2), EXACT_ON_BD(:)%X)
						SUB_F(GLOBAL_INDX(1))%X = SUB_F(GLOBAL_INDX(1))%X + DIFF_NN
					ENDIF
				ENDDO
			ENDDO
			
! 			PRINT*, 'LEFT', PATCH, JJ, SUB_F(11)
			
			!----------------------- RIGHT SIDE ON THE PARAMETER SPACE ------------------------!
			DO II=1, SUB_NUMLN
				SUB_LN = VEC2D(POINT2D(1.D0,IR_GRID(PATCH,2,JJ)+(II-1)*SUB_LN_LENGTH), POINT2D(1.D0,IR_GRID(PATCH,2,JJ)+II*SUB_LN_LENGTH))
				DIFF_NN = 0.D0
				CALL LEAST_SQUARE_LC_INT_II(SF1, INDX1, WEIGHT, EXACT_ON_BD, PATCH, SUB_LN, 'R')
				DO I=1, UBOUND(INDX1,1)
					DO J=1, UBOUND(INDX1,1)
						CALL DR_GL_INDX_FII(GLOBAL_INDX, PATCH, (/I,J/), INDX1)
						IF (GLOBAL_INDX(1).EQ.0 .OR. GLOBAL_INDX(2).EQ.0) THEN
						ELSE
! 							PRINT*, 'HERE 1', GLOBAL_INDX
							DIFF_NN = DOT_PRODUCT(PRODUCT(RESHAPE((/SF1(:,I)%D00, WEIGHT(:)/), (/NUMGSPT, 2/), ORDER=ORDER1), 2), SF1(:,J)%D00)
							SUB_K(GLOBAL_INDX(1), GLOBAL_INDX(2)) = SUB_K(GLOBAL_INDX(1), GLOBAL_INDX(2)) + DIFF_NN
! 							IF (GLOBAL_INDX(1).EQ.12 .AND. GLOBAL_INDX(2).EQ.8) THEN
! 								PRINT*, DIFF_NN, SUB_K(GLOBAL_INDX(1), GLOBAL_INDX(2))
! 							ENDIF
						ENDIF
					ENDDO
					IF (GLOBAL_INDX(1).EQ.0) THEN
					ELSE
						DIFF_NN = DOT_PRODUCT(PRODUCT(RESHAPE((/SF1(:,I)%D00, WEIGHT(:)/), (/NUMGSPT, 2/), ORDER=ORDER1), 2), EXACT_ON_BD(:)%X)
						SUB_F(GLOBAL_INDX(1))%X = SUB_F(GLOBAL_INDX(1))%X + DIFF_NN
					ENDIF
				ENDDO
			ENDDO
! 			PRINT*, 'RIGHT', PATCH, JJ, SUB_F(11)
		ENDDO
		
		IF (PATCH==1) THEN
		!----------------------- BOTTOM SIDE ON THE PARAMETER SPACE ------------------------!
			DO JJ = 1, NUMIR(PATCH,1)-1
				SUB_LN_LENGTH = DABS(IR_GRID(PATCH,1,JJ+1) - IR_GRID(PATCH,1,JJ))/(1.D0*SUB_NUMLN)
				DO II=1, SUB_NUMLN
					SUB_LN = VEC2D(POINT2D(IR_GRID(PATCH,1,JJ)+(II-1)*SUB_LN_LENGTH,0.D0), POINT2D(IR_GRID(PATCH,1,JJ)+II*SUB_LN_LENGTH,0.D0))
					DIFF_NN = 0.D0
					CALL LEAST_SQUARE_LC_INT_II(SF1, INDX1, WEIGHT, EXACT_ON_BD, PATCH, SUB_LN, 'B')
					DO I=1, UBOUND(INDX1,1)
						DO J=1, UBOUND(INDX1,1)
							CALL DR_GL_INDX_FII(GLOBAL_INDX, PATCH, (/I,J/), INDX1)
							IF (GLOBAL_INDX(1).EQ.0 .OR. GLOBAL_INDX(2).EQ.0) THEN
							ELSE
								DIFF_NN = DOT_PRODUCT(PRODUCT(RESHAPE((/SF1(:,I)%D00, WEIGHT(:)/), (/NUMGSPT, 2/), ORDER=ORDER1), 2), SF1(:,J)%D00)
								SUB_K(GLOBAL_INDX(1), GLOBAL_INDX(2)) = SUB_K(GLOBAL_INDX(1), GLOBAL_INDX(2)) + DIFF_NN
		! 							IF (GLOBAL_INDX(1).EQ.14 .AND. GLOBAL_INDX(2).EQ.14) THEN
		! 								PRINT*, INDX1(I), INDX1(J)
		! 								PRINT*, SF1(1:3,I)%D00
		! 								PRINT*, ''
		! 								PRINT*, SF1(1:3,J)%D00
		! 								PRINT*, ''
		! 								PRINT*, WEIGHT(1:3)
		! 								PRINT*, DIFF_NN
		! 							ENDIF
! 								IF (PATCH==2 .AND. GLOBAL_INDX(1)==GLOBAL_INDX(2)) THEN
! 									SUB_K(GLOBAL_INDX(1), GLOBAL_INDX(2)) = 1.D0
! 								ENDIF
							ENDIF
						ENDDO
						IF (GLOBAL_INDX(1).EQ.0) THEN
						ELSE
							DIFF_NN = DOT_PRODUCT(PRODUCT(RESHAPE((/SF1(:,I)%D00, WEIGHT(:)/), (/NUMGSPT, 2/), ORDER=ORDER1), 2), EXACT_ON_BD(:)%X)
							SUB_F(GLOBAL_INDX(1))%X = SUB_F(GLOBAL_INDX(1))%X + DIFF_NN
						ENDIF
					ENDDO
				ENDDO
			
				!----------------------- TOP SIDE ON THE PARAMETER SPACE ------------------------!
				DO II=1, SUB_NUMLN
					SUB_LN = VEC2D(POINT2D(IR_GRID(PATCH,1,JJ)+(II-1)*SUB_LN_LENGTH,1.D0), POINT2D(IR_GRID(PATCH,1,JJ)+II*SUB_LN_LENGTH,1.D0))
					DIFF_NN = 0.D0
					CALL LEAST_SQUARE_LC_INT_II(SF1, INDX1, WEIGHT, EXACT_ON_BD, PATCH, SUB_LN, 'T')
					DO I=1, UBOUND(INDX1,1)
						DO J=1, UBOUND(INDX1,1)
							CALL DR_GL_INDX_FII(GLOBAL_INDX, PATCH, (/I,J/), INDX1)
							IF (GLOBAL_INDX(1).EQ.0 .OR. GLOBAL_INDX(2).EQ.0) THEN
							ELSE
	! 							PRINT*, 'HERE8', GLOBAL_INDX
								DIFF_NN = DOT_PRODUCT(PRODUCT(RESHAPE((/SF1(:,I)%D00, WEIGHT(:)/), (/NUMGSPT, 2/), ORDER=ORDER1), 2), SF1(:,J)%D00)
								SUB_K(GLOBAL_INDX(1), GLOBAL_INDX(2)) = SUB_K(GLOBAL_INDX(1), GLOBAL_INDX(2)) + DIFF_NN
	! 							IF (GLOBAL_INDX(1).EQ.25 .AND. GLOBAL_INDX(2).EQ.25) THEN
	! 								PRINT*, GLOBAL_INDX, SUB_K(GLOBAL_INDX(1), GLOBAL_INDX(2))
	! 							ENDIF
							ENDIF
						ENDDO
						IF (GLOBAL_INDX(1).EQ.0) THEN
						ELSE
							DIFF_NN = DOT_PRODUCT(PRODUCT(RESHAPE((/SF1(:,I)%D00, WEIGHT(:)/), (/NUMGSPT, 2/), ORDER=ORDER1), 2), EXACT_ON_BD(:)%X)
							SUB_F(GLOBAL_INDX(1))%X = SUB_F(GLOBAL_INDX(1))%X + DIFF_NN
						ENDIF
					ENDDO
				ENDDO
	! 			PRINT*, 'TOP', PATCH, JJ, SUB_F(11)
			ENDDO
		ENDIF
		DEALLOCATE(SF1, INDX1)
	ENDDO

	!----------------------- INTERSECTION LINE BETWEEN IGA AND EGM ------------------------!
	IGA_PATCH = 1
	EGM_PATCH = 2
	
	ALLOCATE(SF1(NUMGSPT, (BASIS_KVEC(IGA_PATCH,1)%POLY_ORDER+1)*(BASIS_KVEC(IGA_PATCH,2)%POLY_ORDER+1)))
	ALLOCATE(INDX1((BASIS_KVEC(IGA_PATCH,1)%POLY_ORDER+1)*(BASIS_KVEC(IGA_PATCH,2)%POLY_ORDER+1)))
	
	ALLOCATE(SF2(NUMGSPT, (BASIS_KVEC(EGM_PATCH,1)%POLY_ORDER+1)*(BASIS_KVEC(EGM_PATCH,2)%POLY_ORDER+1)))
	ALLOCATE(INDX2((BASIS_KVEC(EGM_PATCH,1)%POLY_ORDER+1)*(BASIS_KVEC(EGM_PATCH,2)%POLY_ORDER+1)))
	
	DO JJ = 1, NUMIR(EGM_PATCH,2)-1
		SUB_LN_LENGTH = DABS(IR_GRID(EGM_PATCH,2,JJ+1) - IR_GRID(EGM_PATCH,2,JJ))/(1.D0*SUB_NUMLN)
		!----------------------- LEFT SIDE ON THE PARAMETER SPACE ------------------------!
		DO II=1, SUB_NUMLN
			SUB_LN = VEC2D(POINT2D(0.D0,IR_GRID(EGM_PATCH,2,JJ)+(II-1)*SUB_LN_LENGTH), POINT2D(0.D0,IR_GRID(EGM_PATCH,2,JJ)+II*SUB_LN_LENGTH))
			DIFF_NN = 0.D0
			CALL LEAST_SQUARE_LC_INT_IJ(SF1, SF2, INDX1, INDX2, WEIGHT, (/IGA_PATCH,EGM_PATCH/), SUB_LN, 'L')
			DO I=1, UBOUND(INDX1,1)
				DO J=1, UBOUND(INDX2,1)
					CALL DR_GL_INDX_FIJ(GLOBAL_INDX, (/IGA_PATCH,EGM_PATCH/), (/I,J/), INDX1, INDX2)
					IF (GLOBAL_INDX(1).EQ.0 .OR. GLOBAL_INDX(2).EQ.0) THEN
					ELSE
						DIFF_NN = DOT_PRODUCT(PRODUCT(RESHAPE((/SF1(:,I)%D00, WEIGHT(:)/), (/NUMGSPT, 2/), ORDER=ORDER1), 2), SF2(:,J)%D00)
						SUB_K(GLOBAL_INDX(1), GLOBAL_INDX(2)) = SUB_K(GLOBAL_INDX(1), GLOBAL_INDX(2)) + DIFF_NN
						SUB_K(GLOBAL_INDX(2), GLOBAL_INDX(1)) = SUB_K(GLOBAL_INDX(2), GLOBAL_INDX(1)) + DIFF_NN
					ENDIF
				ENDDO
			ENDDO
		ENDDO
		!----------------------- RIGHT SIDE ON THE PARAMETER SPACE ------------------------!
		DO II=1, SUB_NUMLN
			SUB_LN = VEC2D(POINT2D(1.D0,IR_GRID(EGM_PATCH,2,JJ)+(II-1)*SUB_LN_LENGTH), POINT2D(1.D0,IR_GRID(EGM_PATCH,2,JJ)+II*SUB_LN_LENGTH))
			DIFF_NN = 0.D0
			CALL LEAST_SQUARE_LC_INT_IJ(SF1, SF2, INDX1, INDX2, WEIGHT, (/IGA_PATCH,EGM_PATCH/), SUB_LN, 'R')
			DO I=1, UBOUND(INDX1,1)
				DO J=1, UBOUND(INDX2,1)
					CALL DR_GL_INDX_FIJ(GLOBAL_INDX, (/IGA_PATCH,EGM_PATCH/), (/I,J/), INDX1, INDX2)
					IF (GLOBAL_INDX(1).EQ.0 .OR. GLOBAL_INDX(2).EQ.0) THEN
					ELSE
						DIFF_NN = DOT_PRODUCT(PRODUCT(RESHAPE((/SF1(:,I)%D00, WEIGHT(:)/), (/NUMGSPT, 2/), ORDER=ORDER1), 2), SF2(:,J)%D00)
						SUB_K(GLOBAL_INDX(1), GLOBAL_INDX(2)) = SUB_K(GLOBAL_INDX(1), GLOBAL_INDX(2)) + DIFF_NN
						SUB_K(GLOBAL_INDX(2), GLOBAL_INDX(1)) = SUB_K(GLOBAL_INDX(2), GLOBAL_INDX(1)) + DIFF_NN
					ENDIF
				ENDDO
			ENDDO
		ENDDO
	ENDDO
	
	DEALLOCATE(SF1, SF2, INDX1, INDX2)
	
END SUBROUTINE GEN_BD_LN

!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!

SUBROUTINE STIF_LC_INT_II(SF, WEIGHT, LOAD_Q_VEC, INDX, PATCH, NUMIR_INDX)
	INTEGER, INTENT(IN) :: NUMIR_INDX(2), PATCH
	TYPE(FVALUE), INTENT(OUT) :: SF(NUMGSPT**2, (BASIS_KVEC(PATCH,1)%POLY_ORDER+1)*(BASIS_KVEC(PATCH,2)%POLY_ORDER+1))
	TYPE(INT2D), INTENT(OUT) :: INDX((BASIS_KVEC(PATCH,1)%POLY_ORDER+1)*(BASIS_KVEC(PATCH,2)%POLY_ORDER+1))
	REAL*8, INTENT(OUT) :: WEIGHT(NUMGSPT**2)
	TYPE(POINT2D), INTENT(OUT) :: LOAD_Q_VEC(NUMGSPT**2)
	
	TYPE(RECPATCH) :: IRBOX
	TYPE(POINT2D) :: GSPT, DMY_GSPT
	TYPE(MATRIX_22) :: JACOB
	INTEGER :: I,J, K, II, JJ, KK
	REAL*8 :: DET_M

	IRBOX%PT1 = POINT2D(IR_GRID(PATCH,1,NUMIR_INDX(1)), IR_GRID(PATCH,2,NUMIR_INDX(2)))
	IRBOX%PT2 = POINT2D(IR_GRID(PATCH,1,NUMIR_INDX(1)+1), IR_GRID(PATCH,2,NUMIR_INDX(2)))
	IRBOX%PT3 = POINT2D(IR_GRID(PATCH,1,NUMIR_INDX(1)+1), IR_GRID(PATCH,2,NUMIR_INDX(2)+1))
	IRBOX%PT4 = POINT2D(IR_GRID(PATCH,1,NUMIR_INDX(1)), IR_GRID(PATCH,2,NUMIR_INDX(2)+1))

	!------------------! VECTORIZE GAUSS POINTS AND WEIGHTS------------------------------
	CALL GAULEG(IRBOX%PT1%X, IRBOX%PT2%X, GSX, GSXW, NUMGSPT)
	CALL GAULEG(IRBOX%PT1%Y, IRBOX%PT4%Y, GSY, GSYW, NUMGSPT)
	
	KK=0
	DO I=1,NUMGSPT
		DO J=1,NUMGSPT
! 			PRINT*, I, J
			KK=KK+1
			GSPT = POINT2D(GSX(I), GSY(J))
			DMY_GSPT = GSPT
			JACOB = GET_JACOBIAN_MATRIX(GSPT,PATCH)
			DET_M = .DETERMINANT.JACOB
! 			PRINT*, DET_M
			WEIGHT(KK) = DET_M*GSXW(I)*GSYW(J)
! 			PRINT*, WEIGHT(KK)
			LOAD_Q_VEC(KK) = LDFT2D(GSPT,PATCH)
			IF (PATCH==1) THEN
				CALL GET_ALL_PHY_NURBS_SURFACE_2D(SF(KK,:), INDX(:), DMY_GSPT, JACOB, PATCH)
			ELSE
				CALL GET_ALL_PHY_BASIS_IN_INT(SF(KK,:), INDX(:), DMY_GSPT, JACOB, PATCH)
			ENDIF
		ENDDO
	ENDDO
	
! 	PRINT*, 'STIF_LC_INT_II - DONE'
	
END SUBROUTINE STIF_LC_INT_II

SUBROUTINE STIF_LC_INT_IJ(SF1, SF2, INDX1, INDX2, WEIGHT, PATCHES, NUMIR_INDX)

	INTEGER, INTENT(IN) :: NUMIR_INDX(2), PATCHES(2)
	TYPE(FVALUE), INTENT(OUT) :: SF1(NUMGSPT**2, (BASIS_KVEC(PATCHES(1),1)%POLY_ORDER+1)*(BASIS_KVEC(PATCHES(1),2)%POLY_ORDER+1))
	TYPE(FVALUE), INTENT(OUT) :: SF2(NUMGSPT**2, (BASIS_KVEC(PATCHES(2),1)%POLY_ORDER+1)*(BASIS_KVEC(PATCHES(2),2)%POLY_ORDER+1))
	TYPE(INT2D), INTENT(OUT) :: INDX1((BASIS_KVEC(PATCHES(1),1)%POLY_ORDER+1)*(BASIS_KVEC(PATCHES(1),2)%POLY_ORDER+1))
	TYPE(INT2D), INTENT(OUT) :: INDX2((BASIS_KVEC(PATCHES(2),1)%POLY_ORDER+1)*(BASIS_KVEC(PATCHES(2),2)%POLY_ORDER+1))
	REAL*8, INTENT(OUT) :: WEIGHT(NUMGSPT**2)
	
	TYPE(RECPATCH) :: IRBOX
	TYPE(POINT2D) :: GSPT, DMY_GSPT, PHYPT_F, INV_PHYPT_G
	TYPE(MATRIX_22) :: JACOB_F, JACOB_FG, INV_JACOB_F, JACOB_G, INV_JACOB_F_SQUARE
	INTEGER :: I,J, K, II, JJ, KK
	REAL*8 :: DET_JF
	
	IRBOX%PT1 = POINT2D(IR_GRID(PATCHES(2),1,NUMIR_INDX(1)), IR_GRID(PATCHES(2),2,NUMIR_INDX(2)))
	IRBOX%PT2 = POINT2D(IR_GRID(PATCHES(2),1,NUMIR_INDX(1)+1), IR_GRID(PATCHES(2),2,NUMIR_INDX(2)))
	IRBOX%PT3 = POINT2D(IR_GRID(PATCHES(2),1,NUMIR_INDX(1)+1), IR_GRID(PATCHES(2),2,NUMIR_INDX(2)+1))
	IRBOX%PT4 = POINT2D(IR_GRID(PATCHES(2),1,NUMIR_INDX(1)), IR_GRID(PATCHES(2),2,NUMIR_INDX(2)+1))
	
	!------------------! VECTORIZE GAUSS POINTS AND WEIGHTS------------------------------
	CALL GAULEG(IRBOX%PT1%X, IRBOX%PT2%X, GSX, GSXW, NUMGSPT)
	CALL GAULEG(IRBOX%PT1%Y, IRBOX%PT4%Y, GSY, GSYW, NUMGSPT)
	
	KK=0
	DO I=1,NUMGSPT
		DO J=1,NUMGSPT
			KK=KK+1
! 			PRINT*, I, J
			GSPT = POINT2D(GSX(I), GSY(J))
			DMY_GSPT = GSPT
			PHYPT_F = GET_PHY_PT(DMY_GSPT,2)
! 			PRINT*, PHYPT_F
			INV_PHYPT_G = GET_REF_PT(PHYPT_F,1)
			
! 			PRINT*, INV_PHYPT_G
			
			JACOB_F = GET_JACOBIAN_MATRIX(DMY_GSPT,PATCHES(2))
			JACOB_G = GET_JACOBIAN_MATRIX(INV_PHYPT_G,PATCHES(1))
			
! 			INV_JACOB_F = .INVERSE.JACOB_F
			
! 			INV_JACOB_F_SQUARE%ENT(1,1) = DOT_PRODUCT(INV_JACOB_F%ENT(1,:), INV_JACOB_F%ENT(:,1))
! 			INV_JACOB_F_SQUARE%ENT(1,2) = DOT_PRODUCT(INV_JACOB_F%ENT(1,:), INV_JACOB_F%ENT(:,2))
! 			INV_JACOB_F_SQUARE%ENT(2,1) = DOT_PRODUCT(INV_JACOB_F%ENT(2,:), INV_JACOB_F%ENT(:,1))
! 			INV_JACOB_F_SQUARE%ENT(2,2) = DOT_PRODUCT(INV_JACOB_F%ENT(2,:), INV_JACOB_F%ENT(:,2))
! 			
! 			JACOB_FG%ENT(1,1) = DOT_PRODUCT(INV_JACOB_F%ENT(1,:), JACOB_G%ENT(:,1))
! 			JACOB_FG%ENT(1,2) = DOT_PRODUCT(INV_JACOB_F%ENT(1,:), JACOB_G%ENT(:,2))
! 			JACOB_FG%ENT(2,1) = DOT_PRODUCT(INV_JACOB_F%ENT(2,:), JACOB_G%ENT(:,1))
! 			JACOB_FG%ENT(2,2) = DOT_PRODUCT(INV_JACOB_F%ENT(2,:), JACOB_G%ENT(:,2))
			
			DET_JF = .DETERMINANT.JACOB_F
			WEIGHT(KK) = DET_JF*GSXW(I)*GSYW(J)
! 			PRINT*, 'STIF_LC_INT_IN - HERE0'
			CALL GET_ALL_PHY_NURBS_SURFACE_2D(SF1(KK,:), INDX1(:), INV_PHYPT_G, JACOB_G, PATCHES(1))
! 			PRINT*, 'STIF_LC_INT_IN - HERE1'
			CALL GET_ALL_PHY_BASIS_IN_INT(SF2(KK,:), INDX2(:), DMY_GSPT, JACOB_F, PATCHES(2))
! 			PRINT*, 'STIF_LC_INT_IN - HERE2'
		ENDDO
	ENDDO

! 	PRINT*, 'STIF_LC_INT_IJ - DONE'
	
END SUBROUTINE STIF_LC_INT_IJ

SUBROUTINE STIF_FIND_GLOBAL_INDX_FII(GLOBAL_INDX, PATCH, LOCAL_INDX, INDX)
	INTEGER, INTENT(IN) :: PATCH, LOCAL_INDX(2)
	TYPE(INT2D), INTENT(IN) :: INDX((BASIS_KVEC(PATCH,1)%POLY_ORDER+1)*(BASIS_KVEC(PATCH,2)%POLY_ORDER+1))
	INTEGER, INTENT(OUT) :: GLOBAL_INDX(2)
	
	INTEGER :: I, J, K, II, JJ, KK, LOCAL_DOF_SUM
	
	IF (PATCH.EQ.1) THEN
		LOCAL_DOF_SUM = 0
	ELSE
		LOCAL_DOF_SUM = SUM(LOCAL_DOF(1:PATCH-1))
	ENDIF

	DO KK=1, LOCAL_DOF(PATCH)
		IF (NDX(1,LOCAL_DOF_SUM + KK).EQ.INDX(LOCAL_INDX(1))%A .AND. NDX(2,LOCAL_DOF_SUM + KK).EQ.INDX(LOCAL_INDX(1))%B) THEN
			GLOBAL_INDX(1) = LOCAL_DOF_SUM + KK
			GOTO 111
		ELSE
			GLOBAL_INDX(1) = 0
		ENDIF
	ENDDO
	111 CONTINUE
	
	DO KK=1, LOCAL_DOF(PATCH)
		IF (NDX(1,LOCAL_DOF_SUM + KK).EQ.INDX(LOCAL_INDX(2))%A .AND. NDX(2,LOCAL_DOF_SUM + KK).EQ.INDX(LOCAL_INDX(2))%B) THEN
			GLOBAL_INDX(2) = LOCAL_DOF_SUM + KK
			GOTO 222
		ELSE
		GLOBAL_INDX(2) = 0
		ENDIF
	ENDDO
	222 CONTINUE

END SUBROUTINE STIF_FIND_GLOBAL_INDX_FII

SUBROUTINE STIF_FIND_GLOBAL_INDX_FIJ(GLOBAL_INDX, PATCHES, LOCAL_INDX, INDX1, INDX2)
	INTEGER, INTENT(IN) :: PATCHES(2), LOCAL_INDX(2)
	TYPE(INT2D), INTENT(IN) :: INDX1((BASIS_KVEC(PATCHES(1),1)%POLY_ORDER+1)*(BASIS_KVEC(PATCHES(1),2)%POLY_ORDER+1))
	TYPE(INT2D), INTENT(IN) :: INDX2((BASIS_KVEC(PATCHES(2),1)%POLY_ORDER+1)*(BASIS_KVEC(PATCHES(2),2)%POLY_ORDER+1))
	INTEGER, INTENT(OUT) :: GLOBAL_INDX(2)
	
	INTEGER :: I, J, K, II, JJ, KK, LOCAL_DOF_SUM(2)
	
	DO I = 1, 2
		IF (PATCHES(I).EQ.1) THEN
			LOCAL_DOF_SUM(I) = 0
		ELSE
			LOCAL_DOF_SUM(I) = SUM(LOCAL_DOF(1:I-1))
		ENDIF
	ENDDO
	
	DO KK=1, LOCAL_DOF(PATCHES(1))
		IF (NDX(1,LOCAL_DOF_SUM(1) + KK).EQ.INDX1(LOCAL_INDX(1))%A .AND. NDX(2,LOCAL_DOF_SUM(1) + KK).EQ.INDX1(LOCAL_INDX(1))%B) THEN
			GLOBAL_INDX(1) = LOCAL_DOF_SUM(1) + KK
			GOTO 111
		ELSE
			GLOBAL_INDX(1) = 0
		ENDIF
	ENDDO
	111 CONTINUE
	
	DO KK=1, LOCAL_DOF(PATCHES(2))
		IF (NDX(1,LOCAL_DOF_SUM(2) + KK).EQ.INDX2(LOCAL_INDX(2))%A .AND. NDX(2,LOCAL_DOF_SUM(2) + KK).EQ.INDX2(LOCAL_INDX(2))%B) THEN
			GLOBAL_INDX(2) = LOCAL_DOF_SUM(2) + KK
			GOTO 222
		ELSE
		GLOBAL_INDX(2) = 0
		ENDIF
	ENDDO
	222 CONTINUE

END SUBROUTINE STIF_FIND_GLOBAL_INDX_FIJ

SUBROUTINE LEAST_SQUARE_LC_INT_II(SF, INDX, WEIGHT, EXACT_ON_BD, PATCH, SUB_LN, GAMMA_HAT)
	INTEGER, INTENT(IN) :: PATCH
	TYPE(VEC2D), INTENT(IN) :: SUB_LN
	CHARACTER(LEN=1), INTENT(IN) :: GAMMA_HAT
	
	TYPE(FVALUE), INTENT(OUT) :: SF(NUMGSPT, (BASIS_KVEC(PATCH,1)%POLY_ORDER+1)*(BASIS_KVEC(PATCH,2)%POLY_ORDER+1))
	TYPE(INT2D), INTENT(OUT) :: INDX((BASIS_KVEC(PATCH,1)%POLY_ORDER+1)*(BASIS_KVEC(PATCH,2)%POLY_ORDER+1))
	REAL*8, INTENT(OUT) :: WEIGHT(NUMGSPT)
	TYPE(POINT2D), INTENT(OUT) :: EXACT_ON_BD(NUMGSPT)
	
	TYPE(POINT2D) :: GSPT, DMY_GSPT
	REAL*8 :: DET_M
	INTEGER :: I, J, II, JJ, KK
	TYPE(MATRIX_22) :: JACOB
	
	IF (GAMMA_HAT=='B' .OR. GAMMA_HAT=='T') THEN
		CALL GAULEG(SUB_LN%U%X, SUB_LN%V%X, GSX, GSXW, NUMGSPT)
	ELSE
		CALL GAULEG(SUB_LN%U%Y, SUB_LN%V%Y, GSY, GSYW, NUMGSPT)
	ENDIF
	
	DO I=1,NUMGSPT
		IF (GAMMA_HAT=='B') THEN
			GSPT = POINT2D(GSX(I), 0.D0)
		ELSEIF (GAMMA_HAT=='T') THEN
			GSPT = POINT2D(GSX(I), 1.D0)
		ELSEIF (GAMMA_HAT=='L') THEN
			GSPT = POINT2D(0.D0, GSY(I))
		ELSEIF (GAMMA_HAT=='R') THEN
			GSPT = POINT2D(1.D0, GSY(I))
		ENDIF
		DMY_GSPT = GSPT
		JACOB = GET_JACOBIAN_MATRIX(DMY_GSPT,PATCH)
		DET_M = .DETERMINANT.JACOB
		IF (GAMMA_HAT=='B' .OR. GAMMA_HAT=='T') THEN
			WEIGHT(I) = DET_M*GSXW(I)
! 			IF (GAMMA_HAT=='B') THEN
! 				PRINT*, JACOB%ENT(1,1), JACOB%ENT(1,2), JACOB%ENT(2,1), JACOB%ENT(2,2)
! 				PRINT*, PATCH, 'DET_M : ',DET_M, 'GSXW : ', GSXW(I)
! 			ENDIF
		ELSEIF (GAMMA_HAT=='L' .OR. GAMMA_HAT=='R') THEN
			WEIGHT(I) = DET_M*GSYW(I)
		ENDIF
		IF (PATCH==1) THEN
			CALL GET_ALL_PHY_NURBS_SURFACE_2D(SF(I,:), INDX(:), DMY_GSPT, JACOB, PATCH)
		ELSE
			CALL GET_ALL_PHY_BASIS_IN_INT(SF(I,:), INDX(:), DMY_GSPT, JACOB, PATCH)
		ENDIF
		EXACT_ON_BD(I) = EX_DISP(DMY_GSPT,PATCH)
! 					PRINT*, I, EXACT_ON_BD(I)
	ENDDO

END SUBROUTINE LEAST_SQUARE_LC_INT_II

SUBROUTINE LEAST_SQUARE_LC_INT_IJ(SF1, SF2, INDX1, INDX2, WEIGHT, PATCHES, SUB_LN, GAMMA_HAT)
	
	INTEGER, INTENT(IN) :: PATCHES(2)
	TYPE(VEC2D), INTENT(IN) :: SUB_LN
	CHARACTER(LEN=1), INTENT(IN) :: GAMMA_HAT
	
	TYPE(FVALUE), INTENT(OUT) :: SF1(NUMGSPT, (BASIS_KVEC(PATCHES(1),1)%POLY_ORDER+1)*(BASIS_KVEC(PATCHES(1),2)%POLY_ORDER+1))
	TYPE(FVALUE), INTENT(OUT) :: SF2(NUMGSPT, (BASIS_KVEC(PATCHES(2),1)%POLY_ORDER+1)*(BASIS_KVEC(PATCHES(2),2)%POLY_ORDER+1))
	TYPE(INT2D), INTENT(OUT) :: INDX1((BASIS_KVEC(PATCHES(1),1)%POLY_ORDER+1)*(BASIS_KVEC(PATCHES(1),2)%POLY_ORDER+1))
	TYPE(INT2D), INTENT(OUT) :: INDX2((BASIS_KVEC(PATCHES(2),1)%POLY_ORDER+1)*(BASIS_KVEC(PATCHES(2),2)%POLY_ORDER+1))
	REAL*8, INTENT(OUT) :: WEIGHT(NUMGSPT)
	
	TYPE(POINT2D) :: GSPT, DMY_GSPT, PHYPT_F, INV_PHYPT_G
	REAL*8 :: DET_M
	INTEGER :: I, J, II, JJ, KK
	TYPE(MATRIX_22) :: JACOB
	
	IF (GAMMA_HAT=='B' .OR. GAMMA_HAT=='T') THEN
		CALL GAULEG(SUB_LN%U%X, SUB_LN%V%X, GSX, GSXW, NUMGSPT)
	ELSE
		CALL GAULEG(SUB_LN%U%Y, SUB_LN%V%Y, GSY, GSYW, NUMGSPT)
	ENDIF
	
	DO I=1,NUMGSPT
		IF (GAMMA_HAT=='B') THEN
			GSPT = POINT2D(GSX(I), 0.D0)
		ELSEIF (GAMMA_HAT=='T') THEN
			GSPT = POINT2D(GSX(I), 1.D0)
		ELSEIF (GAMMA_HAT=='L') THEN
			GSPT = POINT2D(0.D0, GSY(I))
		ELSEIF (GAMMA_HAT=='R') THEN
			GSPT = POINT2D(1.D0, GSY(I))
		ENDIF
		
		DMY_GSPT = GSPT
		PHYPT_F = GET_PHY_PT(DMY_GSPT, 2)
		INV_PHYPT_G = GET_REF_PT(PHYPT_F, 1,GAMMA_HAT)
		
		JACOB = GET_JACOBIAN_MATRIX(DMY_GSPT,PATCHES(2))
		DET_M = .DETERMINANT.JACOB
		
		IF (GAMMA_HAT=='B' .OR. GAMMA_HAT=='T') THEN
			WEIGHT(I) = DET_M*GSXW(I)
		ELSEIF (GAMMA_HAT=='L' .OR. GAMMA_HAT=='R') THEN
			WEIGHT(I) = DET_M*GSYW(I)
		ENDIF
		
		CALL GET_ALL_PHY_NURBS_SURFACE_2D(SF1(I,:), INDX1(:), INV_PHYPT_G, JACOB, PATCHES(1))
		CALL GET_ALL_PHY_BASIS_IN_INT(SF2(I,:), INDX2(:), DMY_GSPT, JACOB, PATCHES(2))
	ENDDO

END SUBROUTINE LEAST_SQUARE_LC_INT_IJ

SUBROUTINE DR_GL_INDX_FII(GLOBAL_INDX, PATCH, LOCAL_INDX, INDX)
	INTEGER, INTENT(IN) :: PATCH, LOCAL_INDX(2)
	TYPE(INT2D), INTENT(IN) :: INDX((BASIS_KVEC(PATCH,1)%POLY_ORDER+1)*(BASIS_KVEC(PATCH,2)%POLY_ORDER+1))
	INTEGER, INTENT(OUT) :: GLOBAL_INDX(2)
	
	INTEGER :: I, J, K, II, JJ, KK, LC_NUM_SUM
	
	IF (PATCH.EQ.1) THEN
		LC_NUM_SUM = 0
	ELSE
		LC_NUM_SUM = SUM(BDNDX(1:PATCH-1,1)%LC_NUM)
	ENDIF

	DO KK=1, BDNDX(PATCH,1)%LC_NUM
! 				PRINT*, 'KK',KK
		IF (BDNDX(PATCH,KK)%LC_NDX(1).EQ.INDX(LOCAL_INDX(1))%A .AND. BDNDX(PATCH,KK)%LC_NDX(2).EQ.INDX(LOCAL_INDX(1))%B) THEN
			GLOBAL_INDX(1) = LC_NUM_SUM + KK
! 							PRINT*, PATCH, 'G1', GLOBAL_INDX(1)
			GOTO 111
		ELSE
			GLOBAL_INDX(1) = 0
		ENDIF
	ENDDO
	111 CONTINUE

	DO KK=1, BDNDX(PATCH,1)%LC_NUM
! 					PRINT*, 'KK',KK
		IF (BDNDX(PATCH,KK)%LC_NDX(1).EQ.INDX(LOCAL_INDX(2))%A .AND. BDNDX(PATCH,KK)%LC_NDX(2).EQ.INDX(LOCAL_INDX(2))%B) THEN
			GLOBAL_INDX(2) = LC_NUM_SUM + KK
! 								PRINT*, PATCH, 'G2', GLOBAL_INDX(2)
			GOTO 222
		ELSE
			GLOBAL_INDX(2) = 0
		ENDIF
	ENDDO
	222 CONTINUE

END SUBROUTINE DR_GL_INDX_FII

SUBROUTINE DR_GL_INDX_FIJ(GLOBAL_INDX, PATCHES, LOCAL_INDX, INDX1, INDX2)
	INTEGER, INTENT(IN) :: PATCHES(2), LOCAL_INDX(2)
	TYPE(INT2D), INTENT(IN) :: INDX1((BASIS_KVEC(PATCHES(1),1)%POLY_ORDER+1)*(BASIS_KVEC(PATCHES(1),2)%POLY_ORDER+1))
	TYPE(INT2D), INTENT(IN) :: INDX2((BASIS_KVEC(PATCHES(2),1)%POLY_ORDER+1)*(BASIS_KVEC(PATCHES(2),2)%POLY_ORDER+1))
	INTEGER, INTENT(OUT) :: GLOBAL_INDX(2)
	
	INTEGER :: I, J, K, II, JJ, KK, LC_NUM_SUM(2)
	
	DO I = 1, 2
		IF (PATCHES(I).EQ.1) THEN
			LC_NUM_SUM(I) = 0
		ELSE
			LC_NUM_SUM(I) = SUM(BDNDX(1:PATCHES(I)-1,1)%LC_NUM)
		ENDIF
	ENDDO

	DO KK=1, BDNDX(PATCHES(1),1)%LC_NUM
! 				PRINT*, 'KK',KK
		IF (BDNDX(PATCHES(1),KK)%LC_NDX(1).EQ.INDX1(LOCAL_INDX(1))%A .AND. BDNDX(PATCHES(1),KK)%LC_NDX(2).EQ.INDX1(LOCAL_INDX(1))%B) THEN
			GLOBAL_INDX(1) = LC_NUM_SUM(1) + KK
! 							PRINT*, PATCH, 'G1', GLOBAL_INDX(1)
			GOTO 111
		ELSE
			GLOBAL_INDX(1) = 0
		ENDIF
	ENDDO
	111 CONTINUE

	DO KK=1, BDNDX(PATCHES(2),1)%LC_NUM
! 					PRINT*, 'KK',KK
		IF (BDNDX(PATCHES(2),KK)%LC_NDX(1).EQ.INDX2(LOCAL_INDX(2))%A .AND. BDNDX(PATCHES(2),KK)%LC_NDX(2).EQ.INDX2(LOCAL_INDX(2))%B) THEN
			GLOBAL_INDX(2) = LC_NUM_SUM(2) + KK
! 								PRINT*, PATCH, 'G2', GLOBAL_INDX(2)
			GOTO 222
		ELSE
			GLOBAL_INDX(2) = 0
		ENDIF
	ENDDO
	222 CONTINUE

END SUBROUTINE DR_GL_INDX_FIJ

END MODULE INTEGRATION