MODULE ERRORESTIMATE

	USE GEOMETRY
	USE NURBS_BASIS
	USE LOADFUNCTION
	USE GSQUAD

    IMPLICIT NONE
    
CONTAINS

!----MAX. NORM ESTIMATE----
SUBROUTINE MAXNORM(MAX_NORM, COEFF_SOL)

	REAL*8, INTENT(OUT) :: MAX_NORM(5)
	REAL*8, INTENT(IN) :: COEFF_SOL(2*DOF)
	TYPE(POINT2D) :: PHY_PT, REF_PT
	INTEGER :: I, J, K, II, JJ, KK
	TYPE(POINT2D) :: EXDISP, APDISP, ERR_DISP, ERR_LINE_DISP, ERR_POLAR_DISP, TMP_ERR_DISP, MAXDISP
	TYPE(STRESS) :: EXSTR, APSTR, ERR_STR, TMP_ERR_STR, ERR_LINE_STR, ERR_POLAR_STR, MAXSTR
	REAL*8 :: RADIUS, THETA
	INTEGER :: PATCH
	
	ERR_STR = STRESS(0.D0,0.D0,0.D0,0.D0,0.D0)
	MAXSTR 	= STRESS(0.D0,0.D0,0.D0,0.D0,0.D0)
	
	ERR_DISP = POINT2D(0.D0,0.D0)
	MAXDISP = POINT2D(0.D0,0.D0)

	OPEN(11, FILE = './data/ext_disp')
	OPEN(21, FILE = './data/app_disp')
	OPEN(31, FILE = './data/err_disp')
	OPEN(41, FILE = './data/ext_str')
	OPEN(51, FILE = './data/app_str')
	OPEN(61, FILE = './data/err_str')
	
	DO PATCH = 1, NUM_PATCH
		DO JJ = 1, NUMIR(PATCH, 2)-1
	
			CALL GAULEG(IR_GRID(PATCH, 2, JJ), IR_GRID(PATCH, 2, JJ+1), MX_GSY, MX_GSYW, MX_GSPT)
			
			DO II = 1, NUMIR(PATCH, 1)-1
				CALL GAULEG(IR_GRID(PATCH, 1, II), IR_GRID(PATCH, 1, II+1), MX_GSX, MX_GSXW, MX_GSPT)
				
				DO J = 1, MX_GSPT
					DO I = 1, MX_GSPT
						REF_PT = POINT2D(MX_GSX(I), MX_GSY(J))
						PHY_PT = GET_PHY_PT(REF_PT, PATCH)
						CALL GET_RTHETA(RADIUS, THETA, PHY_PT)
						IF(DABS(RADIUS).LE.EPS) THEN
							EXDISP = POINT2D(0.D0, 0.D0); APDISP = POINT2D(0.D0, 0.D0)
						ELSEIF(DABS(PHY_PT%X).LE.EPS .AND. DABS(PHY_PT%Y).LE.EPS) THEN
							EXDISP = POINT2D(0.D0, 0.D0); APDISP = POINT2D(0.D0, 0.D0)
						ELSEIF (PATCH.LE.NUM_IGA_PATCH .AND. RADIUS.LE.INNER_RADIUS) THEN
							GOTO 1
						ELSE
							CALL APPROXSOL(APDISP, APSTR, REF_PT, COEFF_SOL, PATCH, RADIUS)
							EXDISP = EX_DISP(REF_PT, PATCH)
							EXSTR = EX_STRESS(REF_PT, PATCH)
						ENDIF
						TMP_ERR_DISP%X = DABS(EXDISP%X - APDISP%X)
						TMP_ERR_DISP%Y = DABS(APDISP%Y - EXDISP%Y)
						
						TMP_ERR_STR%SXX = DABS(APSTR%SXX - EXSTR%SXX)
						TMP_ERR_STR%SYY = DABS(APSTR%SYY - EXSTR%SYY)
						TMP_ERR_STR%SXY = DABS(APSTR%SXY - EXSTR%SXY)

						WRITE(11,*) PHY_PT, EXDISP%X, EXDISP%Y
						WRITE(21,*) PHY_PT, APDISP%X, APDISP%Y
						WRITE(31,*) PHY_PT, TMP_ERR_DISP%X, TMP_ERR_DISP%Y
						WRITE(41,*) PHY_PT, EXSTR%SXX, EXSTR%SYY, EXSTR%SXY
						WRITE(51,*) PHY_PT, APSTR%SXX, APSTR%SYY, APSTR%SXY
						WRITE(61,*) PHY_PT, TMP_ERR_STR%SXX, TMP_ERR_STR%SYY, TMP_ERR_STR%SXY
						
						IF (TMP_ERR_DISP%X.GE.ERR_DISP%X) THEN
							ERR_DISP%X = TMP_ERR_DISP%X
						ENDIF
						IF (TMP_ERR_DISP%Y.GE.ERR_DISP%Y) THEN
							ERR_DISP%Y = TMP_ERR_DISP%Y
						ENDIF
						
						IF (TMP_ERR_STR%SXX.GE.ERR_STR%SXX) THEN
							ERR_STR%SXX = TMP_ERR_STR%SXX
						ENDIF
						IF (TMP_ERR_STR%SYY.GE.ERR_STR%SYY) THEN
							ERR_STR%SYY = TMP_ERR_STR%SYY
						ENDIF
						IF (TMP_ERR_STR%SXY.GE.ERR_STR%SXY) THEN
							ERR_STR%SXY = TMP_ERR_STR%SXY
						ENDIF
						IF (DABS(EXDISP%X).GE.MAXDISP%X) THEN
							MAXDISP%X = DABS(EXDISP%X)
						ENDIF
						IF (DABS(EXDISP%Y).GE.MAXDISP%Y) THEN
							MAXDISP%Y = DABS(EXDISP%Y)
						ENDIF
						IF (DABS(EXSTR%SXX).GE.MAXSTR%SXX) THEN
							MAXSTR%SXX = DABS(EXSTR%SXX)
						ENDIF
						IF (DABS(EXSTR%SYY).GE.MAXSTR%SYY) THEN
							MAXSTR%SYY = DABS(EXSTR%SYY)
						ENDIF
						IF (DABS(EXSTR%SXY).GE.MAXSTR%SXY) THEN
							MAXSTR%SXY = DABS(EXSTR%SXY)
						ENDIF
						1 CONTINUE
					ENDDO
					WRITE(11,*) ""; WRITE(41,*) ""
				WRITE(21,*) ""; WRITE(51,*) ""
				WRITE(31,*) ""; WRITE(61,*) ""
				ENDDO
				WRITE(11,*) ""; WRITE(41,*) ""
				WRITE(21,*) ""; WRITE(51,*) ""
				WRITE(31,*) ""; WRITE(61,*) ""
			ENDDO
			WRITE(11,*) ""; WRITE(41,*) ""
			WRITE(21,*) ""; WRITE(51,*) ""
			WRITE(31,*) ""; WRITE(61,*) ""
		ENDDO
		WRITE(11,*) ""; WRITE(41,*) ""
		WRITE(21,*) ""; WRITE(51,*) ""
		WRITE(31,*) ""; WRITE(61,*) ""
	ENDDO
	CLOSE(11) ; CLOSE(21) ; CLOSE(31) ; CLOSE(41) ; CLOSE(51); CLOSE(61)
	
	MAX_NORM(1) = ERR_DISP%X*100.D0/MAXDISP%X
	MAX_NORM(2) = ERR_DISP%Y*100.D0/MAXDISP%Y
	MAX_NORM(3) = ERR_STR%SXX*100.D0/MAXSTR%SXX
	MAX_NORM(4) = ERR_STR%SYY*100.D0/MAXSTR%SYY
	MAX_NORM(5) = ERR_STR%SXY*100.D0/MAXSTR%SXY
! 		MAX_NORM(5) = ERR_STR%SXY*100.D0
	
	PRINT*, '<<< REL. MAX. NORM ERROR ESTIMATE : DONE >>>'
	
END SUBROUTINE MAXNORM

SUBROUTINE ENRGY(ENRG, DMY_K, SOL)

	REAL*8, INTENT(IN) :: DMY_K(2*DOF, 2*DOF), SOL(2*DOF)
	REAL*8, INTENT(OUT) :: ENRG(4)
	REAL*8 :: AP, TR
	INTEGER :: I, J

	AP = 0.50D0*DOT_PRODUCT(SOL, MATMUL(DMY_K, SOL))

	IF (PROBLEM.EQ.0) THEN
		TR = 1.5D0*(STRESS_E(1,1) + STRESS_E(1,2) + STRESS_E(2,1) + STRESS_E(2,2))
	ELSEIF (PROBLEM.EQ.1) THEN
		TR = 7884.61538461538475530d0
	ELSEIF (PROBLEM.EQ.2) THEN
! 		TR = 1253.66300366300360d0
		TR = 14258.721708985884106D0
	ELSEIF (PROBLEM.EQ.3) THEN
		TR = 1412.4820475962796990643255412580D0
	ELSEIF (PROBLEM.EQ.4) THEN
		!! Lambda = 2/3
! 		TR = 0.0106234974159766D0
		!! Lambda = 0.544483737
		TR = 4.154544230D0*(1.D0/E)
	ELSEIF (PROBLEM==5) THEN
		TR = 4226.229869155190D0
	ELSEIF (PROBLEM==6) THEN
		TR = 1109.02064272726238414d0
	ELSEIF (PROBLEM==7) THEN
		TR = 315.92993313102198272D0
	ELSEIF (PROBLEM==8) THEN
!		Lambda = 2
		IF 		 (DABS(LAMBDA - 2.D0)<=EPS) THEN
			TR = 1016.96952348408819940D0
!		Lambda = 3
		ELSEIF (DABS(LAMBDA - 3.D0)<=EPS) THEN
			TR = 543.037183719858148830D0
		ENDIF
	ELSEIF (PROBLEM==9) THEN
		TR = 2895.2199671265016150D0
	ELSEIF (PROBLEM==10) THEN
		TR = 576.977007702349737880D0
	ELSEIF (PROBLEM==11) THEN
		TR = 3343.39505001151474060D0
	ENDIF

	ENRG(3) = DSQRT(DABS(AP - TR))*100.D0
	ENRG(4) = DSQRT(DABS(AP - TR) / TR)*100.D0

	ENRG(1) = TR; ENRG(2) = AP

	PRINT*, '<<< REL. ENERGY NORM ERROR ESTIMATE : DONE >>>'

END SUBROUTINE ENRGY

SUBROUTINE L2_NORM_ERROR(L2_NORM, COEFF_SOL)
	
	REAL*8, INTENT(OUT) :: L2_NORM(2)
	REAL*8, INTENT(IN) :: COEFF_SOL(2*DOF)
	INTEGER :: I, J, II, JJ, SUB_NUMLN(2), N, KK, K, PATCH
	REAL*8 :: SUB_LN_LENGTH(2), WEIGHT, DIFF_NN, DET_M, RADIUS, THETA
	TYPE(VEC2D) :: SUB_LN
	TYPE(POINT2D) :: GSPT, DMY_GSPT, PHY_PT
	TYPE(MATRIX_22) :: JACOB
	TYPE(POINT2D) :: EXDISP, APDISP, INTF(2)
	TYPE(STRESS) :: APSTR
	
	N = L2_GSPT
	SUB_NUMLN = (/2,2/)
	INTF(:) = POINT2D(0.D0,0.D0)
	
	DO PATCH = NUM_IGA_PATCH + 1, NUM_PATCH
		DO JJ = 1, NUMIR(PATCH,1)-1
			SUB_LN_LENGTH(1) = DABS(IR_GRID(PATCH,1,JJ+1) - IR_GRID(PATCH,1,JJ))/(1.D0*SUB_NUMLN(1))
			DO J=1, SUB_NUMLN(1)
				CALL GAULEG(IR_GRID(PATCH,1,JJ)+(J-1)*SUB_LN_LENGTH(1), IR_GRID(PATCH,1,JJ)+J*SUB_LN_LENGTH(1), L2_GSX, L2_GSXW, N)
				DO II = 1, NUMIR(PATCH,2)-1
					SUB_LN_LENGTH(2) = DABS(IR_GRID(PATCH,2,II+1) - IR_GRID(PATCH,2,II))/(1.D0*SUB_NUMLN(2))
					DO I = 1, SUB_NUMLN(2)
						CALL GAULEG(IR_GRID(PATCH,2,II)+(I-1)*SUB_LN_LENGTH(2), IR_GRID(PATCH,2,II)+I*SUB_LN_LENGTH(2), L2_GSY, L2_GSYW, N)
						DO KK = 1, N
							DO K = 1, N
								GSPT = POINT2D(GSX(KK),GSY(K))
								DMY_GSPT = GSPT
								JACOB= GET_JACOBIAN_MATRIX(DMY_GSPT,PATCH)
								DET_M = .DETERMINANT.JACOB
								EXDISP = EX_DISP(DMY_GSPT,PATCH)
								CALL GET_RTHETA(RADIUS, THETA, DMY_GSPT)
								CALL APPROXSOL(APDISP, APSTR, DMY_GSPT, COEFF_SOL, PATCH, RADIUS)
								INTF(1)%X = INTF(1)%X + (EXDISP%X - APDISP%X)**2*DET_M*GSXW(KK)*GSYW(K)
								INTF(1)%Y = INTF(1)%Y + (EXDISP%Y - APDISP%Y)**2*DET_M*GSXW(KK)*GSYW(K)
								INTF(2)%X = INTF(2)%X + EXDISP%X**2*DET_M*GSXW(KK)*GSYW(K)
								INTF(2)%Y = INTF(2)%Y + EXDISP%Y**2*DET_M*GSXW(KK)*GSYW(K)
							ENDDO
						ENDDO
					ENDDO
				ENDDO
			ENDDO
		ENDDO
	ENDDO
	
	L2_NORM(1) = DSQRT(INTF(1)%X/INTF(2)%X)*100.D0
	L2_NORM(2) = DSQRT(INTF(1)%Y/INTF(2)%Y)*100.D0
	
	PRINT*, '<<< REL. L2 NORM ERROR ESTIMATE : DONE >>>'
	
END SUBROUTINE L2_NORM_ERROR

SUBROUTINE APPROXSOL(APDISP, APSTR, REF_PT, COEFF_SOL, PATCH, RADIUS)

	INTEGER, INTENT(IN) :: PATCH
	TYPE(POINT2D), INTENT(IN) :: REF_PT
	REAL*8, INTENT(IN) :: COEFF_SOL(2*DOF), RADIUS
	TYPE(POINT2D), INTENT(OUT) :: APDISP
	TYPE(STRESS), INTENT(OUT) :: APSTR
	
	TYPE(FVALUE) :: SF(DOF)
	TYPE(FVALUE) :: LOCAL_IGA_SF(NUM_IGA_PATCH,(BASIS_KVEC(1,1)%POLY_ORDER+1)*(BASIS_KVEC(1,2)%POLY_ORDER+1))
	TYPE(FVALUE) :: LOCAL_EGM_SF(NUM_EGM_PATCH,(BASIS_KVEC(NUM_IGA_PATCH + 1,1)%POLY_ORDER+1)*(BASIS_KVEC(NUM_IGA_PATCH + 1,2)%POLY_ORDER+1))

	TYPE(INT2D) :: IGA_INDX(NUM_IGA_PATCH,(BASIS_KVEC(1,1)%POLY_ORDER+1)*(BASIS_KVEC(1,2)%POLY_ORDER+1))
	TYPE(INT2D) :: EGM_INDX(NUM_EGM_PATCH,(BASIS_KVEC(NUM_IGA_PATCH + 1,1)%POLY_ORDER+1)*(BASIS_KVEC(NUM_IGA_PATCH + 1,2)%POLY_ORDER+1))

	TYPE(POINT2D) :: PHY_PT, POLAR_PT, PHYPT_F, PHYPT_G, INV_PHYPT_F, INV_PHYPT_G
	TYPE(MATRIX_22) :: JACOB(NUM_PATCH), JACOB_FG
	REAL*8 :: DMY_STRAIN(3), APP_STRAIN(3), DMY_STRESS(3), R, THETA
	INTEGER :: I, J, II, JJ, KK, GLOBAL_INDX, LOCAL_DOF_SUM, IGA_PATCH, EGM_PATCH
	LOGICAL :: INTERFACE_MASK
	
	APDISP = POINT2D(0.D0,0.D0)
	APSTR = STRESS(0.0D0, 0.0D0, 0.0D0, 0.D0, 0.D0)
	SF(:) = FVALUE(0.D0,0.D0,0.D0,0.D0,0.D0,0.D0)
	
	DO I = 1, NUM_IGA_PATCH
		LOCAL_IGA_SF(I,:) =  FVALUE(0.D0,0.D0,0.D0,0.D0,0.D0,0.D0)
	ENDDO
	
	DO I = 1, NUM_EGM_PATCH
		LOCAL_EGM_SF(I,:) =  FVALUE(0.D0,0.D0,0.D0,0.D0,0.D0,0.D0)
	ENDDO
	
	IF (PATCH.EQ.1) THEN
		LOCAL_DOF_SUM = 0
	ELSE
		LOCAL_DOF_SUM = SUM(LOCAL_DOF(1:PATCH-1))
	ENDIF
	
	DO I=1, NUM_PATCH
		JACOB(I) = GET_JACOBIAN_MATRIX(REF_PT, I)
	ENDDO
	
	IF (PATCH.LE.NUM_IGA_PATCH) THEN
		IF (RADIUS.GT.INNER_RADIUS) THEN
			!! Compute IGA basis functions
			DO I = 1, NUM_IGA_PATCH
				CALL GET_ALL_PHY_NURBS_SURFACE_2D(LOCAL_IGA_SF(I,:), IGA_INDX(I,:), REF_PT, JACOB(I), I)
			ENDDO
			
			DO I = 1, NUM_IGA_PATCH
				DO JJ=1, UBOUND(LOCAL_IGA_SF,2)
					DO II=1, LOCAL_DOF(I)
						IF (PATCH==I .AND. NDX(1,LOCAL_DOF_SUM + II).EQ.IGA_INDX(I,JJ)%A .AND. NDX(2,LOCAL_DOF_SUM + II).EQ.IGA_INDX(I,JJ)%B) THEN
							SF(LOCAL_DOF_SUM + II) = SF(LOCAL_DOF_SUM + II) + LOCAL_IGA_SF(I,JJ)
							GOTO 1
						ENDIF
					ENDDO
					1 CONTINUE
				ENDDO
			ENDDO
			
			!! Compute IGA basis functions on interfaces
			DO JJ=1, NUM_IGA_PATCH
				DO KK=1, UBOUND(INTERFACE_NDX,1)
					DO I=1, UBOUND(IGA_INDX,2)
						DO II=1, UBOUND(INTERFACE_NDX(1)%SLAVE_PATCH_NDX(:),1)
							IF (INTERFACE_NDX(KK)%MASTER_PATCH_NDX.EQ.JJ .AND.			 &
									INTERFACE_NDX(KK)%SLAVE_PATCH_NDX(II).EQ.PATCH .AND. &
									INTERFACE_NDX(KK)%LC_NDX(2*II+1).EQ.IGA_INDX(PATCH,I)%A .AND. &
									INTERFACE_NDX(KK)%LC_NDX(2*(II+1)).EQ.IGA_INDX(PATCH,I)%B) THEN
								SF(INTERFACE_NDX(KK)%GL_NDX) = SF(INTERFACE_NDX(KK)%GL_NDX) + LOCAL_IGA_SF(PATCH,I)
								GOTO 3
							ENDIF
						ENDDO
						3 CONTINUE
					ENDDO
				ENDDO
			ENDDO
		ENDIF
	!! Compute EGM basis functions
	ELSEIF (PATCH.GE.NUM_IGA_PATCH+1) THEN
		EGM_PATCH = PATCH - NUM_IGA_PATCH
		PHYPT_F = GET_PHY_PT(REF_PT, PATCH)						! F(xi,eta)
		IGA_PATCH = GET_IGA_PATCH_INDX(PHYPT_F) 					! Find the index of IGA patch
		INV_PHYPT_G = GET_REF_PT(PHYPT_F, IGA_PATCH)			! Inverse function of G(x,y)
		JACOB_FG = GET_JACOBIAN_MATRIX(INV_PHYPT_G, IGA_PATCH)
		CALL GET_ALL_PHY_NURBS_SURFACE_2D(LOCAL_IGA_SF(IGA_PATCH,:), IGA_INDX(IGA_PATCH,:), INV_PHYPT_G, JACOB_FG, IGA_PATCH)
		
		CALL GET_ALL_PHY_BASIS_IN_INT(LOCAL_EGM_SF(EGM_PATCH,:), EGM_INDX(EGM_PATCH,:), REF_PT, JACOB(PATCH), PATCH)
		
		LOCAL_DOF_SUM = SUM(LOCAL_DOF(1:PATCH-1))
		
		DO JJ=1, UBOUND(LOCAL_EGM_SF,2)
			DO II=1, LOCAL_DOF(PATCH)
				IF (NDX(1,LOCAL_DOF_SUM + II).EQ.EGM_INDX(EGM_PATCH,JJ)%A .AND. NDX(2,LOCAL_DOF_SUM + II).EQ.EGM_INDX(EGM_PATCH,JJ)%B) THEN
					SF(LOCAL_DOF_SUM + II) = SF(LOCAL_DOF_SUM + II) + LOCAL_EGM_SF(EGM_PATCH,JJ)
					GOTO 2
				ENDIF
			ENDDO
			2 CONTINUE
		ENDDO
		
		LOCAL_DOF_SUM = SUM(LOCAL_DOF(1:IGA_PATCH-1))
			
		DO JJ=1, UBOUND(LOCAL_IGA_SF,2)
			DO II=1, LOCAL_DOF(IGA_PATCH)
				IF (NDX(1,LOCAL_DOF_SUM + II).EQ.IGA_INDX(IGA_PATCH,JJ)%A .AND. NDX(2,LOCAL_DOF_SUM + II).EQ.IGA_INDX(IGA_PATCH,JJ)%B) THEN
					SF(LOCAL_DOF_SUM + II) = SF(LOCAL_DOF_SUM + II) + LOCAL_IGA_SF(IGA_PATCH,JJ)
					GOTO 5
				ENDIF
			ENDDO
			5 CONTINUE
		ENDDO
		
		DO JJ=1, NUM_IGA_PATCH
			DO KK=1, UBOUND(INTERFACE_NDX,1)
				DO I=1, UBOUND(IGA_INDX,2)
					DO II=1, UBOUND(INTERFACE_NDX(1)%SLAVE_PATCH_NDX(:),1)
						IF (INTERFACE_NDX(KK)%MASTER_PATCH_NDX.EQ.JJ .AND. INTERFACE_NDX(KK)%SLAVE_PATCH_NDX(II).EQ.IGA_PATCH .AND. &
								INTERFACE_NDX(KK)%LC_NDX(2*II+1).EQ.IGA_INDX(IGA_PATCH,I)%A .AND. INTERFACE_NDX(KK)%LC_NDX(2*(II+1)).EQ.IGA_INDX(IGA_PATCH,I)%B) THEN
							SF(INTERFACE_NDX(KK)%GL_NDX) = SF(INTERFACE_NDX(KK)%GL_NDX) + LOCAL_IGA_SF(IGA_PATCH,I)
							GOTO 6
						ENDIF
					ENDDO
					6 CONTINUE
				ENDDO
			ENDDO
		ENDDO
	ENDIF

	APDISP%X = DOT_PRODUCT(COEFF_SOL(1:DOF), SF(:)%D00)
	APDISP%Y = DOT_PRODUCT(COEFF_SOL(DOF+1:2*DOF), SF(:)%D00)
	APP_STRAIN = (/0.D0,0.D0,0.D0/)
	DO II=1, DOF
		DMY_STRAIN = (/COEFF_SOL(II)*SF(II)%D10, COEFF_SOL(DOF+II)*SF(II)%D01, COEFF_SOL(II)*SF(II)%D01 + COEFF_SOL(DOF+II)*SF(II)%D10/)
		APP_STRAIN = (/APP_STRAIN(1) + DMY_STRAIN(1),APP_STRAIN(2) + DMY_STRAIN(2),APP_STRAIN(3) + DMY_STRAIN(3)/)
	ENDDO
	DMY_STRESS = MATMUL(STRESS_E, APP_STRAIN)
	APSTR = STRESS(DMY_STRESS(1), DMY_STRESS(2), DMY_STRESS(3), 0.D0, 0.D0)
			
END SUBROUTINE APPROXSOL

END MODULE ERRORESTIMATE
