	MODULE INTEGRATION

	USE GSQUAD
	USE NURBS_BASIS
	USE LOADFUNCTION

	implicit integer (i-n)
	implicit real(8) (a-h,o-z)

CONTAINS


!------------------INTEGRAL CODE FOR THE STIFFNESS MATRIX ELEMENT--------------
SUBROUTINE GEN_KF(STIF_K, STIF_F)

	REAL*8, INTENT(OUT) :: STIF_K(2*DOF, 2*DOF), STIF_F(2*DOF)
	TYPE(RECPATCH) :: IRBOX
	TYPE(POINT2D) :: GSPT, DMY_GSPT, LOAD_F(NUMGSPT**2)
	TYPE(INT2D), ALLOCATABLE :: INDX1(:), INDX2(:)
	TYPE(MATRIX_22) :: JACOB
	TYPE(FVALUE), ALLOCATABLE :: SF1(:,:), SF2(:,:)
	INTEGER :: I,J, K, II, JJ, KK, N, GLOBAL_INDX(6), PATCH, IGA_PATCH
	REAL*8 :: DIFF_XX, DIFF_YY, DIFF_XY, DIFF_YX, DIFF_NN, WEIGHT(NUMGSPT**2)
	
	STIF_K(:,:) = 0.D0; STIF_F(:) = 0.D0

	!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!! IGA - IGA !!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
	!! Compute an element on IGA - IGA
	DO PATCH = 1, NUM_PATCH
		ALLOCATE(INDX1((BASIS_KVEC(PATCH,1)%POLY_ORDER+1)*(BASIS_KVEC(PATCH,2)%POLY_ORDER+1)))
		ALLOCATE(SF1(NUMGSPT**2, (BASIS_KVEC(PATCH,1)%POLY_ORDER+1)*(BASIS_KVEC(PATCH,2)%POLY_ORDER+1)))
		DO JJ=1, NUMIR(PATCH,2)-1
			DO II=1, NUMIR(PATCH,1)-1
				CALL STIF_LC_INT_II(SF1, WEIGHT, LOAD_F(:), INDX1, PATCH, (/II,JJ/))
				DO I = 1, UBOUND(INDX1,1)
					DO J = 1, UBOUND(INDX1,1)
						CALL STIF_FIND_GLOBAL_INDX_FII(GLOBAL_INDX(1:2), PATCH, (/I,J/), INDX1)
						IF (GLOBAL_INDX(1).NE.0 .AND. GLOBAL_INDX(2).NE.0) THEN
							DIFF_XX = DOT_PRODUCT(PRODUCT(RESHAPE((/SF1(:,I)%D10, WEIGHT(:)/), (/NUMGSPT**2, 2/), ORDER=ORDER1), 2), SF1(:,J)%D10)
							DIFF_YY = DOT_PRODUCT(PRODUCT(RESHAPE((/SF1(:,I)%D01, WEIGHT(:)/), (/NUMGSPT**2, 2/), ORDER=ORDER1), 2), SF1(:,J)%D01)
							DIFF_YX = DOT_PRODUCT(PRODUCT(RESHAPE((/SF1(:,I)%D01, WEIGHT(:)/), (/NUMGSPT**2, 2/), ORDER=ORDER1), 2), SF1(:,J)%D10)
							DIFF_XY = DOT_PRODUCT(PRODUCT(RESHAPE((/SF1(:,I)%D10, WEIGHT(:)/), (/NUMGSPT**2, 2/), ORDER=ORDER1), 2), SF1(:,J)%D01)
							
							STIF_K(GLOBAL_INDX(1),GLOBAL_INDX(2)) = STIF_K(GLOBAL_INDX(1),GLOBAL_INDX(2)) + STRESS_E(1,1)*DIFF_XX + STRESS_E(3,3)*DIFF_YY
							STIF_K(DOF+GLOBAL_INDX(1),DOF+GLOBAL_INDX(2)) = STIF_K(DOF+GLOBAL_INDX(1),DOF+GLOBAL_INDX(2)) + STRESS_E(2,2)*DIFF_YY + STRESS_E(3,3)*DIFF_XX
							STIF_K(GLOBAL_INDX(1),DOF+GLOBAL_INDX(2)) = STIF_K(GLOBAL_INDX(1),DOF+GLOBAL_INDX(2)) + STRESS_E(1,2)*DIFF_XY + STRESS_E(3,3)*DIFF_YX
! 							STIF_K(DOF+GLOBAL_INDX(2),GLOBAL_INDX(1)) = STIF_K(DOF+GLOBAL_INDX(2),GLOBAL_INDX(1)) + STRESS_E(2,1)*DIFF_XY + STRESS_E(3,3)*DIFF_YX
						ENDIF
					ENDDO
					IF (GLOBAL_INDX(1).NE.0) THEN
						DIFF_NN = DOT_PRODUCT(PRODUCT(RESHAPE((/SF1(:,I)%D00, WEIGHT(:)/), (/NUMGSPT**2, 2/), ORDER=ORDER1), 2), LOAD_F(:)%X)
						STIF_F(GLOBAL_INDX(1)) = STIF_F(GLOBAL_INDX(1)) + DIFF_NN
						DIFF_NN = DOT_PRODUCT(PRODUCT(RESHAPE((/SF1(:,I)%D00, WEIGHT(:)/), (/NUMGSPT**2, 2/), ORDER=ORDER1), 2), LOAD_F(:)%Y)
						STIF_F(DOF + GLOBAL_INDX(1)) = STIF_F(DOF + GLOBAL_INDX(1)) + DIFF_NN
					ENDIF
				ENDDO
			ENDDO
		ENDDO
		DEALLOCATE(SF1, INDX1)
	ENDDO

! 	PRINT*, 'HERE1-STIF_K(10,DOF+3)', STIF_K(10,DOF+3)
! 	PRINT*, 'HERE1-STIF_K(3,DOF+10)', STIF_K(3,DOF+10)
	
! 	STOP
	
	!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!! IGA - INTERFACE / INTERFACE - INTERFACE !!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
	DO IGA_PATCH = 1, NUM_PATCH-1
		DO PATCH = IGA_PATCH+1, NUM_PATCH
			ALLOCATE(INDX1((BASIS_KVEC(PATCH,1)%POLY_ORDER+1)*(BASIS_KVEC(PATCH,2)%POLY_ORDER+1)))
			ALLOCATE(SF1(NUMGSPT**2, (BASIS_KVEC(PATCH,1)%POLY_ORDER+1)*(BASIS_KVEC(PATCH,2)%POLY_ORDER+1)))
			DO JJ=1, NUMIR(PATCH,2)-1
				DO II=1, NUMIR(PATCH,1)-1
					CALL STIF_LC_INT_II(SF1, WEIGHT, LOAD_F, INDX1, PATCH, (/II,JJ/))
					DO I = 1, UBOUND(INDX1,1)
						DO J = 1, UBOUND(INDX1,1)
							!! Compute an element on an interface - interface of one same IGA patch
							CALL STIF_FIND_GLOBAL_INDX_ALONG_INTERFACE_FII(GLOBAL_INDX, (/IGA_PATCH,PATCH/), (/I,J/), INDX1)
							IF ((GLOBAL_INDX(1).NE.0 .AND. GLOBAL_INDX(2).NE.0) .OR. &
									(GLOBAL_INDX(3).NE.0 .AND. GLOBAL_INDX(4).NE.0) .OR. &
									(GLOBAL_INDX(5).NE.0 .AND. GLOBAL_INDX(6).NE.0)) THEN
								DIFF_XX = DOT_PRODUCT(PRODUCT(RESHAPE((/SF1(:,I)%D10, WEIGHT(:)/), (/NUMGSPT**2, 2/), ORDER=ORDER1), 2), SF1(:,J)%D10)
								DIFF_YY = DOT_PRODUCT(PRODUCT(RESHAPE((/SF1(:,I)%D01, WEIGHT(:)/), (/NUMGSPT**2, 2/), ORDER=ORDER1), 2), SF1(:,J)%D01)
								DIFF_YX = DOT_PRODUCT(PRODUCT(RESHAPE((/SF1(:,I)%D01, WEIGHT(:)/), (/NUMGSPT**2, 2/), ORDER=ORDER1), 2), SF1(:,J)%D10)
								DIFF_XY = DOT_PRODUCT(PRODUCT(RESHAPE((/SF1(:,I)%D10, WEIGHT(:)/), (/NUMGSPT**2, 2/), ORDER=ORDER1), 2), SF1(:,J)%D01)
								CALL STIF_GET_ELEMENT(STIF_K, GLOBAL_INDX(1:6), DIFF_XX, DIFF_YY, DIFF_XY, DIFF_YX)
							ENDIF
! 							PRINT*, 'IGA-INT HERE 1', IGA_PATCH, PATCH, I, J, GLOBAL_INDX(1:2), STIF_K(10,3)
! 								PRINT*, 'IGA-INT HERE 1 - STIF_K(10,DOF+3)', STIF_K(10,DOF+3)
! 								PRINT*, 'IGA-INT HERE 1 - STIF_K(3,DOF+10)', STIF_K(3,DOF+10)
							!! Compute an element on an interface - interface of two different IGA patches
							CALL STIF_FIND_GLOBAL_INDX_ALONG_INTERFACE_FIJ(GLOBAL_INDX, (/IGA_PATCH,PATCH/), (/I,J/), INDX1)
							IF ((GLOBAL_INDX(1).NE.0 .AND. GLOBAL_INDX(2).NE.0) .OR. &
									(GLOBAL_INDX(3).NE.0 .AND. GLOBAL_INDX(4).NE.0) .OR. &
									(GLOBAL_INDX(5).NE.0 .AND. GLOBAL_INDX(6).NE.0)) THEN
								DIFF_XX = DOT_PRODUCT(PRODUCT(RESHAPE((/SF1(:,I)%D10, WEIGHT(:)/), (/NUMGSPT**2, 2/), ORDER=ORDER1), 2), SF1(:,J)%D10)
								DIFF_YY = DOT_PRODUCT(PRODUCT(RESHAPE((/SF1(:,I)%D01, WEIGHT(:)/), (/NUMGSPT**2, 2/), ORDER=ORDER1), 2), SF1(:,J)%D01)
								DIFF_YX = DOT_PRODUCT(PRODUCT(RESHAPE((/SF1(:,I)%D01, WEIGHT(:)/), (/NUMGSPT**2, 2/), ORDER=ORDER1), 2), SF1(:,J)%D10)
								DIFF_XY = DOT_PRODUCT(PRODUCT(RESHAPE((/SF1(:,I)%D10, WEIGHT(:)/), (/NUMGSPT**2, 2/), ORDER=ORDER1), 2), SF1(:,J)%D01)
								CALL STIF_GET_ELEMENT(STIF_K, GLOBAL_INDX(1:6), DIFF_XX, DIFF_YY, DIFF_XY, DIFF_YX, 'SYM')
							ENDIF
! 							PRINT*, 'IGA-INT HERE 2', IGA_PATCH, PATCH, I, J, GLOBAL_INDX(1:2), STIF_K(10,3)
! 								PRINT*, 'IGA-INT HERE 2 - STIF_K(10,DOF+3)', STIF_K(10,DOF+3)
! 								PRINT*, 'IGA-INT HERE 2 - STIF_K(3,DOF+10)', STIF_K(3,DOF+10)
							!! Compute an element on an interface - IGA patch
							CALL STIF_FIND_GLOBAL_INDX_INTERFACE_AND_NONINTERFACE(GLOBAL_INDX, (/IGA_PATCH,PATCH/), (/I,J/), INDX1)
							IF ((GLOBAL_INDX(1).NE.0 .AND. GLOBAL_INDX(2).NE.0) .OR. &
									(GLOBAL_INDX(3).NE.0 .AND. GLOBAL_INDX(4).NE.0) .OR. &
									(GLOBAL_INDX(5).NE.0 .AND. GLOBAL_INDX(6).NE.0)) THEN
								DIFF_XX = DOT_PRODUCT(PRODUCT(RESHAPE((/SF1(:,I)%D10, WEIGHT(:)/), (/NUMGSPT**2, 2/), ORDER=ORDER1), 2), SF1(:,J)%D10)
								DIFF_YY = DOT_PRODUCT(PRODUCT(RESHAPE((/SF1(:,I)%D01, WEIGHT(:)/), (/NUMGSPT**2, 2/), ORDER=ORDER1), 2), SF1(:,J)%D01)
								DIFF_YX = DOT_PRODUCT(PRODUCT(RESHAPE((/SF1(:,I)%D01, WEIGHT(:)/), (/NUMGSPT**2, 2/), ORDER=ORDER1), 2), SF1(:,J)%D10)
								DIFF_XY = DOT_PRODUCT(PRODUCT(RESHAPE((/SF1(:,I)%D10, WEIGHT(:)/), (/NUMGSPT**2, 2/), ORDER=ORDER1), 2), SF1(:,J)%D01)
								CALL STIF_GET_ELEMENT(STIF_K, GLOBAL_INDX(1:6), DIFF_XX, DIFF_YY, DIFF_XY, DIFF_YX, 'SYM')
							ENDIF
! 							PRINT*, 'IGA-INT HERE 3', IGA_PATCH, PATCH, I, J, GLOBAL_INDX(1:2), STIF_K(10,3)
! 								PRINT*, 'IGA-INT HERE 3 - STIF_K(10,DOF+3)', STIF_K(10,DOF+3)
! 								PRINT*, 'IGA-INT HERE 3 - STIF_K(3,DOF+10)', STIF_K(3,DOF+10)
						ENDDO
! 						READ(*,*) 
! 						CALL STIF_FIND_GLOBAL_INDX_ALONG_INTERFACE_FII(GLOBAL_INDX, (/IGA_PATCH,PATCH/), (/I,I/), INDX1)
						IF (GLOBAL_INDX(1).NE.0 .OR. GLOBAL_INDX(3).NE.0 .OR. GLOBAL_INDX(5).NE.0) THEN
							DIFF_NN = DOT_PRODUCT(PRODUCT(RESHAPE((/SF1(:,I)%D00, WEIGHT(:)/), (/NUMGSPT**2, 2/), ORDER=ORDER1), 2), LOAD_F(:)%X)
							CALL LOAD_VC_GET_ELEMENT(STIF_F, GLOBAL_INDX, DIFF_NN, 'U')
							DIFF_NN = DOT_PRODUCT(PRODUCT(RESHAPE((/SF1(:,I)%D00, WEIGHT(:)/), (/NUMGSPT**2, 2/), ORDER=ORDER1), 2), LOAD_F(:)%Y)
							CALL LOAD_VC_GET_ELEMENT(STIF_F, GLOBAL_INDX, DIFF_NN, 'V')
						ENDIF
					ENDDO
				ENDDO
			ENDDO
			DEALLOCATE(SF1, INDX1)
		ENDDO
	ENDDO
	
! 	PRINT*, 'HERE1-STIF_K(10,DOF+3)', STIF_K(10,DOF+3)
! 	PRINT*, 'HERE1-STIF_K(3,DOF+10)', STIF_K(3,DOF+10)
	
! 	STOP
	DO I = DOF + 1, 2*DOF
		DO J = 1, DOF
			STIF_K(I,J) = STIF_K(J,I)
		ENDDO
	ENDDO
! 	PRINT*, 'HERE3', STIF_K(10,3)
	
	WRITE(*,*)
	WRITE(*,*) '<<< ASSEMBLE STIFFNESS MATRIX AND LOAD VECTOR : DONE >>>'
	WRITE(*,*)
	
END SUBROUTINE GEN_KF

!! Compute line integration on dirichlet boundary (Least square method)
SUBROUTINE GEN_BD_LN(SUB_K, SUB_F)

	REAL*8, INTENT(OUT) :: SUB_K(SUM(DR_BDNDX(:,1)%LC_NUM), SUM(DR_BDNDX(:,1)%LC_NUM))
	TYPE(POINT2D), INTENT(OUT) :: SUB_F(SUM(DR_BDNDX(:,1)%LC_NUM))
	TYPE(POINT2D) :: EXACT_ON_BD(NUMGSPT)
	TYPE(FVALUE), ALLOCATABLE :: SF1(:,:), SF2(:,:)
	TYPE(INT2D), ALLOCATABLE :: INDX1(:), INDX2(:)
	TYPE(POINT2D) :: BDPT(2)
	REAL*8 :: WEIGHT(NUMGSPT)
	REAL*8 :: DIFF_NN, DET_M, SUB_LN_LENGTH
	INTEGER :: I, J, II, JJ, KK, N, GLOBAL_INDX(2), PATCH, IGA_PATCH, SUB_NUMLN, MASTER_PATCH, SLAVE_PATCH
	TYPE(VEC2D) :: SUB_LN
	TYPE(MATRIX_22) :: JACOB
	
	N = NUMGSPT; SUB_K(:,:)=0.D0; SUB_F(:) = POINT2D(0.D0,0.D0); SUB_NUMLN = 1
	
!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
	DO PATCH = 1, NUM_PATCH
		ALLOCATE(SF1(NUMGSPT, (BASIS_KVEC(PATCH,1)%POLY_ORDER+1)*(BASIS_KVEC(PATCH,2)%POLY_ORDER+1)))
		ALLOCATE(INDX1((BASIS_KVEC(PATCH,1)%POLY_ORDER+1)*(BASIS_KVEC(PATCH,2)%POLY_ORDER+1)))
		DO JJ = 1, NUMIR(PATCH,2)-1
			SUB_LN_LENGTH = DABS(IR_GRID(PATCH,2,JJ+1) - IR_GRID(PATCH,2,JJ))/(1.D0*SUB_NUMLN)
			IF (PATCH.EQ.2 .OR. PATCH.EQ.3) THEN
			!----------------------- LEFT SIDE ON THE PARAMETER SPACE ------------------------!
				DO II=1, SUB_NUMLN
					SUB_LN = VEC2D(POINT2D(0.D0,IR_GRID(PATCH,2,JJ)+(II-1)*SUB_LN_LENGTH), POINT2D(0.D0,IR_GRID(PATCH,2,JJ)+II*SUB_LN_LENGTH))
					CALL LEAST_SQUARE_LC_INT_II(SF1, INDX1, WEIGHT, EXACT_ON_BD, PATCH, SUB_LN, 'L')
					DO I=1, UBOUND(INDX1,1)
						DO J=1, UBOUND(INDX1,1)
							DIFF_NN = 0.D0
							CALL DR_GL_INDX_FII(GLOBAL_INDX, PATCH, (/I,J/), INDX1)
							IF (GLOBAL_INDX(1).EQ.0 .OR. GLOBAL_INDX(2).EQ.0) THEN
							ELSE
								DIFF_NN = DOT_PRODUCT(PRODUCT(RESHAPE((/SF1(:,I)%D00, WEIGHT(:)/), (/NUMGSPT, 2/), ORDER=ORDER1), 2), SF1(:,J)%D00)
								SUB_K(GLOBAL_INDX(1), GLOBAL_INDX(2)) = SUB_K(GLOBAL_INDX(1), GLOBAL_INDX(2)) + DIFF_NN
							ENDIF
						ENDDO
						IF (GLOBAL_INDX(1).EQ.0) THEN
						ELSE
							DIFF_NN = DOT_PRODUCT(PRODUCT(RESHAPE((/SF1(:,I)%D00, WEIGHT(:)/), (/NUMGSPT, 2/), ORDER=ORDER1), 2), EXACT_ON_BD(:)%X)
							SUB_F(GLOBAL_INDX(1))%X = SUB_F(GLOBAL_INDX(1))%X + DIFF_NN
							DIFF_NN = DOT_PRODUCT(PRODUCT(RESHAPE((/SF1(:,I)%D00, WEIGHT(:)/), (/NUMGSPT, 2/), ORDER=ORDER1), 2), EXACT_ON_BD(:)%Y)
							SUB_F(GLOBAL_INDX(1))%Y = SUB_F(GLOBAL_INDX(1))%Y + DIFF_NN
						ENDIF
					ENDDO
! 					PRINT*, 'LF-1', PATCH, JJ, SUB_K(8,8)
					
					DO MASTER_PATCH = 1, PATCH-1
					!-----------------Compute elements on interface (i.e. FII)---------------------
						DO I = 1, UBOUND(INDX1,1)
							DO J = 1, UBOUND(INDX1,1)
								CALL DR_FIND_GL_INDX_ALONG_INTERFACE_FII(GLOBAL_INDX, (/MASTER_PATCH, PATCH/), (/I,J/), INDX1)
								IF (GLOBAL_INDX(1).EQ.0 .OR. GLOBAL_INDX(2).EQ.0) THEN
								ELSE
			! 								PRINT*, 'HERE 1', GLOBAL_INDX
									DIFF_NN = DOT_PRODUCT(PRODUCT(RESHAPE((/SF1(:,I)%D00, WEIGHT(:)/), (/NUMGSPT, 2/), ORDER=ORDER1), 2), SF1(:,J)%D00)
									SUB_K(GLOBAL_INDX(1), GLOBAL_INDX(2)) = SUB_K(GLOBAL_INDX(1), GLOBAL_INDX(2)) + DIFF_NN
								ENDIF
							ENDDO
							IF (GLOBAL_INDX(1).EQ.0) THEN
							ELSE
								DIFF_NN = DOT_PRODUCT(PRODUCT(RESHAPE((/SF1(:,I)%D00, WEIGHT(:)/), (/NUMGSPT, 2/), ORDER=ORDER1), 2), EXACT_ON_BD(:)%X)
								SUB_F(GLOBAL_INDX(1))%X = SUB_F(GLOBAL_INDX(1))%X + DIFF_NN
								DIFF_NN = DOT_PRODUCT(PRODUCT(RESHAPE((/SF1(:,I)%D00, WEIGHT(:)/), (/NUMGSPT, 2/), ORDER=ORDER1), 2), EXACT_ON_BD(:)%Y)
							SUB_F(GLOBAL_INDX(1))%Y = SUB_F(GLOBAL_INDX(1))%Y + DIFF_NN
							ENDIF
						ENDDO
! 						PRINT*, 'LF-2', PATCH, JJ, SUB_K(22,19)
						!-----------------Compute elements on interface FIJ---------------------
						DO I = 1, UBOUND(INDX1,1)
							DO J = 1, UBOUND(INDX1,1)
								CALL DR_FIND_GL_INDX_ALONG_INTERFACE_FIJ(GLOBAL_INDX, (/MASTER_PATCH, PATCH/), (/I,J/), INDX1)
								IF (GLOBAL_INDX(1).EQ.0 .OR. GLOBAL_INDX(2).EQ.0) THEN
								ELSE
			! 								PRINT*, 'HERE 2', GLOBAL_INDX
									DIFF_NN = DOT_PRODUCT(PRODUCT(RESHAPE((/SF1(:,I)%D00, WEIGHT(:)/), (/NUMGSPT, 2/), ORDER=ORDER1), 2), SF1(:,J)%D00)
									SUB_K(GLOBAL_INDX(1), GLOBAL_INDX(2)) = SUB_K(GLOBAL_INDX(1), GLOBAL_INDX(2)) + DIFF_NN
									SUB_K(GLOBAL_INDX(2), GLOBAL_INDX(1)) = SUB_K(GLOBAL_INDX(2), GLOBAL_INDX(1)) + DIFF_NN
								ENDIF
							ENDDO
						ENDDO
! 						PRINT*, 'LF-3', PATCH, JJ, SUB_K(22,19)
! 						READ(*,*)
					ENDDO
				ENDDO
			ENDIF
				
! 			PRINT*, 'LF', PATCH, JJ, SUB_K(22,19)
			
			IF (PATCH==1 .OR. PATCH==3) THEN
			!----------------------- RIGHT SIDE ON THE PARAMETER SPACE ------------------------!
				DO II=1, SUB_NUMLN
					SUB_LN = VEC2D(POINT2D(1.D0,IR_GRID(PATCH,2,JJ)+(II-1)*SUB_LN_LENGTH), POINT2D(1.D0,IR_GRID(PATCH,2,JJ)+II*SUB_LN_LENGTH))
					DIFF_NN = 0.D0
					CALL LEAST_SQUARE_LC_INT_II(SF1, INDX1, WEIGHT, EXACT_ON_BD, PATCH, SUB_LN, 'R')
					DO I=1, UBOUND(INDX1,1)
						DO J=1, UBOUND(INDX1,1)
							CALL DR_GL_INDX_FII(GLOBAL_INDX, PATCH, (/I,J/), INDX1)
							IF (GLOBAL_INDX(1).EQ.0 .OR. GLOBAL_INDX(2).EQ.0) THEN
							ELSE
								DIFF_NN = DOT_PRODUCT(PRODUCT(RESHAPE((/SF1(:,I)%D00, WEIGHT(:)/), (/NUMGSPT, 2/), ORDER=ORDER1), 2), SF1(:,J)%D00)
								SUB_K(GLOBAL_INDX(1), GLOBAL_INDX(2)) = SUB_K(GLOBAL_INDX(1), GLOBAL_INDX(2)) + DIFF_NN
							ENDIF
						ENDDO
						IF (GLOBAL_INDX(1).EQ.0) THEN
						ELSE
							DIFF_NN = DOT_PRODUCT(PRODUCT(RESHAPE((/SF1(:,I)%D00, WEIGHT(:)/), (/NUMGSPT, 2/), ORDER=ORDER1), 2), EXACT_ON_BD(:)%X)
							SUB_F(GLOBAL_INDX(1))%X = SUB_F(GLOBAL_INDX(1))%X + DIFF_NN
							DIFF_NN = DOT_PRODUCT(PRODUCT(RESHAPE((/SF1(:,I)%D00, WEIGHT(:)/), (/NUMGSPT, 2/), ORDER=ORDER1), 2), EXACT_ON_BD(:)%Y)
							SUB_F(GLOBAL_INDX(1))%Y = SUB_F(GLOBAL_INDX(1))%Y + DIFF_NN
						ENDIF
					ENDDO
					DO MASTER_PATCH = 1, PATCH-1
					!-----------------Compute elements on interface (i.e. FII)---------------------
						DO I = 1, UBOUND(INDX1,1)
							DO J = 1, UBOUND(INDX1,1)
								CALL DR_FIND_GL_INDX_ALONG_INTERFACE_FII(GLOBAL_INDX, (/MASTER_PATCH, PATCH/), (/I,J/), INDX1)
								IF (GLOBAL_INDX(1).EQ.0 .OR. GLOBAL_INDX(2).EQ.0) THEN
								ELSE
			! 								PRINT*, 'HERE 1', GLOBAL_INDX
									DIFF_NN = DOT_PRODUCT(PRODUCT(RESHAPE((/SF1(:,I)%D00, WEIGHT(:)/), (/NUMGSPT, 2/), ORDER=ORDER1), 2), SF1(:,J)%D00)
									SUB_K(GLOBAL_INDX(1), GLOBAL_INDX(2)) = SUB_K(GLOBAL_INDX(1), GLOBAL_INDX(2)) + DIFF_NN
								ENDIF
							ENDDO
							IF (GLOBAL_INDX(1).EQ.0) THEN
							ELSE
								DIFF_NN = DOT_PRODUCT(PRODUCT(RESHAPE((/SF1(:,I)%D00, WEIGHT(:)/), (/NUMGSPT, 2/), ORDER=ORDER1), 2), EXACT_ON_BD(:)%X)
								SUB_F(GLOBAL_INDX(1))%X = SUB_F(GLOBAL_INDX(1))%X + DIFF_NN
								DIFF_NN = DOT_PRODUCT(PRODUCT(RESHAPE((/SF1(:,I)%D00, WEIGHT(:)/), (/NUMGSPT, 2/), ORDER=ORDER1), 2), EXACT_ON_BD(:)%Y)
								SUB_F(GLOBAL_INDX(1))%Y = SUB_F(GLOBAL_INDX(1))%Y + DIFF_NN
							ENDIF
						ENDDO
						!-----------------Compute elements on interface FIJ---------------------
						DO I = 1, UBOUND(INDX1,1)
							DO J = 1, UBOUND(INDX1,1)
								CALL DR_FIND_GL_INDX_ALONG_INTERFACE_FIJ(GLOBAL_INDX, (/MASTER_PATCH, PATCH/), (/I,J/), INDX1)
								IF (GLOBAL_INDX(1).EQ.0 .OR. GLOBAL_INDX(2).EQ.0) THEN
								ELSE
			! 								PRINT*, 'HERE 2', GLOBAL_INDX
									DIFF_NN = DOT_PRODUCT(PRODUCT(RESHAPE((/SF1(:,I)%D00, WEIGHT(:)/), (/NUMGSPT, 2/), ORDER=ORDER1), 2), SF1(:,J)%D00)
									SUB_K(GLOBAL_INDX(1), GLOBAL_INDX(2)) = SUB_K(GLOBAL_INDX(1), GLOBAL_INDX(2)) + DIFF_NN
									SUB_K(GLOBAL_INDX(2), GLOBAL_INDX(1)) = SUB_K(GLOBAL_INDX(2), GLOBAL_INDX(1)) + DIFF_NN
								ENDIF
							ENDDO
						ENDDO
					ENDDO
				ENDDO
! 				PRINT*, 'RG', PATCH, JJ, SUB_K(22,19)
			ENDIF
		ENDDO
		
		DO JJ = 1, NUMIR(PATCH,1)-1
			SUB_LN_LENGTH = DABS(IR_GRID(PATCH,1,JJ+1) - IR_GRID(PATCH,1,JJ))/(1.D0*SUB_NUMLN)
			IF (PATCH==1 .OR. PATCH==3) THEN
			!----------------------- BOTTOM SIDE ON THE PARAMETER SPACE ------------------------!
				DO II=1, SUB_NUMLN
					SUB_LN = VEC2D(POINT2D(IR_GRID(PATCH,1,JJ)+(II-1)*SUB_LN_LENGTH,0.D0), POINT2D(IR_GRID(PATCH,1,JJ)+II*SUB_LN_LENGTH,0.D0))
					DIFF_NN = 0.D0
					CALL LEAST_SQUARE_LC_INT_II(SF1, INDX1, WEIGHT, EXACT_ON_BD, PATCH, SUB_LN, 'B')
					DO I=1, UBOUND(INDX1,1)
						DO J=1, UBOUND(INDX1,1)
							CALL DR_GL_INDX_FII(GLOBAL_INDX, PATCH, (/I,J/), INDX1)
							IF (GLOBAL_INDX(1).EQ.0 .OR. GLOBAL_INDX(2).EQ.0) THEN
							ELSE
								DIFF_NN = DOT_PRODUCT(PRODUCT(RESHAPE((/SF1(:,I)%D00, WEIGHT(:)/), (/NUMGSPT, 2/), ORDER=ORDER1), 2), SF1(:,J)%D00)
								SUB_K(GLOBAL_INDX(1), GLOBAL_INDX(2)) = SUB_K(GLOBAL_INDX(1), GLOBAL_INDX(2)) + DIFF_NN
							ENDIF
						ENDDO
						IF (GLOBAL_INDX(1).EQ.0) THEN
						ELSE
							DIFF_NN = DOT_PRODUCT(PRODUCT(RESHAPE((/SF1(:,I)%D00, WEIGHT(:)/), (/NUMGSPT, 2/), ORDER=ORDER1), 2), EXACT_ON_BD(:)%X)
							SUB_F(GLOBAL_INDX(1))%X = SUB_F(GLOBAL_INDX(1))%X + DIFF_NN
							DIFF_NN = DOT_PRODUCT(PRODUCT(RESHAPE((/SF1(:,I)%D00, WEIGHT(:)/), (/NUMGSPT, 2/), ORDER=ORDER1), 2), EXACT_ON_BD(:)%Y)
							SUB_F(GLOBAL_INDX(1))%Y = SUB_F(GLOBAL_INDX(1))%Y + DIFF_NN
						ENDIF
					ENDDO
					DO MASTER_PATCH = 1, PATCH-1
					!-----------------Compute elements on interface (i.e. FII)---------------------
						DO I = 1, UBOUND(INDX1,1)
							DO J = 1, UBOUND(INDX1,1)
								CALL DR_FIND_GL_INDX_ALONG_INTERFACE_FII(GLOBAL_INDX, (/MASTER_PATCH, PATCH/), (/I,J/), INDX1)
								IF (GLOBAL_INDX(1).EQ.0 .OR. GLOBAL_INDX(2).EQ.0) THEN
								ELSE
			! 								PRINT*, 'HERE 1', GLOBAL_INDX
									DIFF_NN = DOT_PRODUCT(PRODUCT(RESHAPE((/SF1(:,I)%D00, WEIGHT(:)/), (/NUMGSPT, 2/), ORDER=ORDER1), 2), SF1(:,J)%D00)
									SUB_K(GLOBAL_INDX(1), GLOBAL_INDX(2)) = SUB_K(GLOBAL_INDX(1), GLOBAL_INDX(2)) + DIFF_NN
								ENDIF
							ENDDO
							IF (GLOBAL_INDX(1).EQ.0) THEN
							ELSE
								DIFF_NN = DOT_PRODUCT(PRODUCT(RESHAPE((/SF1(:,I)%D00, WEIGHT(:)/), (/NUMGSPT, 2/), ORDER=ORDER1), 2), EXACT_ON_BD(:)%X)
								SUB_F(GLOBAL_INDX(1))%X = SUB_F(GLOBAL_INDX(1))%X + DIFF_NN
								DIFF_NN = DOT_PRODUCT(PRODUCT(RESHAPE((/SF1(:,I)%D00, WEIGHT(:)/), (/NUMGSPT, 2/), ORDER=ORDER1), 2), EXACT_ON_BD(:)%Y)
								SUB_F(GLOBAL_INDX(1))%Y = SUB_F(GLOBAL_INDX(1))%Y + DIFF_NN
							ENDIF
						ENDDO
! 						PRINT*, 'BT-1', MASTER_PATCH, PATCH, SUB_K(22,19)
						!-----------------Compute elements on interface FIJ---------------------
						DO I = 1, UBOUND(INDX1,1)
							DO J = 1, UBOUND(INDX1,1)
								CALL DR_FIND_GL_INDX_ALONG_INTERFACE_FIJ(GLOBAL_INDX, (/MASTER_PATCH, PATCH/), (/I,J/), INDX1)
								IF (GLOBAL_INDX(1).EQ.0 .OR. GLOBAL_INDX(2).EQ.0) THEN
								ELSE
			! 								PRINT*, 'HERE 2', GLOBAL_INDX
									DIFF_NN = DOT_PRODUCT(PRODUCT(RESHAPE((/SF1(:,I)%D00, WEIGHT(:)/), (/NUMGSPT, 2/), ORDER=ORDER1), 2), SF1(:,J)%D00)
									SUB_K(GLOBAL_INDX(1), GLOBAL_INDX(2)) = SUB_K(GLOBAL_INDX(1), GLOBAL_INDX(2)) + DIFF_NN
									SUB_K(GLOBAL_INDX(2), GLOBAL_INDX(1)) = SUB_K(GLOBAL_INDX(2), GLOBAL_INDX(1)) + DIFF_NN
								ENDIF
							ENDDO
						ENDDO
! 						PRINT*, 'BT-2', MASTER_PATCH, PATCH, SUB_K(22,19)
					ENDDO
				ENDDO
			ENDIF
			
! 			PRINT*, 'BT', PATCH, JJ, SUB_K(22,19)
			
			IF (PATCH==1 .OR. PATCH==2) THEN
			!----------------------- TOP SIDE ON THE PARAMETER SPACE ------------------------!
				DO II=1, SUB_NUMLN
					SUB_LN = VEC2D(POINT2D(IR_GRID(PATCH,1,JJ)+(II-1)*SUB_LN_LENGTH,1.D0), POINT2D(IR_GRID(PATCH,1,JJ)+II*SUB_LN_LENGTH,1.D0))
					DIFF_NN = 0.D0
					CALL LEAST_SQUARE_LC_INT_II(SF1, INDX1, WEIGHT, EXACT_ON_BD, PATCH, SUB_LN, 'T')
					DO I=1, UBOUND(INDX1,1)
						DO J=1, UBOUND(INDX1,1)
							CALL DR_GL_INDX_FII(GLOBAL_INDX, PATCH, (/I,J/), INDX1)
							IF (GLOBAL_INDX(1).EQ.0 .OR. GLOBAL_INDX(2).EQ.0) THEN
							ELSE
								DIFF_NN = DOT_PRODUCT(PRODUCT(RESHAPE((/SF1(:,I)%D00, WEIGHT(:)/), (/NUMGSPT, 2/), ORDER=ORDER1), 2), SF1(:,J)%D00)
								SUB_K(GLOBAL_INDX(1), GLOBAL_INDX(2)) = SUB_K(GLOBAL_INDX(1), GLOBAL_INDX(2)) + DIFF_NN
							ENDIF
						ENDDO
						IF (GLOBAL_INDX(1).EQ.0) THEN
						ELSE
							DIFF_NN = DOT_PRODUCT(PRODUCT(RESHAPE((/SF1(:,I)%D00, WEIGHT(:)/), (/NUMGSPT, 2/), ORDER=ORDER1), 2), EXACT_ON_BD(:)%X)
							SUB_F(GLOBAL_INDX(1))%X = SUB_F(GLOBAL_INDX(1))%X + DIFF_NN
							DIFF_NN = DOT_PRODUCT(PRODUCT(RESHAPE((/SF1(:,I)%D00, WEIGHT(:)/), (/NUMGSPT, 2/), ORDER=ORDER1), 2), EXACT_ON_BD(:)%Y)
							SUB_F(GLOBAL_INDX(1))%Y = SUB_F(GLOBAL_INDX(1))%Y + DIFF_NN
						ENDIF
					ENDDO
					DO MASTER_PATCH = 1, PATCH-1
					!-----------------Compute elements on interface (i.e. FII)---------------------
						DO I = 1, UBOUND(INDX1,1)
							DO J = 1, UBOUND(INDX1,1)
								CALL DR_FIND_GL_INDX_ALONG_INTERFACE_FII(GLOBAL_INDX, (/MASTER_PATCH, PATCH/), (/I,J/), INDX1)
								IF (GLOBAL_INDX(1).EQ.0 .OR. GLOBAL_INDX(2).EQ.0) THEN
								ELSE
			! 								PRINT*, 'HERE 1', GLOBAL_INDX
									DIFF_NN = DOT_PRODUCT(PRODUCT(RESHAPE((/SF1(:,I)%D00, WEIGHT(:)/), (/NUMGSPT, 2/), ORDER=ORDER1), 2), SF1(:,J)%D00)
									SUB_K(GLOBAL_INDX(1), GLOBAL_INDX(2)) = SUB_K(GLOBAL_INDX(1), GLOBAL_INDX(2)) + DIFF_NN
								ENDIF
							ENDDO
							IF (GLOBAL_INDX(1).EQ.0) THEN
							ELSE
								DIFF_NN = DOT_PRODUCT(PRODUCT(RESHAPE((/SF1(:,I)%D00, WEIGHT(:)/), (/NUMGSPT, 2/), ORDER=ORDER1), 2), EXACT_ON_BD(:)%X)
								SUB_F(GLOBAL_INDX(1))%X = SUB_F(GLOBAL_INDX(1))%X + DIFF_NN
								DIFF_NN = DOT_PRODUCT(PRODUCT(RESHAPE((/SF1(:,I)%D00, WEIGHT(:)/), (/NUMGSPT, 2/), ORDER=ORDER1), 2), EXACT_ON_BD(:)%Y)
								SUB_F(GLOBAL_INDX(1))%Y = SUB_F(GLOBAL_INDX(1))%Y + DIFF_NN
							ENDIF
						ENDDO
						!-----------------Compute elements on interface FIJ---------------------
						DO I = 1, UBOUND(INDX1,1)
							DO J = 1, UBOUND(INDX1,1)
								CALL DR_FIND_GL_INDX_ALONG_INTERFACE_FIJ(GLOBAL_INDX, (/MASTER_PATCH, PATCH/), (/I,J/), INDX1)
								IF (GLOBAL_INDX(1).EQ.0 .OR. GLOBAL_INDX(2).EQ.0) THEN
								ELSE
			! 								PRINT*, 'HERE 2', GLOBAL_INDX
									DIFF_NN = DOT_PRODUCT(PRODUCT(RESHAPE((/SF1(:,I)%D00, WEIGHT(:)/), (/NUMGSPT, 2/), ORDER=ORDER1), 2), SF1(:,J)%D00)
									SUB_K(GLOBAL_INDX(1), GLOBAL_INDX(2)) = SUB_K(GLOBAL_INDX(1), GLOBAL_INDX(2)) + DIFF_NN
									SUB_K(GLOBAL_INDX(2), GLOBAL_INDX(1)) = SUB_K(GLOBAL_INDX(2), GLOBAL_INDX(1)) + DIFF_NN
								ENDIF
							ENDDO
						ENDDO
					ENDDO
				ENDDO
! 				PRINT*, 'TP', PATCH, JJ, SUB_K(22,19)
			ENDIF
		ENDDO
		DEALLOCATE(SF1, INDX1)
	ENDDO
	
END SUBROUTINE GEN_BD_LN

!! Compute line integration on Neumann boundary
SUBROUTINE IMPOSE_NEUMANN_BD(STIF_F)

	REAL*8, INTENT(INOUT) :: STIF_F(2*DOF)
	
	INTEGER :: I, J
	TYPE(POINT2D) :: LN_INT

	DO J=1, NM_NUMBD
		DO I=1, NM_BDNDX(J,1)%LC_NUM
			CALL NEUMANN_LN_INT(LN_INT, NM_BDNDX(J,I), J)
! 			print*, j, i, nm_bdndx(j,i)%patch_ndx, nm_bdndx(j,i)%lc_ndx
! 			IF (NM_BDNDX(J,I)%GL_NDX==2) THEN
! 				PRINT*, NM_BDNDX(J,I)%GL_NDX, LN_INT
! 			ENDIF
			STIF_F(NM_BDNDX(J,I)%GL_NDX) = STIF_F(NM_BDNDX(J,I)%GL_NDX) + LN_INT%X
			STIF_F(DOF + NM_BDNDX(J,I)%GL_NDX) = STIF_F(DOF + NM_BDNDX(J,I)%GL_NDX) + LN_INT%Y
		ENDDO
	ENDDO

END SUBROUTINE IMPOSE_NEUMANN_BD

!! Compute line integration on Neumann boundary
SUBROUTINE NEUMANN_LN_INT(LN_INT, NM_INFO, GAMMA)

	TYPE(POINT2D), INTENT(OUT) :: LN_INT
	TYPE(BD_INFO), INTENT(IN) :: NM_INFO
	INTEGER, INTENT(IN) :: GAMMA
	
	TYPE(MATRIX_22) :: JACOB
	TYPE(FVALUE) :: DIFF_NURBS
	TYPE(POINT2D) :: GSPT, TRC(1)
	REAL*8 :: DET_M, GS(NUMGSPT), GSW(NUMGSPT)
	INTEGER :: I, J, K, II, JJ, KK, IX, IY, PATCH
	
	LN_INT = POINT2D(0.D0, 0.D0)
	
	PATCH = NM_INFO%PATCH_NDX
	
	IX = NM_INFO%LC_NDX(1)
	IY = NM_INFO%LC_NDX(2)
	
	IF  (GAMMA==1 .OR. GAMMA==5) THEN
		DO II = 1, NUMIR(PATCH, 1)-1
			CALL GAULEG(IR_GRID(PATCH, 1, II), IR_GRID(PATCH, 1, II+1), GS, GSW, NUMGSPT)
			DO I = 1, NUMGSPT
				GSPT = POINT2D(GS(I),1.D0)
				
				DET_M = GET_DET_LN(GSPT, GAMMA, PATCH)
! 				print*, 'here1'
				JACOB = GET_JACOBIAN_MATRIX(GSPT, PATCH)
! 				print*, 'here2'
				DIFF_NURBS = GET_PHY_NURBS_SURFACE_2D(GSPT, IX, IY, JACOB, PATCH)
! 				print*, 'here3'
				CALL TRACTION(TRC, (/GSPT/), PATCH, GAMMA)
! 				print*, 'here4'
				LN_INT%X = LN_INT%X + DIFF_NURBS%D00*TRC(1)%X*DET_M*GSW(I)
				LN_INT%Y = LN_INT%Y + DIFF_NURBS%D00*TRC(1)%Y*DET_M*GSW(I)
			ENDDO
		ENDDO
! 		IF (NM_INFO%GL_NDX==2) THEN
! 			PRINT*, 'LN_INT-1', LN_INT
! 		ENDIF
	ELSEIF (GAMMA==3 .OR. GAMMA==7) THEN
		DO II = 1, NUMIR(PATCH, 1)-1
			CALL GAULEG(IR_GRID(PATCH, 1, II), IR_GRID(PATCH, 1, II+1), GS, GSW, NUMGSPT)
			DO I = 1, NUMGSPT
				GSPT = POINT2D(GS(I),0.D0)
				
				DET_M = GET_DET_LN(GSPT, GAMMA, PATCH)
		
				JACOB = GET_JACOBIAN_MATRIX(GSPT,PATCH)
		
				DIFF_NURBS = GET_PHY_NURBS_SURFACE_2D(GSPT, IX, IY, JACOB, PATCH)
		
				CALL TRACTION(TRC, (/GSPT/), PATCH, GAMMA)
		
				LN_INT%X = LN_INT%X + DIFF_NURBS%D00*TRC(1)%X*DET_M*GSW(I)
				LN_INT%Y = LN_INT%Y + DIFF_NURBS%D00*TRC(1)%Y*DET_M*GSW(I)
				
! 				IF (NM_INFO%GL_NDX==2) THEN
! 					PRINT*, 'GSPT', GSPT
! 					PRINT*, 'DET_M', DET_M
! 					PRINT*, 'DIFF_NURBS', DIFF_NURBS%D00
! 					PRINT*, 'TRC', TRC(1)
! 					PRINT*, 'GSW', GSW(I)
! 					PRINT*, 'LN_INT', LN_INT
! 					PRINT*, '------------------------------------------------'
! 				ENDIF
			ENDDO
		ENDDO
		
! 		IF (NM_INFO%GL_NDX==2) THEN
! 			PRINT*, 'LN_INT-2', LN_INT
! 		ENDIF
		
	ELSEIF (GAMMA==2 .OR. GAMMA==6) THEN
		DO II = 1, NUMIR(PATCH, 2)-1
			CALL GAULEG(IR_GRID(PATCH, 2, II), IR_GRID(PATCH, 2, II+1), GS, GSW, NUMGSPT)
			DO I = 1, NUMGSPT
				GSPT = POINT2D(0.D0, GS(I))
				
				DET_M = GET_DET_LN(GSPT, GAMMA, PATCH)
		
				JACOB = GET_JACOBIAN_MATRIX(GSPT,PATCH)
		
				DIFF_NURBS = GET_PHY_NURBS_SURFACE_2D(GSPT, IX, IY, JACOB, PATCH)
		
				CALL TRACTION(TRC, (/GSPT/), PATCH, GAMMA)
		
				LN_INT%X = LN_INT%X + DIFF_NURBS%D00*TRC(1)%X*DET_M*GSW(I)
				LN_INT%Y = LN_INT%Y + DIFF_NURBS%D00*TRC(1)%Y*DET_M*GSW(I)
			ENDDO
		ENDDO
! 		IF (NM_INFO%GL_NDX==2) THEN
! 			PRINT*, 'LN_INT-3', LN_INT
! 		ENDIF
	ELSEIF (GAMMA==4) THEN
		DO II = 1, NUMIR(PATCH, 2)-1
			CALL GAULEG(IR_GRID(PATCH, 2, II), IR_GRID(PATCH, 2, II+1), GS, GSW, NUMGSPT)
			DO I = 1, NUMGSPT
				GSPT = POINT2D(1.D0, GS(I))
				
				DET_M = GET_DET_LN(GSPT, GAMMA, PATCH)
		
				JACOB = GET_JACOBIAN_MATRIX(GSPT,PATCH)
		
				DIFF_NURBS = GET_PHY_NURBS_SURFACE_2D(GSPT, IX, IY, JACOB, PATCH)
		
				CALL TRACTION(TRC, (/GSPT/), PATCH, GAMMA)
		
				LN_INT%X = LN_INT%X + DIFF_NURBS%D00*TRC(1)%X*DET_M*GSW(I)
				LN_INT%Y = LN_INT%Y + DIFF_NURBS%D00*TRC(1)%Y*DET_M*GSW(I)
			ENDDO
		ENDDO
! 		IF (NM_INFO%GL_NDX==2) THEN
! 			PRINT*, 'LN_INT-4', LN_INT
! 		ENDIF
	ENDIF
! 		IF (NM_INFO%GL_NDX==2) THEN
! 			PRINT*, 'LN_INT-5', LN_INT
! 		ENDIF
	!! Compute line integration of NURBS basis functions on interface
	IF (NM_INFO%INTERFACE_LG) THEN
		IF (NM_INFO%SLAVE_GAMMA==3) THEN
			DO II = 1, NUMIR(NM_INFO%SLAVE_PATCH_NDX, 1)-1
				CALL GAULEG(IR_GRID(NM_INFO%SLAVE_PATCH_NDX, 1, II), IR_GRID(NM_INFO%SLAVE_PATCH_NDX, 1, II+1), GS, GSW, NUMGSPT)
				DO I = 1, NUMGSPT
					GSPT = POINT2D(GS(I), 0.D0)
					
					DET_M = GET_DET_LN(GSPT, NM_INFO%SLAVE_GAMMA, NM_INFO%SLAVE_PATCH_NDX)
			
					JACOB = GET_JACOBIAN_MATRIX(GSPT, NM_INFO%SLAVE_PATCH_NDX)
			
					DIFF_NURBS = GET_PHY_NURBS_SURFACE_2D(GSPT, NM_INFO%LC_INTERFACE_NDX(1), NM_INFO%LC_INTERFACE_NDX(2), JACOB, NM_INFO%SLAVE_PATCH_NDX)
			
					CALL TRACTION(TRC, (/GSPT/), NM_INFO%SLAVE_PATCH_NDX, NM_INFO%SLAVE_GAMMA)
			
					LN_INT%X = LN_INT%X + DIFF_NURBS%D00*TRC(1)%X*DET_M*GSW(I)
					LN_INT%Y = LN_INT%Y + DIFF_NURBS%D00*TRC(1)%Y*DET_M*GSW(I)
				ENDDO
			ENDDO
! 			IF (NM_INFO%GL_NDX==2) THEN
! 				PRINT*, 'LN_INT-6', LN_INT
! 			ENDIF
		ELSEIF (NM_INFO%SLAVE_GAMMA==4) THEN
			DO II = 1, NUMIR(NM_INFO%SLAVE_PATCH_NDX, 2)-1
				CALL GAULEG(IR_GRID(NM_INFO%SLAVE_PATCH_NDX, 2, II), IR_GRID(NM_INFO%SLAVE_PATCH_NDX, 2, II+1), GS, GSW, NUMGSPT)
				DO I = 1, NUMGSPT
					GSPT = POINT2D(1.D0, GS(I))
					
					DET_M = GET_DET_LN(GSPT, NM_INFO%SLAVE_GAMMA, NM_INFO%SLAVE_PATCH_NDX)
			
					JACOB = GET_JACOBIAN_MATRIX(GSPT, NM_INFO%SLAVE_PATCH_NDX)
			
					DIFF_NURBS = GET_PHY_NURBS_SURFACE_2D(GSPT, NM_INFO%LC_INTERFACE_NDX(1), NM_INFO%LC_INTERFACE_NDX(2), JACOB, NM_INFO%SLAVE_PATCH_NDX)
			
					CALL TRACTION(TRC, (/GSPT/), NM_INFO%SLAVE_PATCH_NDX, NM_INFO%SLAVE_GAMMA)
			
					LN_INT%X = LN_INT%X + DIFF_NURBS%D00*TRC(1)%X*DET_M*GSW(I)
					LN_INT%Y = LN_INT%Y + DIFF_NURBS%D00*TRC(1)%Y*DET_M*GSW(I)
				ENDDO
			ENDDO
! 			IF (NM_INFO%GL_NDX==2) THEN
! 				PRINT*, 'LN_INT-7', LN_INT
! 			ENDIF
		ELSEIF (NM_INFO%SLAVE_GAMMA==5) THEN
			DO II = 1, NUMIR(NM_INFO%SLAVE_PATCH_NDX, 1)-1
				CALL GAULEG(IR_GRID(NM_INFO%SLAVE_PATCH_NDX, 1, II), IR_GRID(NM_INFO%SLAVE_PATCH_NDX, 1, II+1), GS, GSW, NUMGSPT)
				DO I = 1, NUMGSPT
					GSPT = POINT2D(GS(I), 1.D0)
					
					DET_M = GET_DET_LN(GSPT, NM_INFO%SLAVE_GAMMA, NM_INFO%SLAVE_PATCH_NDX)
			
					JACOB = GET_JACOBIAN_MATRIX(GSPT, NM_INFO%SLAVE_PATCH_NDX)
			
					DIFF_NURBS = GET_PHY_NURBS_SURFACE_2D(GSPT, NM_INFO%LC_INTERFACE_NDX(1), NM_INFO%LC_INTERFACE_NDX(2), JACOB, NM_INFO%SLAVE_PATCH_NDX)
			
					CALL TRACTION(TRC, (/GSPT/), NM_INFO%SLAVE_PATCH_NDX, NM_INFO%SLAVE_GAMMA)
			
					LN_INT%X = LN_INT%X + DIFF_NURBS%D00*TRC(1)%X*DET_M*GSW(I)
					LN_INT%Y = LN_INT%Y + DIFF_NURBS%D00*TRC(1)%Y*DET_M*GSW(I)
				ENDDO
			ENDDO
! 			IF (NM_INFO%GL_NDX==2) THEN
! 				PRINT*, 'LN_INT-8', LN_INT
! 			ENDIF
		ELSEIF (NM_INFO%SLAVE_GAMMA==7) THEN
			DO II = 1, NUMIR(NM_INFO%SLAVE_PATCH_NDX, 1)-1
				CALL GAULEG(IR_GRID(NM_INFO%SLAVE_PATCH_NDX, 1, II), IR_GRID(NM_INFO%SLAVE_PATCH_NDX, 1, II+1), GS, GSW, NUMGSPT)
				DO I = 1, NUMGSPT
					GSPT = POINT2D(GS(I), 0.D0)
					
					DET_M = GET_DET_LN(GSPT, NM_INFO%SLAVE_GAMMA, NM_INFO%SLAVE_PATCH_NDX)
			
					JACOB = GET_JACOBIAN_MATRIX(GSPT, NM_INFO%SLAVE_PATCH_NDX)
			
					DIFF_NURBS = GET_PHY_NURBS_SURFACE_2D(GSPT, NM_INFO%LC_INTERFACE_NDX(1), NM_INFO%LC_INTERFACE_NDX(2), JACOB, NM_INFO%SLAVE_PATCH_NDX)
			
					CALL TRACTION(TRC, (/GSPT/), NM_INFO%SLAVE_PATCH_NDX, NM_INFO%SLAVE_GAMMA)
			
					LN_INT%X = LN_INT%X + DIFF_NURBS%D00*TRC(1)%X*DET_M*GSW(I)
					LN_INT%Y = LN_INT%Y + DIFF_NURBS%D00*TRC(1)%Y*DET_M*GSW(I)
				ENDDO
			ENDDO
! 			IF (NM_INFO%GL_NDX==2) THEN
! 				PRINT*, 'LN_INT-9', LN_INT
! 			ENDIF
		ELSE
			PRINT*, 'ERROR - NEUMANN_LN_INT : "NM_INFO%SLAVE_GAMMA" IS NOT SET COMPLETELY!'
			STOP
		ENDIF
	ENDIF
	
END SUBROUTINE NEUMANN_LN_INT

SUBROUTINE STIF_LC_INT_II(SF, WEIGHT, LOAD_F, INDX, PATCH, NUMIR_INDX)
	INTEGER, INTENT(IN) :: NUMIR_INDX(2), PATCH
	TYPE(FVALUE), INTENT(OUT) :: SF(NUMGSPT**2, (BASIS_KVEC(PATCH,1)%POLY_ORDER+1)*(BASIS_KVEC(PATCH,2)%POLY_ORDER+1))
	TYPE(INT2D), INTENT(OUT) :: INDX((BASIS_KVEC(PATCH,1)%POLY_ORDER+1)*(BASIS_KVEC(PATCH,2)%POLY_ORDER+1))
	REAL*8, INTENT(OUT) :: WEIGHT(NUMGSPT**2)
	TYPE(POINT2D), INTENT(OUT) :: LOAD_F(NUMGSPT**2)
	
	TYPE(RECPATCH) :: IRBOX
	TYPE(POINT2D) :: GSPT, DMY_GSPT
	TYPE(MATRIX_22) :: JACOB
	INTEGER :: I,J, K, II, JJ, KK
	REAL*8 :: DET_M

	IRBOX%PT1 = POINT2D(IR_GRID(PATCH,1,NUMIR_INDX(1)), IR_GRID(PATCH,2,NUMIR_INDX(2)))
	IRBOX%PT2 = POINT2D(IR_GRID(PATCH,1,NUMIR_INDX(1)+1), IR_GRID(PATCH,2,NUMIR_INDX(2)))
	IRBOX%PT3 = POINT2D(IR_GRID(PATCH,1,NUMIR_INDX(1)+1), IR_GRID(PATCH,2,NUMIR_INDX(2)+1))
	IRBOX%PT4 = POINT2D(IR_GRID(PATCH,1,NUMIR_INDX(1)), IR_GRID(PATCH,2,NUMIR_INDX(2)+1))

	!------------------! VECTORIZE GAUSS POINTS AND WEIGHTS------------------------------
	CALL GAULEG(IRBOX%PT1%X, IRBOX%PT2%X, GSX, GSXW, NUMGSPT)
	CALL GAULEG(IRBOX%PT1%Y, IRBOX%PT4%Y, GSY, GSYW, NUMGSPT)
	
	KK=0
	DO I=1,NUMGSPT
		DO J=1,NUMGSPT
! 			PRINT*, I, J
			KK=KK+1
			GSPT = POINT2D(GSX(I), GSY(J))
			DMY_GSPT = GSPT
			JACOB = GET_JACOBIAN_MATRIX(GSPT,PATCH)
			DET_M = .DETERMINANT.JACOB
! 			PRINT*, DET_M
			WEIGHT(KK) = DET_M*GSXW(I)*GSYW(J)
! 			PRINT*, WEIGHT(KK)
			LOAD_F(KK) = LDFT2D(DMY_GSPT,PATCH)
! 			IF (PATCH.LE.NUM_IGA_PATCH) THEN
				CALL GET_ALL_PHY_NURBS_SURFACE_2D(SF(KK,:), INDX(:), DMY_GSPT, JACOB, PATCH)
! 			ELSE
! 				CALL GET_ALL_PHY_BASIS_IN_INT(SF(KK,:), INDX(:), DMY_GSPT, JACOB, PATCH)
! 			ENDIF
		ENDDO
	ENDDO
	
! 	PRINT*, 'STIF_LC_INT_II - DONE'
	
END SUBROUTINE STIF_LC_INT_II

SUBROUTINE STIF_LC_INT_IJ(SF1, SF2, INDX1, INDX2, WEIGHT, PATCHES, NUMIR_INDX)

	INTEGER, INTENT(IN) :: NUMIR_INDX(2), PATCHES(2) ! PATCHES(1) = IGA_PATCH,	PATCHES(2) = EGM_PATCH
	TYPE(FVALUE), INTENT(OUT) :: SF1(NUMGSPT**2, (BASIS_KVEC(PATCHES(1),1)%POLY_ORDER+1)*(BASIS_KVEC(PATCHES(1),2)%POLY_ORDER+1))
	TYPE(FVALUE), INTENT(OUT) :: SF2(NUMGSPT**2, (BASIS_KVEC(PATCHES(2),1)%POLY_ORDER+1)*(BASIS_KVEC(PATCHES(2),2)%POLY_ORDER+1))
	TYPE(INT2D), INTENT(OUT) :: INDX1((BASIS_KVEC(PATCHES(1),1)%POLY_ORDER+1)*(BASIS_KVEC(PATCHES(1),2)%POLY_ORDER+1))
	TYPE(INT2D), INTENT(OUT) :: INDX2((BASIS_KVEC(PATCHES(2),1)%POLY_ORDER+1)*(BASIS_KVEC(PATCHES(2),2)%POLY_ORDER+1))
	REAL*8, INTENT(OUT) :: WEIGHT(NUMGSPT**2)
	
	TYPE(RECPATCH) :: IRBOX
	TYPE(POINT2D) :: GSPT, DMY_GSPT, PHYPT_F, INV_PHYPT_G
	TYPE(MATRIX_22) :: JACOB_F, JACOB_G
	INTEGER :: I,J, K, II, JJ, KK
	REAL*8 :: DET_JF
	
	SF1(:,:) = FVALUE(0.D0,0.D0,0.D0,0.D0,0.D0,0.D0)
	SF2(:,:) = FVALUE(0.D0,0.D0,0.D0,0.D0,0.D0,0.D0)
	
	IRBOX%PT1 = POINT2D(IR_GRID(PATCHES(2),1,NUMIR_INDX(1)), IR_GRID(PATCHES(2),2,NUMIR_INDX(2)))
	IRBOX%PT2 = POINT2D(IR_GRID(PATCHES(2),1,NUMIR_INDX(1)+1), IR_GRID(PATCHES(2),2,NUMIR_INDX(2)))
	IRBOX%PT3 = POINT2D(IR_GRID(PATCHES(2),1,NUMIR_INDX(1)+1), IR_GRID(PATCHES(2),2,NUMIR_INDX(2)+1))
	IRBOX%PT4 = POINT2D(IR_GRID(PATCHES(2),1,NUMIR_INDX(1)), IR_GRID(PATCHES(2),2,NUMIR_INDX(2)+1))
	
	!------------------! VECTORIZE GAUSS POINTS AND WEIGHTS------------------------------
	CALL GAULEG(IRBOX%PT1%X, IRBOX%PT2%X, GSX, GSXW, NUMGSPT)
	CALL GAULEG(IRBOX%PT1%Y, IRBOX%PT4%Y, GSY, GSYW, NUMGSPT)
	
	KK=0
	DO I=1,NUMGSPT
		DO J=1,NUMGSPT
			KK=KK+1
! 			PRINT*, I, J
			GSPT = POINT2D(GSX(I), GSY(J))
			DMY_GSPT = GSPT
			PHYPT_F = GET_PHY_PT(DMY_GSPT,PATCHES(2))
! 			PRINT*, PHYPT_F
			IGA_PATCH = GET_IGA_PATCH_INDX(PHYPT_F)
			
			IF (IGA_PATCH==PATCHES(1)) THEN
				INV_PHYPT_G = GET_REF_PT(PHYPT_F,PATCHES(1))
				
	! 			PRINT*, INV_PHYPT_G
				
				JACOB_F = GET_JACOBIAN_MATRIX(DMY_GSPT,PATCHES(2))
				JACOB_G = GET_JACOBIAN_MATRIX(INV_PHYPT_G,PATCHES(1))
				
				DET_JF = .DETERMINANT.JACOB_F
				WEIGHT(KK) = DET_JF*GSXW(I)*GSYW(J)
	! 			PRINT*, 'STIF_LC_INT_IN - HERE0'
				CALL GET_ALL_PHY_NURBS_SURFACE_2D(SF1(KK,:), INDX1(:), INV_PHYPT_G, JACOB_G, PATCHES(1))
	! 			PRINT*, 'STIF_LC_INT_IN - HERE1'
				CALL GET_ALL_PHY_BASIS_IN_INT(SF2(KK,:), INDX2(:), DMY_GSPT, JACOB_F, PATCHES(2))
	! 			PRINT*, 'STIF_LC_INT_IN - HERE2'
			ELSE
				GOTO 10
			ENDIF
		ENDDO
	ENDDO
	
	10 CONTINUE
	
! 	PRINT*, 'STIF_LC_INT_IJ - DONE'
	
END SUBROUTINE STIF_LC_INT_IJ

SUBROUTINE STIF_FIND_GLOBAL_INDX_FII(GLOBAL_INDX, PATCH, LOCAL_INDX, INDX)
	INTEGER, INTENT(IN) :: PATCH, LOCAL_INDX(2)
	TYPE(INT2D), INTENT(IN) :: INDX((BASIS_KVEC(PATCH,1)%POLY_ORDER+1)*(BASIS_KVEC(PATCH,2)%POLY_ORDER+1))
	INTEGER, INTENT(OUT) :: GLOBAL_INDX(2)
	
	INTEGER :: I, J, K, II, JJ, KK, LOCAL_DOF_SUM
	
	IF (PATCH.EQ.1) THEN
		LOCAL_DOF_SUM = 0
	ELSE
		LOCAL_DOF_SUM = SUM(LOCAL_DOF(1:PATCH-1))
	ENDIF

	DO I = 1, 2
		DO KK=1, LOCAL_DOF(PATCH)
			IF (NDX(1,LOCAL_DOF_SUM + KK).EQ.INDX(LOCAL_INDX(I))%A .AND. NDX(2,LOCAL_DOF_SUM + KK).EQ.INDX(LOCAL_INDX(I))%B) THEN
				GLOBAL_INDX(I) = LOCAL_DOF_SUM + KK
				GOTO 10
			ELSE
				GLOBAL_INDX(I) = 0
			ENDIF
		ENDDO
		10 CONTINUE
	ENDDO
	
END SUBROUTINE STIF_FIND_GLOBAL_INDX_FII

SUBROUTINE STIF_FIND_GLOBAL_INDX_FIJ(GLOBAL_INDX, PATCHES, LOCAL_INDX, INDX1, INDX2)
	INTEGER, INTENT(IN) :: PATCHES(2), LOCAL_INDX(2) ! PATCHES(1) = IGA PATCH,  PATCHES(2) = EGM PATCH
	TYPE(INT2D), INTENT(IN) :: INDX1((BASIS_KVEC(PATCHES(1),1)%POLY_ORDER+1)*(BASIS_KVEC(PATCHES(1),2)%POLY_ORDER+1))
	TYPE(INT2D), INTENT(IN) :: INDX2((BASIS_KVEC(PATCHES(2),1)%POLY_ORDER+1)*(BASIS_KVEC(PATCHES(2),2)%POLY_ORDER+1))
	INTEGER, INTENT(OUT) :: GLOBAL_INDX(2)
	
	INTEGER :: I, J, K, II, JJ, KK, LOCAL_DOF_SUM(2)
	
	DO I = 1, 2
		IF (PATCHES(I).EQ.1) THEN
			LOCAL_DOF_SUM(I) = 0
		ELSE
			LOCAL_DOF_SUM(I) = SUM(LOCAL_DOF(1:PATCHES(I)-1))
		ENDIF
	ENDDO
	
	GLOBAL_INDX(:) = 0
	
	DO KK=1, LOCAL_DOF(PATCHES(1))
		IF (NDX(1,LOCAL_DOF_SUM(1) + KK).EQ.INDX1(LOCAL_INDX(1))%A .AND. NDX(2,LOCAL_DOF_SUM(1) + KK).EQ.INDX1(LOCAL_INDX(1))%B) THEN
			GLOBAL_INDX(1) = LOCAL_DOF_SUM(1) + KK
			GOTO 10
		ELSE
			GLOBAL_INDX(1) = 0
		ENDIF
	ENDDO
	10 CONTINUE

	DO KK=1, LOCAL_DOF(PATCHES(2))
		IF (NDX(1,LOCAL_DOF_SUM(2) + KK).EQ.INDX2(LOCAL_INDX(2))%A .AND. NDX(2,LOCAL_DOF_SUM(2) + KK).EQ.INDX2(LOCAL_INDX(2))%B) THEN
			GLOBAL_INDX(2) = LOCAL_DOF_SUM(2) + KK
			GOTO 20
		ELSE
			GLOBAL_INDX(2) = 0
		ENDIF
	ENDDO
	20 CONTINUE
	
END SUBROUTINE STIF_FIND_GLOBAL_INDX_FIJ

SUBROUTINE STIF_FIND_GLOBAL_INDX_ALONG_INTERFACE_FII(GLOBAL_INDX, PATCH, LOCAL_INDX, INDX)
	INTEGER, INTENT(OUT) :: GLOBAL_INDX(6)
	INTEGER, INTENT(IN) :: PATCH(2), LOCAL_INDX(2)	! PATCH(1) = MASTER_PATCH, PATCH(2) = SLAVE_PATCH
	TYPE(INT2D), INTENT(IN) :: INDX((BASIS_KVEC(PATCH(2),1)%POLY_ORDER+1)*(BASIS_KVEC(PATCH(2),2)%POLY_ORDER+1))
	
	INTEGER :: I, J, K, II, JJ, KK, GL_INDX_TO_SLAVE_PATCH_NDX(6)
	
	GLOBAL_INDX(:) = 0
	GL_INDX_TO_SLAVE_PATCH_NDX = (/1, 1, 2, 2, 3, 3/)
	
	DO I = 1, UBOUND(GLOBAL_INDX,1)
		IF (MOD(I,2)==0) THEN
			DO KK=1, UBOUND(INTERFACE_NDX,1)
				IF (INTERFACE_NDX(KK)%MASTER_PATCH_NDX.EQ.PATCH(1) .AND. INTERFACE_NDX(KK)%SLAVE_PATCH_NDX(GL_INDX_TO_SLAVE_PATCH_NDX(I)).EQ.PATCH(2) .AND. &
						INTERFACE_NDX(KK)%LC_NDX(I+1).EQ.INDX(LOCAL_INDX(2))%A .AND. INTERFACE_NDX(KK)%LC_NDX(I+2).EQ.INDX(LOCAL_INDX(2))%B) THEN
					GLOBAL_INDX(I) = INTERFACE_NDX(KK)%GL_NDX
					GOTO 10
				ELSE
				GLOBAL_INDX(I) = 0
				ENDIF
			ENDDO
		ELSE
			DO KK=1, UBOUND(INTERFACE_NDX,1)
				IF (INTERFACE_NDX(KK)%MASTER_PATCH_NDX.EQ.PATCH(1) .AND. INTERFACE_NDX(KK)%SLAVE_PATCH_NDX(GL_INDX_TO_SLAVE_PATCH_NDX(I)).EQ.PATCH(2) .AND. &
						INTERFACE_NDX(KK)%LC_NDX(I+2).EQ.INDX(LOCAL_INDX(1))%A .AND. INTERFACE_NDX(KK)%LC_NDX(I+3).EQ.INDX(LOCAL_INDX(1))%B) THEN
					GLOBAL_INDX(I) = INTERFACE_NDX(KK)%GL_NDX
					GOTO 20
				ELSE
					GLOBAL_INDX(I) = 0
				ENDIF
			ENDDO
		ENDIF
		10 CONTINUE
		20 CONTINUE
	ENDDO

END SUBROUTINE STIF_FIND_GLOBAL_INDX_ALONG_INTERFACE_FII

SUBROUTINE STIF_FIND_GLOBAL_INDX_ALONG_INTERFACE_FIJ(GLOBAL_INDX, PATCH, LOCAL_INDX, INDX)
	INTEGER, INTENT(OUT) :: GLOBAL_INDX(6)
	INTEGER, INTENT(IN) :: PATCH(2), LOCAL_INDX(2)	! PATCH(1) = MASTER_PATCH, PATCH(2) = SLAVE_PATCH
	TYPE(INT2D), INTENT(IN) :: INDX((BASIS_KVEC(PATCH(2),1)%POLY_ORDER+1)*(BASIS_KVEC(PATCH(2),2)%POLY_ORDER+1))
	
	INTEGER :: I, J, K, II, JJ, KK
	
	GLOBAL_INDX(:) = 0

	DO KK=1, UBOUND(INTERFACE_NDX,1)
		IF (INTERFACE_NDX(KK)%MASTER_PATCH_NDX.EQ.PATCH(1) .AND. INTERFACE_NDX(KK)%SLAVE_PATCH_NDX(2).EQ.PATCH(2) .AND. &
				INTERFACE_NDX(KK)%LC_NDX(5).EQ.INDX(LOCAL_INDX(1))%A .AND. INTERFACE_NDX(KK)%LC_NDX(6).EQ.INDX(LOCAL_INDX(1))%B) THEN
			GLOBAL_INDX(1) = INTERFACE_NDX(KK)%GL_NDX
			GOTO 10
		ELSE
			GLOBAL_INDX(1) = 0
		ENDIF
	ENDDO
	10 CONTINUE

	IF (GLOBAL_INDX(1).EQ.0) THEN
		GLOBAL_INDX(2) = 0
	ELSE
		DO KK=1, UBOUND(INTERFACE_NDX,1)
			IF (INTERFACE_NDX(KK)%MASTER_PATCH_NDX.EQ.PATCH(1) .AND. INTERFACE_NDX(KK)%SLAVE_PATCH_NDX(1).EQ.PATCH(2) .AND. &
					INTERFACE_NDX(KK)%LC_NDX(3).EQ.INDX(LOCAL_INDX(2))%A .AND. INTERFACE_NDX(KK)%LC_NDX(4).EQ.INDX(LOCAL_INDX(2))%B) THEN
				GLOBAL_INDX(2) = INTERFACE_NDX(KK)%GL_NDX
				GOTO 20
			ELSE
				GLOBAL_INDX(2) = 0
			ENDIF
		ENDDO
		20 CONTINUE
	ENDIF

	DO KK=1, UBOUND(INTERFACE_NDX,1)
		IF (INTERFACE_NDX(KK)%MASTER_PATCH_NDX.EQ.PATCH(1) .AND. INTERFACE_NDX(KK)%SLAVE_PATCH_NDX(3).EQ.PATCH(2) .AND. &
				INTERFACE_NDX(KK)%LC_NDX(7).EQ.INDX(LOCAL_INDX(1))%A .AND. INTERFACE_NDX(KK)%LC_NDX(8).EQ.INDX(LOCAL_INDX(1))%B) THEN
			GLOBAL_INDX(3) = INTERFACE_NDX(KK)%GL_NDX
			GOTO 30
		ELSE
			GLOBAL_INDX(3) = 0
		ENDIF
	ENDDO
	30 CONTINUE

	IF (GLOBAL_INDX(3).EQ.0) THEN
		GLOBAL_INDX(4) = 0
	ELSE
		DO KK=1, UBOUND(INTERFACE_NDX,1)
			IF (INTERFACE_NDX(KK)%SLAVE_PATCH_NDX(1).EQ.PATCH(2) .AND. &
					INTERFACE_NDX(KK)%LC_NDX(3).EQ.INDX(LOCAL_INDX(2))%A .AND. INTERFACE_NDX(KK)%LC_NDX(4).EQ.INDX(LOCAL_INDX(2))%B) THEN
				GLOBAL_INDX(4) = INTERFACE_NDX(KK)%GL_NDX
				GOTO 40
			ELSE
			GLOBAL_INDX(4) = 0
			ENDIF
		ENDDO
	ENDIF
	40 CONTINUE
	
END SUBROUTINE STIF_FIND_GLOBAL_INDX_ALONG_INTERFACE_FIJ

SUBROUTINE STIF_FIND_GLOBAL_INDX_INTERFACE_AND_NONINTERFACE(GLOBAL_INDX, PATCH, LOCAL_INDX, INDX)
	INTEGER, INTENT(OUT) :: GLOBAL_INDX(6)
	INTEGER, INTENT(IN) :: PATCH(2), LOCAL_INDX(2)	! PATCH(1) = MASTER_PATCH, PATCH(2) = SLAVE_PATCH
	TYPE(INT2D), INTENT(IN) :: INDX((BASIS_KVEC(PATCH(2),1)%POLY_ORDER+1)*(BASIS_KVEC(PATCH(2),2)%POLY_ORDER+1))
	
	INTEGER :: I, J, K, II, JJ, KK, LOCAL_DOF_SUM
	
	GLOBAL_INDX(:) = 0
	
	IF (PATCH(2).EQ.1) THEN
		LOCAL_DOF_SUM = 0
	ELSE
		LOCAL_DOF_SUM = SUM(LOCAL_DOF(1:PATCH(2)-1))
	ENDIF
	
! 	DO I = 1, UBOUND(GLOBAL_INDX,1)
! 		IF (MOD(I,2).NE.0) THEN
! 			DO KK=1, UBOUND(INTERFACE_NDX,1)
! 				IF (INTERFACE_NDX(KK)%MASTER_PATCH_NDX.EQ.PATCH(1) .AND. INTERFACE_NDX(KK)%SLAVE_PATCH_NDX(?).EQ.PATCH(2) .AND. &
! 						INTERFACE_NDX(KK)%LC_NDX(I+2).EQ.INDX(LOCAL_INDX(1))%A .AND. INTERFACE_NDX(KK)%LC_NDX(I+3).EQ.INDX(LOCAL_INDX(1))%B) THEN
! 					GLOBAL_INDX(I) = INTERFACE_NDX(KK)%GL_NDX
! 					GOTO 10
! 				ELSE
! 					GLOBAL_INDX(1) = 0
! 				ENDIF
! 			ENDDO
! 			10 CONTINUE
! 		ELSE
! 			IF (GLOBAL_INDX(1)==0) THEN
! 			ELSE
! 				DO KK = LOCAL_DOF_SUM + 1, LOCAL_DOF_SUM + LOCAL_DOF(PATCH(2))
! 					IF (NDX(1,KK).EQ.INDX(LOCAL_INDX(2))%A .AND. NDX(2,KK).EQ.INDX(LOCAL_INDX(2))%B) THEN
! 						GLOBAL_INDX(I) = KK
! 						GOTO 20
! 					ELSE
! 						GLOBAL_INDX(2) = 0
! 					ENDIF
! 				ENDDO
! 				20 CONTINUE
! 			ENDIF
! 		ENDIF		
! 		IF (I.GE.2 .AND. GLOBAL_INDX(I-1).NE.0 .AND. GLOBAL_INDX(I).NE.0) THEN
! 			GOTO 11
! 		ENDIF
! 	ENDDO
! 	11 CONTINUE
	
	DO KK=1, UBOUND(INTERFACE_NDX,1)
		IF (INTERFACE_NDX(KK)%MASTER_PATCH_NDX.EQ.PATCH(1) .AND. INTERFACE_NDX(KK)%SLAVE_PATCH_NDX(1).EQ.PATCH(2) .AND. INTERFACE_NDX(KK)%LC_NDX(3).EQ.INDX(LOCAL_INDX(1))%A .AND. INTERFACE_NDX(KK)%LC_NDX(4).EQ.INDX(LOCAL_INDX(1))%B) THEN
			GLOBAL_INDX(1) = INTERFACE_NDX(KK)%GL_NDX
			GOTO 555
		ELSE
			GLOBAL_INDX(1) = 0
		ENDIF
	ENDDO
	555 CONTINUE
		
	IF (GLOBAL_INDX(1).EQ.0) THEN
		GLOBAL_INDX(2) = 0
	ELSE
		DO KK = LOCAL_DOF_SUM + 1, LOCAL_DOF_SUM + LOCAL_DOF(PATCH(2))
			IF (NDX(1,KK).EQ.INDX(LOCAL_INDX(2))%A .AND. NDX(2,KK).EQ.INDX(LOCAL_INDX(2))%B) THEN
				GLOBAL_INDX(2) = KK
				GOTO 666
			ELSE
			GLOBAL_INDX(2) = 0
			ENDIF
		ENDDO
		666 CONTINUE
	ENDIF
	
	DO KK=1, UBOUND(INTERFACE_NDX,1)
		IF (INTERFACE_NDX(KK)%MASTER_PATCH_NDX.EQ.PATCH(1) .AND. INTERFACE_NDX(KK)%SLAVE_PATCH_NDX(2).EQ.PATCH(2) .AND. INTERFACE_NDX(KK)%LC_NDX(5).EQ.INDX(LOCAL_INDX(1))%A .AND. INTERFACE_NDX(KK)%LC_NDX(6).EQ.INDX(LOCAL_INDX(1))%B) THEN
			GLOBAL_INDX(3) = INTERFACE_NDX(KK)%GL_NDX
			GOTO 5559
		ELSE
			GLOBAL_INDX(3) = 0
		ENDIF
	ENDDO
	5559 CONTINUE
	
	IF (GLOBAL_INDX(3).EQ.0) THEN
		GLOBAL_INDX(4) = 0
	ELSE
		DO KK = LOCAL_DOF_SUM + 1, LOCAL_DOF_SUM + LOCAL_DOF(PATCH(2))
			IF (NDX(1,KK).EQ.INDX(LOCAL_INDX(2))%A .AND. NDX(2,KK).EQ.INDX(LOCAL_INDX(2))%B) THEN
				GLOBAL_INDX(4) = KK
				GOTO 6789
			ELSE
			GLOBAL_INDX(4) = 0
			ENDIF
		ENDDO
		6789 CONTINUE
	ENDIF
	
	DO KK=1, UBOUND(INTERFACE_NDX,1)
		IF (INTERFACE_NDX(KK)%MASTER_PATCH_NDX.EQ.PATCH(1) .AND. INTERFACE_NDX(KK)%SLAVE_PATCH_NDX(3).EQ.PATCH(2) .AND. INTERFACE_NDX(KK)%LC_NDX(7).EQ.INDX(LOCAL_INDX(1))%A .AND. INTERFACE_NDX(KK)%LC_NDX(8).EQ.INDX(LOCAL_INDX(1))%B) THEN
			GLOBAL_INDX(5) = INTERFACE_NDX(KK)%GL_NDX
			GOTO 579
		ELSE
			GLOBAL_INDX(5) = 0
		ENDIF
	ENDDO
	579 CONTINUE
	
	IF (GLOBAL_INDX(5).EQ.0) THEN
		GLOBAL_INDX(6) = 0
	ELSE
		DO KK = LOCAL_DOF_SUM + 1, LOCAL_DOF_SUM + LOCAL_DOF(PATCH(2))
			IF (NDX(1,KK).EQ.INDX(LOCAL_INDX(2))%A .AND. NDX(2,KK).EQ.INDX(LOCAL_INDX(2))%B) THEN
				GLOBAL_INDX(6) = KK
				GOTO 6669
			ELSE
			GLOBAL_INDX(6) = 0
			ENDIF
		ENDDO
		6669 CONTINUE
	ENDIF
	
END SUBROUTINE STIF_FIND_GLOBAL_INDX_INTERFACE_AND_NONINTERFACE

SUBROUTINE STIF_FIND_GLOBAL_INDX_INTERFACE_AND_EGM(GLOBAL_INDX, PATCHES, LOCAL_INDX, INDX1, INDX2)
	INTEGER, INTENT(IN) :: PATCHES(2), LOCAL_INDX(2) ! PATCHES(1) = IGA_PATCH, PATCHES(2) = EGM_PATCH
	TYPE(INT2D), INTENT(IN) :: INDX1((BASIS_KVEC(PATCHES(1),1)%POLY_ORDER+1)*(BASIS_KVEC(PATCHES(1),2)%POLY_ORDER+1))
	TYPE(INT2D), INTENT(IN) :: INDX2((BASIS_KVEC(PATCHES(2),1)%POLY_ORDER+1)*(BASIS_KVEC(PATCHES(2),2)%POLY_ORDER+1))
	INTEGER, INTENT(OUT) :: GLOBAL_INDX(2)
	
	INTEGER :: I, J, K, II, JJ, KK, LOCAL_DOF_SUM
	
	GLOBAL_INDX(:) = 0
	
	IF (PATCHES(2).EQ.1) THEN
		LOCAL_DOF_SUM = 0
	ELSE
		LOCAL_DOF_SUM = SUM(LOCAL_DOF(1:PATCHES(2)-1))
	ENDIF
	
	DO KK=1, UBOUND(INTERFACE_NDX,1)
		IF (INTERFACE_NDX(KK)%SLAVE_PATCH_NDX(1).EQ.PATCHES(1) .AND. &
				INTERFACE_NDX(KK)%LC_NDX(3).EQ.INDX1(LOCAL_INDX(1))%A .AND. INTERFACE_NDX(KK)%LC_NDX(4).EQ.INDX1(LOCAL_INDX(1))%B) THEN
			GLOBAL_INDX(1) = INTERFACE_NDX(KK)%GL_NDX
			GOTO 20
		ELSE
			GLOBAL_INDX(1) = 0
		ENDIF
	ENDDO
	20 CONTINUE
	
	DO KK=1, LOCAL_DOF(PATCHES(2))
		IF (NDX(1,LOCAL_DOF_SUM + KK).EQ.INDX2(LOCAL_INDX(2))%A .AND. NDX(2,LOCAL_DOF_SUM + KK).EQ.INDX2(LOCAL_INDX(2))%B) THEN
			GLOBAL_INDX(2) = LOCAL_DOF_SUM + KK
			GOTO 10
		ELSE
			GLOBAL_INDX(2) = 0
		ENDIF
	ENDDO
	10 CONTINUE
	
END SUBROUTINE STIF_FIND_GLOBAL_INDX_INTERFACE_AND_EGM

SUBROUTINE STIF_GET_ELEMENT(STIF_K, GLOBAL_INDX, DIFF_XX, DIFF_YY, DIFF_XY, DIFF_YX, SYM)
	REAL*8, INTENT(INOUT) :: STIF_K(2*DOF,2*DOF)
	INTEGER, INTENT(IN) :: GLOBAL_INDX(6)
	REAL*8, INTENT(IN) :: DIFF_XX, DIFF_YY, DIFF_XY, DIFF_YX
	CHARACTER(LEN=3), OPTIONAL, INTENT(IN) :: SYM
	
	IF (PRESENT(SYM)) THEN
		IF (GLOBAL_INDX(1).NE.0 .AND. GLOBAL_INDX(2).NE.0) THEN
			STIF_K(		 GLOBAL_INDX(1),		GLOBAL_INDX(2)) = STIF_K(		 GLOBAL_INDX(1),		GLOBAL_INDX(2)) + STRESS_E(1,1)*DIFF_XX + STRESS_E(3,3)*DIFF_YY
			STIF_K(DOF+GLOBAL_INDX(1),DOF+GLOBAL_INDX(2)) = STIF_K(DOF+GLOBAL_INDX(1),DOF+GLOBAL_INDX(2)) + STRESS_E(2,2)*DIFF_YY + STRESS_E(3,3)*DIFF_XX
			STIF_K(		 GLOBAL_INDX(1),DOF+GLOBAL_INDX(2)) = STIF_K(		 GLOBAL_INDX(1),DOF+GLOBAL_INDX(2)) + STRESS_E(1,2)*DIFF_XY + STRESS_E(3,3)*DIFF_YX
! 			STIF_K(DOF+GLOBAL_INDX(2),GLOBAL_INDX(1)) = STIF_K(DOF+GLOBAL_INDX(2),GLOBAL_INDX(1)) + STRESS_E(2,1)*DIFF_XY + STRESS_E(3,3)*DIFF_YX
			
			IF (GLOBAL_INDX(1).NE.GLOBAL_INDX(2)) THEN
				STIF_K(		 GLOBAL_INDX(2),		GLOBAL_INDX(1)) = STIF_K(		 GLOBAL_INDX(2),		GLOBAL_INDX(1)) + STRESS_E(1,1)*DIFF_XX + STRESS_E(3,3)*DIFF_YY
				STIF_K(DOF+GLOBAL_INDX(2),DOF+GLOBAL_INDX(1)) = STIF_K(DOF+GLOBAL_INDX(2),DOF+GLOBAL_INDX(1)) + STRESS_E(2,2)*DIFF_YY + STRESS_E(3,3)*DIFF_XX
				STIF_K(		 GLOBAL_INDX(2),DOF+GLOBAL_INDX(1)) = STIF_K(		 GLOBAL_INDX(2),DOF+GLOBAL_INDX(1)) + STRESS_E(1,2)*DIFF_YX + STRESS_E(3,3)*DIFF_XY
! 				STIF_K(DOF+GLOBAL_INDX(1),GLOBAL_INDX(2)) = STIF_K(DOF+GLOBAL_INDX(1),GLOBAL_INDX(2)) + STRESS_E(2,1)*DIFF_YX + STRESS_E(3,3)*DIFF_XY
			ENDIF
		ENDIF
		IF (GLOBAL_INDX(3).NE.0 .AND. GLOBAL_INDX(4).NE.0) THEN
			STIF_K(		 GLOBAL_INDX(3),		GLOBAL_INDX(4)) = STIF_K(		 GLOBAL_INDX(3),		GLOBAL_INDX(4)) + STRESS_E(1,1)*DIFF_XX + STRESS_E(3,3)*DIFF_YY
			STIF_K(DOF+GLOBAL_INDX(3),DOF+GLOBAL_INDX(4)) = STIF_K(DOF+GLOBAL_INDX(3),DOF+GLOBAL_INDX(4)) + STRESS_E(2,2)*DIFF_YY + STRESS_E(3,3)*DIFF_XX
			STIF_K(		 GLOBAL_INDX(3),DOF+GLOBAL_INDX(4)) = STIF_K(		 GLOBAL_INDX(3),DOF+GLOBAL_INDX(4)) + STRESS_E(1,2)*DIFF_XY + STRESS_E(3,3)*DIFF_YX
! 			STIF_K(DOF+GLOBAL_INDX(4),GLOBAL_INDX(3)) = STIF_K(DOF+GLOBAL_INDX(4),GLOBAL_INDX(3)) + STRESS_E(2,1)*DIFF_XY + STRESS_E(3,3)*DIFF_YX
			
			IF (GLOBAL_INDX(3).NE.GLOBAL_INDX(4)) THEN
				STIF_K(		 GLOBAL_INDX(4),		GLOBAL_INDX(3)) = STIF_K(		 GLOBAL_INDX(4),		GLOBAL_INDX(3)) + STRESS_E(1,1)*DIFF_XX + STRESS_E(3,3)*DIFF_YY
				STIF_K(DOF+GLOBAL_INDX(4),DOF+GLOBAL_INDX(3)) = STIF_K(DOF+GLOBAL_INDX(4),DOF+GLOBAL_INDX(3)) + STRESS_E(2,2)*DIFF_YY + STRESS_E(3,3)*DIFF_XX
				STIF_K(		 GLOBAL_INDX(4),DOF+GLOBAL_INDX(3)) = STIF_K(		 GLOBAL_INDX(4),DOF+GLOBAL_INDX(3)) + STRESS_E(1,2)*DIFF_YX + STRESS_E(3,3)*DIFF_XY
! 				STIF_K(DOF+GLOBAL_INDX(3),GLOBAL_INDX(4)) = STIF_K(DOF+GLOBAL_INDX(3),GLOBAL_INDX(4)) + STRESS_E(2,1)*DIFF_YX + STRESS_E(3,3)*DIFF_XY
			ENDIF
		ENDIF
		IF (GLOBAL_INDX(5).NE.0 .AND. GLOBAL_INDX(6).NE.0) THEN
			STIF_K(		 GLOBAL_INDX(5),		GLOBAL_INDX(6)) = STIF_K(		 GLOBAL_INDX(5),		GLOBAL_INDX(6)) + STRESS_E(1,1)*DIFF_XX + STRESS_E(3,3)*DIFF_YY
			STIF_K(DOF+GLOBAL_INDX(5),DOF+GLOBAL_INDX(6)) = STIF_K(DOF+GLOBAL_INDX(5),DOF+GLOBAL_INDX(6)) + STRESS_E(2,2)*DIFF_YY + STRESS_E(3,3)*DIFF_XX
			STIF_K(		 GLOBAL_INDX(5),DOF+GLOBAL_INDX(6)) = STIF_K(		 GLOBAL_INDX(5),DOF+GLOBAL_INDX(6)) + STRESS_E(1,2)*DIFF_XY + STRESS_E(3,3)*DIFF_YX
! 			STIF_K(DOF+GLOBAL_INDX(6),GLOBAL_INDX(5)) = STIF_K(DOF+GLOBAL_INDX(6),GLOBAL_INDX(5)) + STRESS_E(2,1)*DIFF_XY + STRESS_E(3,3)*DIFF_YX

			IF (GLOBAL_INDX(5).NE.GLOBAL_INDX(6)) THEN
				STIF_K(		 GLOBAL_INDX(6),		GLOBAL_INDX(5)) = STIF_K(		 GLOBAL_INDX(6),		GLOBAL_INDX(5)) + STRESS_E(1,1)*DIFF_XX + STRESS_E(3,3)*DIFF_YY
				STIF_K(DOF+GLOBAL_INDX(6),DOF+GLOBAL_INDX(5)) = STIF_K(DOF+GLOBAL_INDX(6),DOF+GLOBAL_INDX(5)) + STRESS_E(2,2)*DIFF_YY + STRESS_E(3,3)*DIFF_XX
				STIF_K(		 GLOBAL_INDX(6),DOF+GLOBAL_INDX(5)) = STIF_K(		 GLOBAL_INDX(6),DOF+GLOBAL_INDX(5)) + STRESS_E(1,2)*DIFF_YX + STRESS_E(3,3)*DIFF_XY
! 				STIF_K(DOF+GLOBAL_INDX(5),GLOBAL_INDX(6)) = STIF_K(DOF+GLOBAL_INDX(5),GLOBAL_INDX(6)) + STRESS_E(2,1)*DIFF_YX + STRESS_E(3,3)*DIFF_XY
			ENDIF
		ENDIF
	ELSE
		IF (GLOBAL_INDX(1).NE.0 .AND. GLOBAL_INDX(2).NE.0) THEN
			STIF_K(		 GLOBAL_INDX(1),		GLOBAL_INDX(2)) = STIF_K(		 GLOBAL_INDX(1),		GLOBAL_INDX(2)) + STRESS_E(1,1)*DIFF_XX + STRESS_E(3,3)*DIFF_YY
			STIF_K(DOF+GLOBAL_INDX(1),DOF+GLOBAL_INDX(2)) = STIF_K(DOF+GLOBAL_INDX(1),DOF+GLOBAL_INDX(2)) + STRESS_E(2,2)*DIFF_YY + STRESS_E(3,3)*DIFF_XX
			STIF_K(		 GLOBAL_INDX(1),DOF+GLOBAL_INDX(2)) = STIF_K(		 GLOBAL_INDX(1),DOF+GLOBAL_INDX(2)) + STRESS_E(1,2)*DIFF_XY + STRESS_E(3,3)*DIFF_YX
! 			STIF_K(DOF+GLOBAL_INDX(2),GLOBAL_INDX(1)) = STIF_K(DOF+GLOBAL_INDX(2),GLOBAL_INDX(1)) + STRESS_E(2,1)*DIFF_XY + STRESS_E(3,3)*DIFF_YX
		ENDIF
		IF (GLOBAL_INDX(3).NE.0 .AND. GLOBAL_INDX(4).NE.0) THEN
			STIF_K(		 GLOBAL_INDX(3),		GLOBAL_INDX(4)) = STIF_K(		 GLOBAL_INDX(3),		GLOBAL_INDX(4)) + STRESS_E(1,1)*DIFF_XX + STRESS_E(3,3)*DIFF_YY
			STIF_K(DOF+GLOBAL_INDX(3),DOF+GLOBAL_INDX(4)) = STIF_K(DOF+GLOBAL_INDX(3),DOF+GLOBAL_INDX(4)) + STRESS_E(2,2)*DIFF_YY + STRESS_E(3,3)*DIFF_XX
			STIF_K(		 GLOBAL_INDX(3),DOF+GLOBAL_INDX(4)) = STIF_K(		 GLOBAL_INDX(3),DOF+GLOBAL_INDX(4)) + STRESS_E(1,2)*DIFF_XY + STRESS_E(3,3)*DIFF_YX
! 			STIF_K(DOF+GLOBAL_INDX(4),GLOBAL_INDX(3)) = STIF_K(DOF+GLOBAL_INDX(4),GLOBAL_INDX(3)) + STRESS_E(2,1)*DIFF_XY + STRESS_E(3,3)*DIFF_YX
		ENDIF
		IF (GLOBAL_INDX(5).NE.0 .AND. GLOBAL_INDX(6).NE.0) THEN
			STIF_K(		 GLOBAL_INDX(5),		GLOBAL_INDX(6)) = STIF_K(		 GLOBAL_INDX(5),		GLOBAL_INDX(6)) + STRESS_E(1,1)*DIFF_XX + STRESS_E(3,3)*DIFF_YY
			STIF_K(DOF+GLOBAL_INDX(5),DOF+GLOBAL_INDX(6)) = STIF_K(DOF+GLOBAL_INDX(5),DOF+GLOBAL_INDX(6)) + STRESS_E(2,2)*DIFF_YY + STRESS_E(3,3)*DIFF_XX
			STIF_K(		 GLOBAL_INDX(5),DOF+GLOBAL_INDX(6)) = STIF_K(		 GLOBAL_INDX(5),DOF+GLOBAL_INDX(6)) + STRESS_E(1,2)*DIFF_XY + STRESS_E(3,3)*DIFF_YX
! 			STIF_K(DOF+GLOBAL_INDX(6),GLOBAL_INDX(5)) = STIF_K(DOF+GLOBAL_INDX(6),GLOBAL_INDX(5)) + STRESS_E(2,1)*DIFF_XY + STRESS_E(3,3)*DIFF_YX
		ENDIF
	ENDIF
	
END SUBROUTINE STIF_GET_ELEMENT

SUBROUTINE LOAD_VC_GET_ELEMENT(STIF_F, GLOBAL_INDX, DIFF_NN, UV)
	REAL*8, INTENT(INOUT) :: STIF_F(2*DOF)
	INTEGER, INTENT(IN) :: GLOBAL_INDX(6)
	REAL*8, INTENT(IN) :: DIFF_NN
	CHARACTER(LEN=1), INTENT(IN) :: UV
	
	IF (UV=='U') THEN
		IF (GLOBAL_INDX(1).NE.0) THEN
			STIF_F(GLOBAL_INDX(1)) = STIF_F(GLOBAL_INDX(1)) + DIFF_NN
		ENDIF
		IF (GLOBAL_INDX(3).NE.0) THEN
			STIF_F(GLOBAL_INDX(3)) = STIF_F(GLOBAL_INDX(3)) + DIFF_NN
		ENDIF
		IF (GLOBAL_INDX(5).NE.0) THEN
			STIF_F(GLOBAL_INDX(5)) = STIF_F(GLOBAL_INDX(5)) + DIFF_NN
		ENDIF
	ELSEIF (UV=='V') THEN
		IF (GLOBAL_INDX(1).NE.0) THEN
			STIF_F(DOF + GLOBAL_INDX(1)) = STIF_F(DOF + GLOBAL_INDX(1)) + DIFF_NN
		ENDIF
		IF (GLOBAL_INDX(3).NE.0) THEN
			STIF_F(DOF + GLOBAL_INDX(3)) = STIF_F(DOF + GLOBAL_INDX(3)) + DIFF_NN
		ENDIF
		IF (GLOBAL_INDX(5).NE.0) THEN
			STIF_F(DOF + GLOBAL_INDX(5)) = STIF_F(DOF + GLOBAL_INDX(5)) + DIFF_NN
		ENDIF
	ENDIF

END SUBROUTINE LOAD_VC_GET_ELEMENT
	
SUBROUTINE LEAST_SQUARE_LC_INT_II(SF, INDX, WEIGHT, EXACT_ON_BD, PATCH, SUB_LN, GAMMA_HAT)
	INTEGER, INTENT(IN) :: PATCH
	TYPE(VEC2D), INTENT(IN) :: SUB_LN
	CHARACTER(LEN=1), INTENT(IN) :: GAMMA_HAT
	
	TYPE(FVALUE), INTENT(OUT) :: SF(NUMGSPT, (BASIS_KVEC(PATCH,1)%POLY_ORDER+1)*(BASIS_KVEC(PATCH,2)%POLY_ORDER+1))
	TYPE(INT2D), INTENT(OUT) :: INDX((BASIS_KVEC(PATCH,1)%POLY_ORDER+1)*(BASIS_KVEC(PATCH,2)%POLY_ORDER+1))
	REAL*8, INTENT(OUT) :: WEIGHT(NUMGSPT)
	TYPE(POINT2D), INTENT(OUT) :: EXACT_ON_BD(NUMGSPT)
	
	TYPE(POINT2D) :: GSPT, DMY_GSPT
	REAL*8 :: DET_M
	INTEGER :: I, J, II, JJ, KK
	TYPE(MATRIX_22) :: JACOB
	
	IF (GAMMA_HAT=='B' .OR. GAMMA_HAT=='T') THEN
		CALL GAULEG(SUB_LN%U%X, SUB_LN%V%X, GSX, GSXW, NUMGSPT)
	ELSE
		CALL GAULEG(SUB_LN%U%Y, SUB_LN%V%Y, GSY, GSYW, NUMGSPT)
	ENDIF
	
	DO I=1,NUMGSPT
		IF (GAMMA_HAT=='B') THEN
			GSPT = POINT2D(GSX(I), 0.D0)
		ELSEIF (GAMMA_HAT=='T') THEN
			GSPT = POINT2D(GSX(I), 1.D0)
		ELSEIF (GAMMA_HAT=='L') THEN
			GSPT = POINT2D(0.D0, GSY(I))
		ELSEIF (GAMMA_HAT=='R') THEN
			GSPT = POINT2D(1.D0, GSY(I))
		ENDIF
		DMY_GSPT = GSPT
		JACOB = GET_JACOBIAN_MATRIX(DMY_GSPT,PATCH)
		DET_M = .DETERMINANT.JACOB
		IF (GAMMA_HAT=='B' .OR. GAMMA_HAT=='T') THEN
			WEIGHT(I) = DET_M*GSXW(I)
		ELSEIF (GAMMA_HAT=='L' .OR. GAMMA_HAT=='R') THEN
			WEIGHT(I) = DET_M*GSYW(I)
		ENDIF
! 		IF (PATCH.LE.NUM_IGA_PATCH) THEN
			CALL GET_ALL_PHY_NURBS_SURFACE_2D(SF(I,:), INDX(:), DMY_GSPT, JACOB, PATCH)
! 		ELSE
! 			CALL GET_ALL_PHY_BASIS_IN_INT(SF(I,:), INDX(:), DMY_GSPT, JACOB, PATCH)
! 		ENDIF
		EXACT_ON_BD(I) = EX_DISP(DMY_GSPT,PATCH)
! 					PRINT*, I, EXACT_ON_BD(I)
	ENDDO

END SUBROUTINE LEAST_SQUARE_LC_INT_II

SUBROUTINE LEAST_SQUARE_LC_INT_IJ(SF1, SF2, INDX1, INDX2, WEIGHT, PATCHES, SUB_LN, GAMMA_HAT)
	
	INTEGER, INTENT(IN) :: PATCHES(2) ! PATCHES(1) = IGA_PATCH,  PATCHES(2) = EGM_PATCH
	TYPE(VEC2D), INTENT(IN) :: SUB_LN
	CHARACTER(LEN=1), INTENT(IN) :: GAMMA_HAT
	
	TYPE(FVALUE), INTENT(OUT) :: SF1(NUMGSPT, (BASIS_KVEC(PATCHES(1),1)%POLY_ORDER+1)*(BASIS_KVEC(PATCHES(1),2)%POLY_ORDER+1))
	TYPE(FVALUE), INTENT(OUT) :: SF2(NUMGSPT, (BASIS_KVEC(PATCHES(2),1)%POLY_ORDER+1)*(BASIS_KVEC(PATCHES(2),2)%POLY_ORDER+1))
	TYPE(INT2D), INTENT(OUT) :: INDX1((BASIS_KVEC(PATCHES(1),1)%POLY_ORDER+1)*(BASIS_KVEC(PATCHES(1),2)%POLY_ORDER+1))
	TYPE(INT2D), INTENT(OUT) :: INDX2((BASIS_KVEC(PATCHES(2),1)%POLY_ORDER+1)*(BASIS_KVEC(PATCHES(2),2)%POLY_ORDER+1))
	REAL*8, INTENT(OUT) :: WEIGHT(NUMGSPT)
	
	TYPE(POINT2D) :: GSPT, DMY_GSPT, PHYPT_F, INV_PHYPT_G
	REAL*8 :: DET_M
	INTEGER :: I, J, II, JJ, KK
	TYPE(MATRIX_22) :: JACOB
	
	IF (GAMMA_HAT=='B' .OR. GAMMA_HAT=='T') THEN
		CALL GAULEG(SUB_LN%U%X, SUB_LN%V%X, GSX, GSXW, NUMGSPT)
	ELSE
		CALL GAULEG(SUB_LN%U%Y, SUB_LN%V%Y, GSY, GSYW, NUMGSPT)
	ENDIF
	
	DO I=1,NUMGSPT
		IF (GAMMA_HAT=='B') THEN
			GSPT = POINT2D(GSX(I), 0.D0)
		ELSEIF (GAMMA_HAT=='T') THEN
			GSPT = POINT2D(GSX(I), 1.D0)
		ELSEIF (GAMMA_HAT=='L') THEN
			GSPT = POINT2D(0.D0, GSY(I))
		ELSEIF (GAMMA_HAT=='R') THEN
			GSPT = POINT2D(1.D0, GSY(I))
		ENDIF
		
		DMY_GSPT = GSPT
		PHYPT_F = GET_PHY_PT(DMY_GSPT, PATCHES(2))
		INV_PHYPT_G = GET_REF_PT(PHYPT_F, PATCHES(1))
		
		JACOB = GET_JACOBIAN_MATRIX(DMY_GSPT,PATCHES(2))
		DET_M = .DETERMINANT.JACOB
		
		IF (GAMMA_HAT=='B' .OR. GAMMA_HAT=='T') THEN
			WEIGHT(I) = DET_M*GSXW(I)
		ELSEIF (GAMMA_HAT=='L' .OR. GAMMA_HAT=='R') THEN
			WEIGHT(I) = DET_M*GSYW(I)
		ENDIF
		
		CALL GET_ALL_PHY_NURBS_SURFACE_2D(SF1(I,:), INDX1(:), INV_PHYPT_G, JACOB, PATCHES(1))
		CALL GET_ALL_PHY_BASIS_IN_INT(SF2(I,:), INDX2(:), DMY_GSPT, JACOB, PATCHES(2))
	ENDDO

END SUBROUTINE LEAST_SQUARE_LC_INT_IJ

SUBROUTINE DR_GL_INDX_FII(GLOBAL_INDX, PATCH, LOCAL_INDX, INDX)
	INTEGER, INTENT(IN) :: PATCH, LOCAL_INDX(2)
	TYPE(INT2D), INTENT(IN) :: INDX((BASIS_KVEC(PATCH,1)%POLY_ORDER+1)*(BASIS_KVEC(PATCH,2)%POLY_ORDER+1))
	INTEGER, INTENT(OUT) :: GLOBAL_INDX(2)
	
	INTEGER :: I, J, K, II, JJ, KK, LC_NUM_SUM
	
	GLOBAL_INDX(:) = 0
	
	IF (PATCH.EQ.1) THEN
		LC_NUM_SUM = 0
	ELSE
		LC_NUM_SUM = SUM(DR_BDNDX(1:PATCH-1,1)%LC_NUM)
	ENDIF

	DO KK=1, DR_BDNDX(PATCH,1)%LC_NUM
! 				PRINT*, 'KK',KK
		IF (DR_BDNDX(PATCH,KK)%LC_NDX(1).EQ.INDX(LOCAL_INDX(1))%A .AND. DR_BDNDX(PATCH,KK)%LC_NDX(2).EQ.INDX(LOCAL_INDX(1))%B) THEN
			GLOBAL_INDX(1) = LC_NUM_SUM + KK
! 							PRINT*, PATCH, 'G1', GLOBAL_INDX(1)
			GOTO 111
		ELSE
			GLOBAL_INDX(1) = 0
		ENDIF
	ENDDO
	111 CONTINUE

	DO KK=1, DR_BDNDX(PATCH,1)%LC_NUM
! 					PRINT*, 'KK',KK
		IF (DR_BDNDX(PATCH,KK)%LC_NDX(1).EQ.INDX(LOCAL_INDX(2))%A .AND. DR_BDNDX(PATCH,KK)%LC_NDX(2).EQ.INDX(LOCAL_INDX(2))%B) THEN
			GLOBAL_INDX(2) = LC_NUM_SUM + KK
! 								PRINT*, PATCH, 'G2', GLOBAL_INDX(2)
			GOTO 222
		ELSE
			GLOBAL_INDX(2) = 0
		ENDIF
	ENDDO
	222 CONTINUE

END SUBROUTINE DR_GL_INDX_FII

SUBROUTINE DR_GL_INDX_FIJ(GLOBAL_INDX, PATCHES, LOCAL_INDX, INDX1, INDX2)
	INTEGER, INTENT(IN) :: PATCHES(2), LOCAL_INDX(2)
	TYPE(INT2D), INTENT(IN) :: INDX1((BASIS_KVEC(PATCHES(1),1)%POLY_ORDER+1)*(BASIS_KVEC(PATCHES(1),2)%POLY_ORDER+1))
	TYPE(INT2D), INTENT(IN) :: INDX2((BASIS_KVEC(PATCHES(2),1)%POLY_ORDER+1)*(BASIS_KVEC(PATCHES(2),2)%POLY_ORDER+1))
	INTEGER, INTENT(OUT) :: GLOBAL_INDX(2)
	
	INTEGER :: I, J, K, II, JJ, KK, LC_NUM_SUM(2)
	
	GLOBAL_INDX(:) = 0
	
	DO I = 1, 2
		IF (PATCHES(I).EQ.1) THEN
			LC_NUM_SUM(I) = 0
		ELSE
			LC_NUM_SUM(I) = SUM(DR_BDNDX(1:PATCHES(I)-1,1)%LC_NUM)
		ENDIF
	ENDDO

	DO KK=1, DR_BDNDX(PATCHES(1),1)%LC_NUM
! 				PRINT*, 'KK',KK
		IF (DR_BDNDX(PATCHES(1),KK)%LC_NDX(1).EQ.INDX1(LOCAL_INDX(1))%A .AND. DR_BDNDX(PATCHES(1),KK)%LC_NDX(2).EQ.INDX1(LOCAL_INDX(1))%B) THEN
			GLOBAL_INDX(1) = LC_NUM_SUM(1) + KK
! 							PRINT*, PATCH, 'G1', GLOBAL_INDX(1)
			GOTO 111
		ELSE
			GLOBAL_INDX(1) = 0
		ENDIF
	ENDDO
	111 CONTINUE

	DO KK=1, DR_BDNDX(PATCHES(2),1)%LC_NUM
! 					PRINT*, 'KK',KK
		IF (DR_BDNDX(PATCHES(2),KK)%LC_NDX(1).EQ.INDX2(LOCAL_INDX(2))%A .AND. DR_BDNDX(PATCHES(2),KK)%LC_NDX(2).EQ.INDX2(LOCAL_INDX(2))%B) THEN
			GLOBAL_INDX(2) = LC_NUM_SUM(2) + KK
! 								PRINT*, PATCH, 'G2', GLOBAL_INDX(2)
			GOTO 222
		ELSE
			GLOBAL_INDX(2) = 0
		ENDIF
	ENDDO
	222 CONTINUE

END SUBROUTINE DR_GL_INDX_FIJ

SUBROUTINE DR_FIND_GL_INDX_ALONG_INTERFACE_FII(GLOBAL_INDX, PATCH, LOCAL_INDX, INDX)
	INTEGER, INTENT(OUT) :: GLOBAL_INDX(2)
	INTEGER, INTENT(IN) :: PATCH(2), LOCAL_INDX(2)	! PATCH(1) = MASTER_PATCH, PATCH(2) = SLAVE_PATCH
	TYPE(INT2D), INTENT(IN) :: INDX((BASIS_KVEC(PATCH(2),1)%POLY_ORDER+1)*(BASIS_KVEC(PATCH(2),2)%POLY_ORDER+1))
	
	INTEGER :: I, J, K, II, JJ, KK
	
	GLOBAL_INDX(:) = 0
	
	DO KK=1, UBOUND(INTERFACE_BDNDX,1)
		IF (INTERFACE_BDNDX(KK)%MASTER_PATCH_NDX.EQ.PATCH(1) .AND. INTERFACE_BDNDX(KK)%SLAVE_PATCH_NDX(1).EQ.PATCH(2) .AND. &
				INTERFACE_BDNDX(KK)%LC_NDX(3).EQ.INDX(LOCAL_INDX(1))%A .AND. INTERFACE_BDNDX(KK)%LC_NDX(4).EQ.INDX(LOCAL_INDX(1))%B) THEN
			GLOBAL_INDX(1) = INTERFACE_BDNDX(KK)%GL_BDNDX
			GOTO 112
		ELSE
			GLOBAL_INDX(1) = 0
		ENDIF
	ENDDO
	112 CONTINUE
	
	DO KK=1, UBOUND(INTERFACE_BDNDX,1)
		IF (INTERFACE_BDNDX(KK)%MASTER_PATCH_NDX.EQ.PATCH(1) .AND. INTERFACE_BDNDX(KK)%SLAVE_PATCH_NDX(1).EQ.PATCH(2) .AND. &
				INTERFACE_BDNDX(KK)%LC_NDX(3).EQ.INDX(LOCAL_INDX(2))%A .AND. INTERFACE_BDNDX(KK)%LC_NDX(4).EQ.INDX(LOCAL_INDX(2))%B) THEN
			GLOBAL_INDX(2) = INTERFACE_BDNDX(KK)%GL_BDNDX
			GOTO 223
		ELSE
			GLOBAL_INDX(2) = 0
		ENDIF
	ENDDO
	223 CONTINUE
					
END SUBROUTINE DR_FIND_GL_INDX_ALONG_INTERFACE_FII

SUBROUTINE DR_FIND_GL_INDX_ALONG_INTERFACE_FIJ(GLOBAL_INDX, PATCH, LOCAL_INDX, INDX)
	INTEGER, INTENT(OUT) :: GLOBAL_INDX(2)
	INTEGER, INTENT(IN) :: PATCH(2), LOCAL_INDX(2)	! PATCH(1) = MASTER_PATCH, PATCH(2) = SLAVE_PATCH
	TYPE(INT2D), INTENT(IN) :: INDX((BASIS_KVEC(PATCH(2),1)%POLY_ORDER+1)*(BASIS_KVEC(PATCH(2),2)%POLY_ORDER+1))
	INTEGER :: I, J, K, II, JJ, KK, LC_NUM_SUM

	GLOBAL_INDX(:) = 0
	
	IF (PATCH(2).EQ.1) THEN
		LC_NUM_SUM = 0
	ELSE
		LC_NUM_SUM = SUM(DR_BDNDX(1:PATCH(2)-1,1)%LC_NUM)
	ENDIF
	
	DO KK=1, UBOUND(INTERFACE_BDNDX,1)
		IF (INTERFACE_BDNDX(KK)%MASTER_PATCH_NDX.EQ.PATCH(1) .AND. INTERFACE_BDNDX(KK)%SLAVE_PATCH_NDX(1).EQ.PATCH(2) .AND. INTERFACE_BDNDX(KK)%LC_NDX(3).EQ.INDX(LOCAL_INDX(1))%A .AND. INTERFACE_BDNDX(KK)%LC_NDX(4).EQ.INDX(LOCAL_INDX(1))%B) THEN
			GLOBAL_INDX(1) = INTERFACE_BDNDX(KK)%GL_BDNDX
			GOTO 114
		ELSE
			GLOBAL_INDX(1) = 0
		ENDIF
	ENDDO
	114 CONTINUE

	DO KK=1, DR_BDNDX(PATCH(2),1)%LC_NUM
		IF (DR_BDNDX(PATCH(2),KK)%LC_NDX(1).EQ.INDX(LOCAL_INDX(2))%A .AND. DR_BDNDX(PATCH(2),KK)%LC_NDX(2).EQ.INDX(LOCAL_INDX(2))%B) THEN
			GLOBAL_INDX(2) = LC_NUM_SUM + KK
			GOTO 225
		ELSE
			GLOBAL_INDX(2) = 0
		ENDIF
	ENDDO
	225 CONTINUE
	
END SUBROUTINE DR_FIND_GL_INDX_ALONG_INTERFACE_FIJ

SUBROUTINE DR_FIND_GL_INDX_ALONG_INTERFACE_AND_NONINTERFACE(GLOBAL_INDX, PATCH, LOCAL_INDX, INDX)
	INTEGER, INTENT(OUT) :: GLOBAL_INDX(2)
	INTEGER, INTENT(IN) :: PATCH(2), LOCAL_INDX(2)	! PATCH(1) = MASTER_PATCH, PATCH(2) = SLAVE_PATCH
	TYPE(INT2D), INTENT(IN) :: INDX((BASIS_KVEC(PATCH(2),1)%POLY_ORDER+1)*(BASIS_KVEC(PATCH(2),2)%POLY_ORDER+1))
	INTEGER :: I, J, K, II, JJ, KK, LC_NUM_SUM

	GLOBAL_INDX(:) = 0
	
	IF (PATCH(2).EQ.1) THEN
		LC_NUM_SUM = 0
	ELSE
		LC_NUM_SUM = SUM(DR_BDNDX(1:PATCH(2)-1,1)%LC_NUM)
	ENDIF
	
	DO KK=1, UBOUND(INTERFACE_BDNDX,1)
		IF (INTERFACE_BDNDX(KK)%MASTER_PATCH_NDX.EQ.PATCH(1) .AND. INTERFACE_BDNDX(KK)%SLAVE_PATCH_NDX(1).EQ.PATCH(2) .AND. &
				INTERFACE_BDNDX(KK)%LC_NDX(3).EQ.INDX(LOCAL_INDX(1))%A .AND. INTERFACE_BDNDX(KK)%LC_NDX(4).EQ.INDX(LOCAL_INDX(1))%B) THEN
			GLOBAL_INDX(1) = INTERFACE_BDNDX(KK)%GL_BDNDX
			GOTO 114
		ELSE
			GLOBAL_INDX(1) = 0
		ENDIF
	ENDDO
	114 CONTINUE

	DO KK=1, DR_BDNDX(PATCH(2),1)%LC_NUM
		IF (DR_BDNDX(PATCH(2),KK)%LC_NDX(1).EQ.INDX(LOCAL_INDX(2))%A .AND. DR_BDNDX(PATCH(2),KK)%LC_NDX(2).EQ.INDX(LOCAL_INDX(2))%B) THEN
			GLOBAL_INDX(2) = LC_NUM_SUM + KK
			GOTO 225
		ELSE
			GLOBAL_INDX(2) = 0
		ENDIF
	ENDDO
	225 CONTINUE
	
END SUBROUTINE DR_FIND_GL_INDX_ALONG_INTERFACE_AND_NONINTERFACE

END MODULE INTEGRATION